### ISSUE TITLE
Typescript 2.4 dynamic imports error

### ISSUE THREAD

**Issue by hamedbaatour** [ng-packagr/ng-packagr#775] opened 2018-04-16 17:51 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
TypeScript 2.4 added support for dynamic imports via `import()` syntax however it does not seem to work.
I did set the languageLevel support to es2017 as stated in the docs  
```
    "lib": {
      "entryFile": "src/public_api.ts",
      "languageLevel": ["dom", "es2017"]
    },
```
but I still get this error when I run `yarn build:lib`
```
BUILD ERROR
my-lib/src/bar/bar.service.ts(11,5): error TS1323: Dynamic import cannot be used when targeting ECMAScript 2015 modules.
```

#### How To Reproduce
1.clone ng-packaged
2.add a dependency (momentjs)
3.add an import expression in bar.service.ts

#### Expected Behaviour
should support dynamic imports

#### Version Information
using the latest version of ng-packgr:
```
    "ng-packagr": "2.4.2",
    "@angular/core": "~5.2.0",
    "typescript": "~2.7.1",
     "node": 8.11.1
```

**Comment by lucasvst** [comment] 2018-06-28 17:33
@hamedbaatour did you manage how to do this using ng-packagr? I'm with the same trouble here.

**Comment by lucasvst** [comment] 2018-06-28 17:35
This issues are linked? #449

**Comment by Goonersid** [comment] 2018-07-23 17:55
Same here!

**Comment by ViceIce** [comment] 2019-07-15 11:17
duplicate of #449

**Comment by alan-agius4** [comment] 2020-04-23 17:16
duplicate of #449

**Closed by alan-agius4** 2020-04-23 17:16 UTC
