### ISSUE TITLE
StaticInjectorError when trying to inject service from root injector in package created with ng-packagr

### ISSUE THREAD

**Issue by ivanastefanoska** [ng-packagr/ng-packagr#490] opened 2018-01-12 13:53 UTC
## Type of Issue
```
[x] Bug Report
[ ] Feature Request
```

## Description

Provider/service injection not working after packaging.

#### How To Reproduce

```ts
// NPM package (mypackage)
@NgModule({
   imports: [ ... ],
   declarations: [
      HomeComponent
   ],
   exports: [
      HomeComponent
   ],
   providers: []
})
export class FeatureAModule { }

//home.component.ts
@component({
selector: 'home',
...
})
export class HomeComponent {
    constructor(private notifyService: NotifyService) { ... }
}

//Host application:
//package.json
  "dependencies": {
         ...
         "mypackage" : "1.0.0" (custom npm package created with ng-packagr and published)
  }

//app.module.ts
@NgModule({
  imports: [ 
     ..., 
     AppRoutes
  ],
  declarations: [
     AppComponent,
     AppHeaderComponent
   ],
   providers: [
     NotifyService
   ]
})
export class AppModule { }

//app.routes.ts
...
 {
        path: 'feature-a',
        loadChildren: 'mypackage#FeatureAModule',
}
```

#### Expected Behaviour

The NotifyService is listed in the NgModule's providers of the host application AppModule and should get injected in HomeComponent of mypackage.

When running the host application and lazy load the module, I got the error:
ERROR Error: StaticInjectorError[NotifyService]: 
  StaticInjectorError[NotifyService]: 
    NullInjectorError: No provider for NotifyService!

When the app starts, Angular eagerly loads the AppModule and registers NotifyService in the root app injector. When some component (AppHeaderComponent)  injects NotifyService, Angular finds it in the app root injector, and delivers the app-wide singleton NotifyService. No problem.

When Angular creates a component from lazy-loaded FeatureA module, it must inject a NotifyService. I expect it  to find the NotifyService provider in the root injector and use it here. But I got the above error.

If I add NotifyService in providers array of FeatureAModule in mypackage, when the router lazy loads the FeatureAModule , it will create a child injector and registers the NotifyService provider with that child injector. I want NotifyService to be an application-wide singleton. I don't want each Feature module to have its own separate instance. 

#### Version Information

```
ng-packagr: v2.0.0-rc.10
@angular/*: 5.2.0
typescript: ~2.6.1
rxjs: 5.5.6
node: 6.11.1
npm/yarn: 5.2.0
```

**Comment by kingcody** [comment] 2018-01-21 12:31
Duplicate of #299? Perhaps see #335.

**Comment by SchnWalter** [comment] 2021-02-08 14:22
The string version of `Route.loadChildren` is now deprecated in favor of  dynamic ES import, see:

   > https://github.com/angular/angular/blob/d067dc0cb9a3088a7c3443d33d35f7a0856b8a49/packages/router/src/config.ts#L124-L134

And `@Injectable({ providedIn: 'root' })` can now be used to have a global service that can be used anywhere. This would be a good alternative to the issue that the original reported wanted to avoid, which is actually caused by a bad architecture and a wrong understanding of how the Angular DI works.

@alan-agius4, this story should be closed, a lot has changed since it has been reported 3 years ago, and it has been stale since.

**Comment by alan-agius4** [comment] 2021-02-08 14:38
Closing as per above comment. Please re-open if the issue persists in v11x

**Closed by alan-agius4** 2021-02-08 14:38 UTC
