### ISSUE TITLE
Importing from a sibling library in subentry point is not working

### ISSUE THREAD

**Issue by bozhidarc** [ng-packagr/ng-packagr#2191] opened 2021-12-08 12:22 UTC
## Type of Issue

```
[X ] Bug Report
[ ] Feature Request
```

## Description

When import in a local library a module from a subpath of another sibling library I receive the following error 
> error TS2307:  Cannot find module 'lib-a' or its corresponding type declarations.

#### How To Reproduce
I have the following structure:
```
projects
    lib-a
        sub-path1
            sub-path1.component.ts
            sub-path1.module.ts
            public-api.ts
        sub-path2
            public-api.ts
        src
            lib
            public-api.ts
    lib-b
        src
            lib
                lib-b.module.ts <- import { SubPath1 } from 'lib-a/sub-path1';
                lib-b.component.ts
            public-api.ts
```

In the my `tsconfig` I have the following entries for `paths`.
```
"paths": [
    "lib-a": [
        "projects/lib-a/src/public-api",
    ],
    "lib-a/sub-path1": [
        "projects/lib-a/sub-path1/public-api",
    ],
    "lib-a/sub-path2": [
        "projects/lib-a/sub-path2/public-api",
    ],
    "lib-b": [
        "projects/lib-a/src/public-api",
    ],
]
```
When I build the library it throws the following error

> error TS2307:  Cannot find module 'lib-a' or its corresponding type declarations.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 12.2.5
@angular/*: 12.1.1
typescript: 4.3.2
rxjs: 6.6.0
node: v12.22.1
npm: 6.14.12
```

**Comment by SchnWalter** [comment] 2021-12-08 19:57
There isn't enough information in "How To Reproduce" to provide a definitive answer, a repository would have been more helpful here.

It's not enough to have some path aliases in your root TypeScript configuration. But by the looks of it, you need to define the peer dependency in the `package.json` of your 2nd library and you also need to have `ng-package.json` files for all secondary entry points.

> https://github.com/ng-packagr/ng-packagr/blob/v13.1.1/docs/secondary-entrypoints.md

**Comment by alan-agius4** [comment] 2022-05-11 07:19
Closing due to the lack reproducibility.

**Closed by alan-agius4** 2022-05-11 07:19 UTC
