### ISSUE TITLE
Can't find *.ngfactory.js after bundling module!

### ISSUE THREAD

**Issue by AhmedBHameed** [ng-packagr/ng-packagr#913] opened 2018-05-30 16:57 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug: After publishing a module and try testing it using ng serve --aot i get errors
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-pickydate' in '/home/ahmed/WWW/ngx-pickydate/src/app'
ERROR in ./src/app/app.component.ngfactory.js
Module not found: Error: Can't resolve 'ngx-pickydate' in '/home/ahmed/WWW/ngx-pickydate/src/app'
ERROR in ./src/app/ngx-pickydate/@ngx-pickydate/ngx-pickydate.ngfactory.js
Module not found: Error: Can't resolve 'ngx-pickydate' in '/home/ahmed/WWW/ngx-pickydate/src/app/ngx-pickydate/@ngx-pickydate'
ℹ ｢wdm｣: Failed to compile.
```
The module run fine without 'Ahead of Time' compilation. i mean with `ng serve`

#### How To Reproduce

_A bug: `ng serve --aot`

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_
After reading a bit about this error i found that this part inside tsconfig.json
```
"angularCompilerOptions": {
  "genDir": "compiled"
}
```
is responsible of generating ngFactory.js files. so do i miss something here !??

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.5
@angular/compiler:     6.0.3
@angular/compiler-cli: 6.0.3
rollup:                0.55.5
tsickle:               0.27.5
typescript:            2.7.2
```

No third party library.

**package.json of the modal**
```
{
    "$schema": "./node_modules/ng-packagr/package.schema.json",
    "name": "ngx-pickydate",
    "version": "1.0.5",
    "ngPackage": {
      "lib": {
        "entryFile": "index.ts"
      },
      "dest": "@ngx-pickydate"
    }
  }
```
**tsconfig.json**
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "genDir": "compiled",
    "fullTemplateTypeCheck": true,
    "preserveWhitespaces": true
  }
}

```

**package.json of the main project**
```
{
  "name": "testpackage",
  "version": "1.0.2",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "bundle": "ng-packagr -p src/app/ngx-pickydate/package.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "lib": {
    "entryFile": "ngx-pickydate.ts"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "~6.0.0",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^2.4.5",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslib": "^1.9.1",
    "tslint": "~5.9.1",
    "typescript": "^2.7.2"
  }
}

```

**Comment by alan-agius4** [comment] 2018-05-30 18:08
It looks like you don't have the correct path mappings in your `tsconfig.json`

In your main `tsconfig` you should have something similar to
```js
"compilerOptions": {
  ....
    "paths": {
      "ngx-pickydate": [
        "dist/ngx-pickydate"
      ]
    }
 }
```

**Comment by AhmedBHameed** [comment] 2018-05-30 20:17
@alan-agius4 So now my `tsconfig.json` is something like this

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "paths": {
      "ngx-pickydate": [
        "dist/ngx-pickydate"
      ]
    },
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "genDir": "compiled",
    "fullTemplateTypeCheck": true,
    "preserveWhitespaces": true
  }
}
```
I can't find *.ngfactory.js file !
Still i get the same error with `ng serve --aot`

**Comment by alan-agius4** [comment] 2018-05-30 20:19
Have you build the library? Does dist/ngx-pickydate exist?

**Comment by alan-agius4** [comment] 2018-05-30 20:29
I can see that the path is incorrect as you don’t have a dist folder.

It should be pointing to the actual distributable path. ‘app/ngx-pixkydate/@ngx-pickydate’

**Comment by AhmedBHameed** [comment] 2018-05-30 20:35
Yes sure this is the link of the [module](https://github.com/AhmedBHameed/ngx-pickydate)
I'm actually new for producing angular modules, I'm wondering what path will do if it is exists in my main `tsconfig.json`?
I don't expect that consumer will add it manually after installing module. right ?

**Comment by alan-agius4** [comment] 2018-05-30 20:37
That is correct, consumers don’t need to  add it when they install the package.

To get you started quickly, I suggest you use Angular CLI

**Comment by AhmedBHameed** [comment] 2018-05-30 20:41
This is for angular 6 i guess!
I tried to bundle it using rollup task bundler but i stuck somewhere that i could not find much info.
Do you have links to start reading more about ?
BTW thank you for helping me and for your time.

**Comment by alan-agius4** [comment] 2018-05-30 20:47
No problem, I don’t particular have any links. I suggest maybe to that a look at medium.com

**Comment by aburht** [comment] 2018-07-26 19:40
@AhmedBHameed  Did you find a solution for this?

**Comment by AhmedBHameed** [comment] 2018-07-26 21:46
@aburht Well after huge searching about it i decided to go with `rollup.js` to bundle my module. and as you see that this issue still open !!
Hope someone will find a solution for it.
However if you need help with `rollup.js` feel free contacting me. happy to help you.

**Comment by alan-agius4** [comment] 2018-09-29 06:39
Closing as this seems to be a config related issue and without a reproduction it’s not really possible to tackle.

My 2 cents would be that the name of the library in that package.json doesn’t match the one in the tsconfig paths.

If the problem persists please open a new issue, with a minimal reproduction.

**Closed by alan-agius4** 2018-09-29 06:39 UTC

**Comment by LazeBear** [comment] 2018-10-05 05:10
I've got the same problem but my case might be a bit different.
I packaged my library into the dist folder, so the folder structure looks like the following

my-lib: 
+dist
--->actual lib
+src
+assets
+other source code

so this gave me that module not found error when I install the library from the root level and import it as 'import {my-lib-module} from 'my-lib/dist'

after I move everything inside the dist folder (not include dist) to a new repo and install from that repo, problem solved.

Hope it helps
