### ISSUE TITLE
maximum call stack size exceeded (index.ts)

### ISSUE THREAD

**Issue by ssameh** [ng-packagr/ng-packagr#1093] opened 2018-09-20 04:24 UTC
Hi

I will try to describe the issue as far as I can (Note I managed to solve the issue so I am just reporting it)

I was applying a migration from Angular 5 to Angular 6, I started getting errors when I attempt to package my code, so I thought perhaps I need as well to upgrade my packager node. I moved to  ng-packagr version 4.2.0

My app was building and running with no issue but when I attempted to package it , I instantly got the error _maximum call stack size exceeded_

I followed divide and conquer approach started by packaging component by component until I manged to isolate the error in one component that is triggering such exception  

I reviewed all my code but I couldn't see any issue plus it was packaging fine before with no issues, I reviewed my component code against others but I couldn't see any difference until I noticed one difference 

My component was actually saved in a ts file sharing the same name of its parent folder, once I changed the file name the error was resolved (folder name became different from file name)  

My app folder structure is simple a parent folder and beneath it the ts files (component.t s+ module.ts + index.ts)  

Sameh 

![capture](https://user-images.githubusercontent.com/4237266/45796067-c2790100-bc6c-11e8-8773-081dae66b19d.PNG)

{
  "name": "ng-App",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "concurrently \"nodemon server/index.js\" \"ng serve --proxy-config proxy.conf.json\"",
    "build": "ng build",
    "test": "ng test --singleRun --code-coverage",
    "watch:test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "package": "ng-packagr -p ng-package.json",
    "postpackage": "cd dist && npm pack",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.doc.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.1.7",
    "@angular/cdk": "6.4.7",
    "@angular/common": "6.1.7",
    "@angular/compiler": "6.1.7",
    "@angular/core": "6.1.7",
    "@angular/forms": "6.1.7",
    "@angular/http": "6.1.7",
    "@angular/material": "6.4.7",
    "@angular/platform-browser": "6.1.7",
    "@angular/platform-browser-dynamic": "6.1.7",
    "@angular/router": "6.1.7",
    "@ng-bootstrap/ng-bootstrap": "1.0.0",
    "ag-grid": "18.1.2",
    "ag-grid-angular": "18.1.0",
    "bootstrap": "3.3.7",
    "chart.js": "2.7.1",
    "concurrently": "3.5.1",
    "core-js": "2.5.3",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "material-design-icons": "3.0.1",
    "ng-packagr": "4.2.0",
    "primeicons": "^1.0.0-beta.10",
    "primeng": "6.1.4",
    "reselect": "3.0.1",
    "rxjs": "6.3.2",
    "tachyons": "4.9.1",
    "tachyons-flexbox": "2.1.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "^6.2.2",
    "@angular/compiler-cli": "6.1.7",
    "@angular/language-service": "6.1.7",
    "@compodoc/compodoc": "1.0.6",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "6.0.100",
    "ajv": "6.1.1",
    "casual": "1.5.19",
    "codelyzer": "4.1.0",
    "express": "4.16.2",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.1",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "ts-node": "3.2.2",
    "tslint": "5.7.0",
    "typescript": "2.9.2"
  }
}

**Comment by marcusklein** [comment] 2018-09-25 03:15
Thanks, same happened to me. Fixing the file name worked :+1:

**Comment by dherges** [comment] 2018-09-25 11:43
Hi,

thanks for reporting. Can you reproduce the error by running just `ngc`? If yes, could you open a bug on the Angular issue tracker?

**Comment by DanielKalmann** [comment] 2018-10-06 09:13
I have this issue too. It started occurring when upgrading from v2.4.2 to 4.2. 

I simply can not rename all my files and/or folders, so help is wanted.

**Comment by DanielKalmann** [comment] 2018-10-06 12:38
I was able to fix it:

When using a file (model mostly) inside a folder with the same name, the maximum call stack error would trigger. By using an index.ts file which exports all the files and specifically pointing to this index instead of the folder, the build succeeds.

Example:

src\
 | -- lib   
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | -- something 
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | -- something.ts  
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | -- index.ts
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | -- somethingelse 
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | -- somethingelse.ts  
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | -- index.ts

 
something/index.ts
````javascript
export * from './something';
`````

public_api.ts (old):
````javascript
export * from './lib/something';
````

public_api.ts (new):
````javascript
export * from './lib/something/index';
````

For every other import which imported a model with the same name as the folder from an index directly to the folder, you need to specifically call the filename of the model.

somethingelse.ts (old):
````javascript
import { Something } from './../something';
````

somethingelse.ts (new):
````javascript
import { Something } from './../something/something';
````

**Comment by florian-kittel** [comment] 2019-06-19 11:57
We have the issue as well. But it is not so easy to fix, because we have hundreds of files and can't figure out which files have this problem at import. Is there a way to find out when the packagr gets crashed?

**Comment by StevenSwitten** [comment] 2019-08-29 08:35
Any update on this?

**Comment by alastair-todd** [comment] 2019-11-02 06:03
I concur it does appear to be a models directory with an index.ts only containing models and then importing it in shorthand as @DanielKalmann states.

FWIW I updated to nodejs v12 which had no effect.

**Comment by RudiVuuren** [comment] 2019-11-05 10:08
I have experienced this issue due to the use of .replace(regExp, () => string).

In my case removing the .replace solved my issue.

**Comment by RudiVuuren** [comment] 2019-11-05 10:20
Try installing `npm i -D node-sass` when using `"ng-packagr": "^5.4.0"`

**Comment by snebjorn** [comment] 2020-03-15 17:27
No idea why but this function was causing
> Maximum call stack size exceeded

when building (ng-packagr@9.0.3) with Ivy turned off. No problems when it was on.

```ts
export function guid() {
  return 'xxxxxx4xyx'.replace(/[xy]/g, c => {
    const r = (Math.random() * 16) | 0,
      v = c == 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}
```

**Comment by t3o-it** [comment] 2020-04-07 12:12
Thanks @snebjorn, I was using the same approach for generating GUIDs.

**Comment by splincode** [comment] 2020-04-26 18:03
@alan-agius4 when export this function from public_api.ts we have `maximum call stack size exceeded`

```ts
export function uuidv4(): string {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c: string): string {
        const r: number = (Math.random() * 16) | 0;
        const v: number = c === 'x' ? r : (r & 0x3) | 0x8;
        return v.toString(16);
    });
}
```

**Comment by alan-agius4** [comment] 2020-04-26 18:30
Seems like an `@angular/compiler-cli` issue, which most likely it will be solved by Ivy.

**Comment by Splaktar** [comment] 2020-05-23 06:53
I ran into this today in `ng-packagr@9.1.5` and `@angular-devkit/build-ng-packagr@0.901.7`. For me the fix was just to specifically import the index file.

### Broken

```ts
export * from './button-bar';
```

### Fixed

```ts
export * from './button-bar/index';
```

In my case, this file is `lib/public-api.ts`.

**Comment by rlexa** [comment] 2020-07-27 12:45
Had this problem with ng9, for me it helped to transform the exported functions to be arrow functions instead.

**Comment by negue** [comment] 2020-11-16 19:22
> Had this problem with ng9, for me it helped to transform the exported functions to be arrow functions instead.

@rlexa thank you, that helped 👍

**Comment by Adrian1907** [comment] 2021-04-27 14:22
In my case helped only turning `fullTemplateTypeCheck` in `false` in the `tsconfig.lib.json` file

**Comment by alan-agius4** [comment] 2021-07-10 22:11
Closing since view engine is deprecated

**Closed by alan-agius4** 2021-07-10 22:11 UTC
Labels: bug, roadmap (high)
