### ISSUE TITLE
Support for build size budgets

### ISSUE THREAD

**Issue by tylermumford** [ng-packagr/ng-packagr#1538] opened 2020-02-11 21:34 UTC
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I'm creating an Angular library in a workspace, and I'd like to set a size budget for the library, as described in [the Angular docs on budgets](https://angular.io/guide/build#configure-size-budgets). It looks like this feature is only available for applications, and not for `"projectType": "library"`.

#### Expected Behaviour

It would be nice if this feature used the same logic and messages that are in the default application builder. There seems to be some context in [this file](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/browser/index.ts), but I haven't investigated further.

#### Version Information

```
PS > node_modules/.bin/ng-packagr --version
ng-packagr:            5.7.1
@angular/compiler:     8.2.14
rollup:                1.25.2
tsickle:               0.37.1
typescript:            3.5.3
```

**Comment by alan-agius4** [comment] 2020-03-22 19:17
Pretty much this is a duplicate of https://github.com/ng-packagr/ng-packagr/issues/1249

**Closed by alan-agius4** 2020-03-22 19:17 UTC
