### ISSUE TITLE
build --prod RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by staneee** [ng-packagr/ng-packagr#2076] opened 2021-09-22 07:41 UTC
## Type of Issue

```
[*] Bug Report
[ ] Feature Request
```

## Description

I have a `@aaa/lib-a` that can be published to gitLab's NPM library and imported for use in other projects. 
When I create a second library `@bbb/lib-b` and introduce modules from `@aaa/lib-a`, compilation problems arise:

```text
[error] RangeError: Maximum call stack size exceeded
    at resolveModuleNamesReusingOldState (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:105667:24)
    at processImportedModules (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:107154:35)
    at findSourceFileWorker (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:106926:17)
    at findSourceFile (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:106788:26)
    at processImportedModules (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:107190:25)
    at findSourceFileWorker (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:106926:17)
    at findSourceFile (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:106788:26)
    at processImportedModules (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:107190:25)
    at findSourceFileWorker (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:106926:17)
    at findSourceFile (D:\dev\@bbb\lib-b\node_modules\typescript\lib\typescript.js:106788:26)

```

> The `@aaa/lib-a` and `@bbb/lib-b` tsconfig configurations are basically the same

If the `tsconfig.lib.prod.json` configuration item `enableIvy` is changed to `true`, it will compile normally, but cannot be published to NPM:
```json
{
  "extends": "./tsconfig.lib.json",
  "compilerOptions": {
    "declarationMap": false
  },
  "angularCompilerOptions": {
    "enableIvy": true
  }
}

```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            11.2.4
@angular/compiler:     11.2.14
rollup:                2.38.4
typescript:            4.1.6
rxjs: ~6.5.4
node: v14.17.5
npm: 6.14.14
```

**Comment by alan-agius4** [comment] 2021-09-22 11:53
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/2045

**Comment by alan-agius4** [comment] 2021-09-22 11:55
Actuality, I was wrong and is not a duplicate. Try to update to latest version of Angular and ng-packagr. If the problem persists please provide a minimal reproduction.

**Comment by staneee** [comment] 2021-09-22 14:52
> Actuality, I was wrong and is not a duplicate. Try to update to latest version of Angular and ng-packagr. If the problem persists please provide a minimal reproduction.

There is a time difference between us. I will reply after trying during working hours, tks。

**Comment by staneee** [comment] 2021-09-23 09:14
This is my repository: ([link](https://github.com/staneee/ng-packge-demos))

`master` branch is `angular 11`, `angular 12` is in `ng-12` branch, in NG-12,.

I think it is important to set `compilationMode` in `tsconfig.lib.prod.json` to `partial` like this:
```json
{
  "extends": "./tsconfig.lib.json",
  "compilerOptions": {
    "declarationMap": false
  },
  "angularCompilerOptions": {
    "compilationMode": "partial"
  }
}

```

**Comment by alan-agius4** [comment] 2021-11-14 06:58
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.

**Closed by alan-agius4** 2021-11-14 06:58 UTC
Labels: needs investigation
