### ISSUE TITLE
Angular 13: Getting Uncaught SyntaxError: Unexpected token 'export' when I run the app

### ISSUE THREAD

**Issue by deepak-prabhu** [ng-packagr/ng-packagr#2299] opened 2022-04-07 11:53 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

I have updated the Angular from 12 to 13. When I run the app I am getting the error **"Uncaught SyntaxError: Unexpected token 'export"**. Adding below few details to get the context.

Earlier in **angular.json** config, I had below dependent entries in **scripts** section.

"**scripts**": [
"./node_modules/@angular/core/bundles/core.umd.min.js",
"./node_modules/@angular/common/bundles/common.umd.min.js",
]

After the angular update to 13, I noticed that in place of umd JS files we have .mjs file (Modular JS files) "./node_modules/@angular/core/esm2020/core.mjs". So I have added **.mjs** file location inside scripts section of angular json configuration

When I run the app I'm getting the error from **scripts.js** and it's pointing to the line "export * from './index';" (this line is from core.mjs file)

Please let me know how to fix this issue?

I tried adding the type "module" in main package.json. But still getting the same issue.

**Note:** 
If I execute the above script manually eg: node --es-module-specifier-resolution=node ./node_modules/@angular/core/esm2020/core.mjs it works fine

#### How To Reproduce

1. Take any Angular 13 app and add below entries like "./node_modules/@angular/core/esm2020/core.mjs" in scripts section of Angular.json configuration file
3. Build and run the app
4. In browser console, you will see the error  **Uncaught SyntaxError: Unexpected token 'export'**

#### Expected Behaviour

1. App should run without any JS errors
2. Should be able to identify the export keyword 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^13.3.0
@angular/compiler: ~13.3.0 
typescript: ~4.6.2
rxjs: ^6.6.7
node: 12.20.2/14.15.5/16.10.0 (Tried with all these Node versions)
npm: 6.14.11
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by SchnWalter** [comment] 2022-04-07 15:16
UMD modules have been removed from Angular v13, see:

* https://github.com/angular/angular/commit/49b82ae56112c1e0d58ac28bcab1705e1f678ab1
* https://github.com/ng-packagr/ng-packagr/pull/2050

**Comment by deepak-prabhu** [comment] 2022-04-07 15:21
Thank you for the reply.

Yes, in place of UMD files now we have .mjs files under each angular core node modules folder. I have included those in place of UMD files in scripts section of angular.json file.

Build is working fine.

However when I run the app, I'm getting the above mentioned error from "/scripts.js" (internally its pointing to export keyword). How do we solve this using .mjs files as I need those files to be included in scripts section due to dependency.

**Comment by deepak-prabhu** [comment] 2022-04-07 15:34
Basically how do we make /scripts.js as ECMA module(.mjs) as it contains "export" keywords from angular core scripts that are included in angular.json scripts section

**Comment by SchnWalter** [comment] 2022-04-07 18:22
As I said before, the UMD builds from both Angular and APF, you can no longer use them.

Besides that, you don't have an issue with `ng-packagr`, this project is a build tool for libraries and the `angular.json` configuration for its builder doesn't have a `scripts` section. You are either using the application builder, in which case you clearly have an invalid setup, because those files should never be in the scripts section, or you are using a 3rd party builder, in which case you should close this unrelated issue. If I got this wrong, then please respect the [contributing guidelens](https://github.com/ng-packagr/ng-packagr/blob/master/CONTRIBUTING.md) and provide a minimal reproduction of the issue.

**Comment by alan-agius4** [comment] 2022-04-13 07:26
This is expected as the ESM modules are not a 1 to 1 replacement for UMDs and cannot be used in the `scripts` configuration. 

In general the Angular framework in not intended to be used as a global script as this will cause opt-out of a number of optimisations to reduce bundle size.

If for one reason or another you do still need to use UMD bundles which is discouraged, you'd need to do the transformations yourself.

**Closed by alan-agius4** 2022-04-13 07:26 UTC
