### ISSUE TITLE
Regression in 11.1.2: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by splincode** [ng-packagr/ng-packagr#1843] opened 2021-01-21 07:21 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

After upgrade to `ng-packagr | 11.0.3 -> 11.1.2` I have problem with build

https://github.com/Angular-RU/angular-ru-sdk/pull/361/checks?check_run_id=1736875741

```
@angular-ru/common: $ ng build library && cp README.md dist/library
@angular-ru/common: Building Angular Package
@angular-ru/common: ******************************************************************************
@angular-ru/common: It is not recommended to publish Ivy libraries to NPM repositories.
@angular-ru/common: Read more here: https://v9.angular.io/guide/ivy#maintaining-library-compatibility
@angular-ru/common: ******************************************************************************
@angular-ru/common: ------------------------------------------------------------------------------
@angular-ru/common: Building entry point '@angular-ru/common'
@angular-ru/common: ------------------------------------------------------------------------------
@angular-ru/common: - Compiling TypeScript sources through NGC
@angular-ru/common: Error: ENOENT: no such file or directory, open '/home/runner/work/angular-ru-sdk/angular-ru-sdk/packages/common/src/**/*.ts'
@angular-ru/common:     at Object.openSync (fs.js:476:3)
@angular-ru/common:     at Object.readFileSync (fs.js:377:35)
@angular-ru/common:     at NodeJSFileSystem.NodeJSReadonlyFileSystem.readFile (/home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/src/ngtsc/file_system/src/node_js_file_system.js:98:23)
@angular-ru/common:     at EsmDependencyHost.DependencyHostBase.recursivelyCollectDependencies (/home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_host.js:81:40)
@angular-ru/common:     at EsmDependencyHost.DependencyHostBase.processFile (/home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_host.js:136:22)
@angular-ru/common:     at EsmDependencyHost.DependencyHostBase.collectDependenciesInFiles (/home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/ngcc/src/dependencies/dependency_host.js:56:26)
@angular-ru/common:     at ProgramBasedEntryPointFinder.getInitialEntryPointPaths (/home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/program_based_entry_point_finder.js:49:18)
@angular-ru/common:     at ProgramBasedEntryPointFinder.TracingEntryPointFinder.findEntryPoints (/home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/tracing_entry_point_finder.js:45:41)
@angular-ru/common:     at /home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:28:41
@angular-ru/common:     at SingleProcessExecutorAsync.SingleProcessorExecutorBase.doExecute (/home/runner/work/angular-ru-sdk/angular-ru-sdk/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:28:29)
@angular-ru/common: ✖ Compiling TypeScript sources through NGC
@angular-ru/common: ERROR: NGCC failed.
@angular-ru/common: An unhandled exception occurred: NGCC failed.
@angular-ru/common: See "/tmp/ng-pAyPtN/angular-errors.log" for further details.
@angular-ru/common: error Command failed with exit code 127.
@angular-ru/common: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:lib exited 127 in '@angular-ru/common'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 127.
```

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

1. Git clone https://github.com/Angular-RU/angular-ru-sdk/
2. Install ng-packagr 11.1.2
3. run `yarn build:lib`

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

Working without regression

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 11.1.2
@angular/*: last
typescript: last
rxjs: last
node: last
yarn: 1.2
```

**Comment by JoostK** [comment] 2021-01-21 08:24
I guess this is an issue related to path mappings. I'll have a look at your repro.

**Comment by alan-agius4** [comment] 2021-01-21 09:10
The problem appears to be that `files` contains a glob https://github.com/Angular-RU/angular-ru-sdk/blob/7582e79ed70311854ea51bdec5f1f3771b9340d7/packages/common/tsconfig.lib.json#L17 but this is invalid, see: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#examples

I think in this case, NGCC should really throw a more actionable error.

**Comment by JoostK** [comment] 2021-01-21 09:15
@alan-agius4  thanks, great find. That does indeed look like the cause here.

**Comment by splincode** [comment] 2021-01-21 09:50
@alan-agius4 How can I fixed my issue?)

**Comment by alan-agius4** [comment] 2021-01-21 10:10
@splincode, yeah.

**Comment by alan-agius4** [comment] 2021-01-21 11:00
Closing as this is really not actionable from ng-packagr.

**Closed by alan-agius4** 2021-01-21 11:00 UTC
