### ISSUE TITLE
How to disable auto generate dist.tgz file?

### ISSUE THREAD

**Issue by AndrewLang** [ng-packagr/ng-packagr#737] opened 2018-03-29 17:41 UTC
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

I build my project to dist folder, after build I found there is a file named "dist.tgz" is generated, is there an option to disable it?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
"@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "core-js": "^2.5.4",
    "rxjs": "^5.5.8",
    "zone.js": "^0.8.20",
    "@angular/cli": "1.7.3",
    "@angular/compiler-cli": "^5.2.9",
    "@types/jasmine": "2.8.6",
    "@types/node": "~9.6.1",
    "@types/gulp": "^4.0.5",
    "ng-packagr": "2.4.1",
    "gulp": "3.9.1",
    "gulp-rimraf": "0.2.2",
    "gulp-bump": "^3.1.0",
    "run-sequence": "^2.2.1",
    "rimraf": "^2.6.2",
    "shelljs": "0.8.1",
    "chalk": "2.3.2",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.7.0",
    "jasmine-spec-reporter": "~4.1.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.8.1"
```

**Comment by daimoonis** [comment] 2018-04-05 08:05
Hello, i think that packager should not create tgz file by default as it does now. Possibly it may be configurable, but anyway, anyone can pack generated code by himself right, so what is the reason for this? I'm using version 2.2.0 because it was not implemented there yet.

**Comment by kylecordes** [comment] 2018-04-05 14:33
Dup #728 ?

**Comment by alan-agius4** [comment] 2020-11-12 10:37
Duplicate of #728

**Closed by alan-agius4** 2020-11-12 10:37 UTC
