### ISSUE TITLE
Maximum Stack Size Error - file / folder naming problem

### ISSUE THREAD

**Issue by SebastianLindner** [ng-packagr/ng-packagr#1613] opened 2020-04-29 12:40 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

While trying to create a package I am getting the following error.

Compiling TypeScript sources through ngc
ERROR: Maximum call stack size exceeded
npm ERR! code ELIFECYCLE
npm ERR! errno 111

It seems the packaging process is getting into some kind of endless loop.

#### How To Reproduce

It seems you cannot have the same name for a folder and file in it if you also reference it by e.g. an index file.

E.g.
- my-component
-- index.ts
-- my-component.ts

index.ts:
export * from './my-component';

If you now reference the index.ts e.g. from the entry point of packaging I get the above described error.

#### Expected Behaviour

There should be no error during packaging.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.1
@angular/*: 8.2.14
typescript: 3.5.3
rollup: 2.6.1
rxjs: 6.4.0
node: 12.16.3
```

**Comment by Splaktar** [comment] 2020-05-23 06:46
I'm seeing this as well, but this issue seems to be a duplicate of https://github.com/ng-packagr/ng-packagr/issues/1093.

**Comment by alan-agius4** [comment] 2020-08-09 20:34
Duplicate of #1093

**Closed by alan-agius4** 2020-08-09 20:34 UTC
