### ISSUE TITLE
fullTemplateTypeCheck: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by dherges** [ng-packagr/ng-packagr#1087] opened 2018-09-18 12:29 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

angular/angular#19906

angular/angular#24143

#### How To Reproduce

Issue happens when `fullTemplateTypeCheck` is enabled.

https://angular.io/guide/aot-compiler#fulltemplatetypecheck

```
Error: TypeError: Cannot read property 'type' of null
    at C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:26
    at Array.forEach (native)
    at removeSummaryDuplicates (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:25384:11)
    at TemplateParser.tryParseHtml (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24393:51)
    at TemplateParser.tryParse (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24370:21)
    at TemplateParser.parse (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24332:44)
    at AotCompiler._parseTemplate (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29710:60)
    at AotCompiler._compileComponent (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29682:23)
    at C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29528:55
    at Array.forEach (native)
```

The issue can be work-around'ed by setting `fullTemplateTypeCheck: false`

#### Expected Behaviour

Something, just anything better :-)

An error message ... indicating where the problem in the code base.

#### Version Information

```
Angular CLI: 6.2.2
Node: 10.10.0
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.8.2
@angular-devkit/schematics        0.8.2
@angular/cdk                      6.4.7
@angular/cli                      6.2.2
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.8.2
ng-packagr                        4.1.1
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.8.3
```

**Comment by dherges** [comment] 2018-09-18 12:36
We need a repro btw 🗡 😢

**Comment by dherges** [comment] 2018-09-24 15:13
I found one case where `isSkipSelf of null` relates to `fullTemplateTypeCheck`. Die to the error message I don't know what piece of code causes the error. The error is supressed with `fullTemplateTypeCheck: false`

https://github.com/angular/angular/issues/20523

**Comment by rdhelms** [comment] 2018-10-09 19:19
Just wanted to add that I got this same error with the angular 7.0.0-rc versions, but setting `fullTemplateTypeCheck: false` still suppressed the error exactly like @dherges said. But still no real info on the core issue.

**Version Information**
```
Angular CLI: 7.0.0-rc.2
Node: 8.11.3
OS: linux x64
Angular: 7.0.0-rc.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.9.0-rc.2
@angular-devkit/build-angular     0.9.0-rc.2
@angular-devkit/build-optimizer   0.9.0-rc.2
@angular-devkit/core              7.0.0-rc.2
@angular-devkit/schematics        7.0.0-rc.2
@angular/cdk                      7.0.0-rc.1
@angular/cli                      7.0.0-rc.2
@ngtools/json-schema              1.1.0
@ngtools/webpack                  7.0.0-rc.2
@schematics/angular               7.0.0-rc.2
@schematics/update                0.9.0-rc.2
ng-packagr                        4.2.0
rxjs                              6.3.3
typescript                        3.1.1
webpack                           4.19.1
```

**Comment by rdhelms** [comment] 2018-10-22 18:54
Seems to still be around with ng-packagr@4.4.0

**Comment by pfeigl** [comment] 2019-02-05 18:00
We are running into the same problem. Setup similar to what others reported: Two libraries, where one depends on the other. 

I debugged into the angular compiler today a little and what actually fails is the following:
* The compiler refers to Pipes which he identified in the "dist" folder
* However the metadata resolver does not load those files
* Therefor there are nullreferences later on in the pipeline, because the duplicateRemover tries to work on null objects, because the pipe metadata was not loaded

To be honest, I'm not sure what the real problem now is and who has to fix it. But it feels like the compiler should never know about the contents of my dist folder.

**Comment by dherges** [comment] 2019-02-13 06:55
https://github.com/angular/angular/issues/24143#issuecomment-462984828

> Angular Ivy completely removes `.metadata.json` (and greatly simplifies path handling in the compiler in general), so this problem should be fixed completely with the Ivy compiler.

Hej @pfeigl, thanks for digging into this and sharing the info. I don't have any plans yet, I keep it on the Angular 8 roadmap.

**Comment by nelisbijl** [comment] 2019-03-08 09:53
I got this error when adding a directive to the exports section of a module.
Removing it resolved it.
Note: different combination of nodeJS en ng-cli also resolved the problem.
Not sure if this helps anyone. No time to research what's happening and why.

**Comment by kmursk** [comment] 2020-03-11 12:13
Folder _node_modules_ added to project through **symlink** invokes compiler's failure _Cannot read property 'type' of null_ with angular/cli 8.2, 8.3 and 9.0.5 and compatible versions of typescript respectively. This error can be suppressed by compiler option _"fullTemplateTypeCheck": false_, but further there would be other unclear errors. Some of them can be fixed by other compiler options. but eventually you would be forced to enable _fullTemplateTypeCheck_ again if your project depends on external non-angular libraries. All said is true if option _enableIvy_ is false.

**Comment by braydonharris** [comment] 2020-03-24 16:28
Can confirm with angular 9 getting the same error. I have a library that is wrapping around angular material components, Ivy is enabled in my library as well as my project that is consuming my library

Adding the fullTemplateCheck in the tsconfig.lib.json does suppress the error and allows my app to work again.
`"angularCompilerOptions": {
		"annotateForClosureCompiler": true,
		"skipTemplateCodegen": true,
		"strictMetadataEmit": false,
		"fullTemplateTypeCheck": false,
		"strictInjectionParameters": true,
		"enableResourceInlining": true
},`

Here's my package.json
`"dependencies": {
    "@angular/animations": "^9.0.7",
    "@angular/cdk": "^9.1.3",
    "@angular/common": "^9.0.7",
    "@angular/compiler": "^9.0.7",
    "@angular/core": "^9.0.7",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.0.7",
    "@angular/material": "^9.1.3",
    "@angular/platform-browser": "^9.0.7",
    "@angular/platform-browser-dynamic": "^9.0.7",
    "@angular/router": "^9.0.7",
    "core-js": "^3.2.1",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.5.2",
    "tslib": "^1.11.1",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.900.7",
    "@angular-devkit/build-ng-packagr": "~0.900.7",
    "@angular/cli": "^9.0.7",
    "@angular/compiler-cli": "^9.0.7",
    "@angular/language-service": "^9.0.7",
    "@types/jasmine": "~3.5.9",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "ng-packagr": "^9.0.3",
    "node-sass": "^4.13.1",
    "protractor": "~5.4.3",
    "scss-bundle": "3.1.1",
    "tsickle": "^0.38.1",
    "tslint": "~6.1.0",
    "typescript": "~3.7.5"
  }`

Another item to note is that I can't seem to produce it locally on my machine only when I deploy the code to my server

Any help in figuring out why this error is happening would be greatly appreciated!

**Comment by dima-gusyatiner** [comment] 2020-03-25 18:13
For me, currently, it's either `"fullTemplateTypeCheck": false` and then the error is:
````
Error during template compile of 'DemoRoutingModule'
Function calls are not supported in decorators but 'RouterModule' was called
````

Or, if i set `fullTemplateTypeCheck` to `true`, I get the very loved and detailed error:
````
ERROR: Cannot read property 'type' of null
````

This is a very annoying error! Please provide more info into the error, what exactly didn't the compiler like?

**Comment by kmursk** [comment] 2020-03-28 03:45
Message "_Function calls are not supported in decorators..._" means that compiler doesn't like snippet
_@NgModule({
  imports: [RouterModule.forRoot(...._
Here is the _function call_.  It seems there is no way to rewrite source code in another way, hence you should change the next compiler's option.
  _"angularCompilerOptions": {
    "skipTemplateCodegen": false,_
It can fix the error about _function call_. But as it had been said at previous comment, most likely you will have other unsolvable troubles. Thus the better way is to leave _"fullTemplateTypeCheck": true_.

**Comment by braydonharris** [comment] 2020-04-03 18:05
Can confirm from what @kmursk suggested keeping the "fullTemplateTypeCheck": true and adding the skipTemplateCodegen: false also resolves the issue however possibly updating to angular 9.1 may have also fixed my issue I'll need to test more to confirm that.

**Comment by LPCmedia** [comment] 2020-04-26 21:52
I am importing a module from another library with pipes and I can reproduce this issue. 
using 9.1.3 

fullTemplateTypeCheck: true -> Cannot read property 'type' of null 
umd compilation tries to remove duplicates via type for pipes and the exported ones are all null. 

fullTemplateTypeCheck: false -> ERROR: Illegal state: Could not load the summary for pipe 'NAME'
thrown on the first pipe that is exported by the module.
compiler cli formatDiagnostics seems to be the source of the thrown error.

**Comment by LarsVonQualen** [comment] 2020-05-27 10:27
I can confirm issues regarding symlinks.
I'm running the latest Windows 10 Pro, Windows Terminal 1.0.1401.0 with the latest Powershell 7.0.1 and ng-packagr 5.7.1.

I use a symlink to C:\development in another folder, which triggers this error. If i go directly into C:\development, and retries, with no other changes, it works fine.

**Comment by Romanchuk** [comment] 2020-07-17 07:06
Issue appeared when i changed **npm** to **pnpm** since pnpm uses symlinks in node_modules

Angular 10
ng-packagr 10

**Comment by Clashsoft** [comment] 2020-09-05 12:29
Using `pnpm` and Angular 9, I'm having the same problem.

**Comment by literalpie** [comment] 2021-03-13 19:01
I did some digging, and I think the cause of the error is in the Angular Compiler (ngc), specifically [`removeSummaryDuplicates`](https://github.com/angular/angular/blob/1f956184c426814be8fcbdab03396c910e29d935/packages/compiler/src/template_parser/template_parser.ts#L921).

But the root issue is even deeper than that. I believe the problem has something to do with the `StaticSymbolCache` being inconsistent in how it sets the `filePath` of a symbol. When using PNPM, the cache contained two entries for `NgClass` (and many other symbols). One entry at the "actual" path ("node_modules/.pnpm/@angular/...") and one entry at the hard-linked path ("node_modules/@angular/..."). Strangely, this doesn't seem to be a problem when using `npm link`, even though that also uses symbolic links.

I really hope that the Angular team reconsiders fixing issues related to pnpm, especially since this issue _has nothing to do with ngcc_, which is their justification for not fixing this in the past (as far as I can tell, this won't work any better when using Angular Linker).

I was really hoping that at the end of my digging I would be able to find a solution, but the compiler simply has too much complexity for me to find the source of this and an appropriate fix. I hope someone else has more success than me!

**Comment by JoostK** [comment] 2021-03-13 19:48
@literalpie The Angular Linker itself does indeed not prevent this problem, but fortunately it allows a library to be compiled with the Ivy compiler instead of ViewEngine. The Ivy compiler no longer uses the `StaticSymbol` abstraction internally, instead it refers to symbols by their TypeScript declaration in `.d.ts` files.

**Comment by literalpie** [comment] 2021-03-13 21:29
Thank you for the tip @JoostK. I just tested this with the "Ivy" project in the integrations folder of ng-packagr, and I do not get the error when using pnpm!

**Comment by Romanchuk** [comment] 2021-04-01 04:51
@literalpie Could you share your setup?

**Comment by literalpie** [comment] 2021-04-01 11:13
@Romanchuk sorry, I'm not sure what you're asking for. I was simply using the nag-packagr repo and I used onion to install dependencies and then built the ivy integration test.

**Comment by gkTim** [comment] 2021-07-09 09:46
Having the same problem. Sadly it seems not to be possible to switch to ivy for the dev build because storybook seems to handle angular npm packages not correctly and can't find templates. Also using pnpm

**Closed** 2021-08-20 13:55 UTC
Labels: bug, roadmap (high)
