### ISSUE TITLE
.metadata.json file not generated 

### ISSUE THREAD

**Issue by pchmn** [ng-packagr/ng-packagr#1540] opened 2020-02-12 12:04 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

With v9.0.0+ of ng-packagr, when I build my library, `.metadata.json` file is not generated in _dist_ folder. 

I tried to set `generateCodeForLibraries` _(When true (the default), generates factory files (.ngfactory.js and .ngstyle.js) for .d.ts files with a corresponding .metadata.json file.)_ angular compiler option to true in my `tsconfig.json` file, but `.metadat.json` is still not generated.

The library can be used in a project, but there are issues with Angular Language Service plugin because of the missing `.metadata.json` file.

#### How To Reproduce

(With @angular/cli@9.0.0+)
```
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib
ng build my-lib
```

#### Expected Behaviour

The `.metadata.json` file is present in _dist_ folder.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            9.0.0
@angular/compiler:     9.0.0
rollup:                1.31.0
tsickle:
typescript:            3.7.5
$ node -v
v13.7.0
$ npm -v
v6.13.6
```

**Comment by JoostK** [comment] 2020-02-12 12:08
Can you try with `ng build my-lib --prod`, as that ought to generate the library using the ViewEngine compiler instead of Ivy (which doesn't produce metadata). Publishing a ViewEngine library is actually important at the moment, as Ivy generated code is not yet stable.

**Comment by pchmn** [comment] 2020-02-12 12:10
Yes if I try `ng build my-lib --prod` it creates the `.metadat.json` file.
Thanks

**Comment by alan-agius4** [comment] 2020-02-12 17:29
Closing as it working as intended.

**Closed by alan-agius4** 2020-02-12 17:29 UTC
