### ISSUE TITLE
[BUG] Unexpected Value using NgModule interdependencies

### ISSUE THREAD

**Issue by jdavidls** [ng-packagr/ng-packagr#1444] opened 2019-11-10 23:24 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

 I receive a Unexpected value 'AnyModule' error when building a library with NgModule dependencies (when one NgModule depends on other NgModule exported from other package/subpackage).

#### How To Reproduce

I have created a repo with the minimal reproduction of the issue, here:  https://github.com/prodisign/bug-reporting . Type `ng build rh` to obtain the error message:

```
------------------------------------------------------------------------------
Building entry point '@prodisign/rh/model/client'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: Unexpected value 'LayoutModule in ../dist/prodisign/rh/client/prodisign-rh-client.d.ts' imported by the module 'ModelModule in ../projects/prodisign/rh/model/client/src/ModelModule.ts'. Please add a @NgModule annotation.

An unhandled exception occurred: Unexpected value 'LayoutModule in ../dist/prodisign/rh/client/prodisign-rh-client.d.ts' imported by the module 'ModelModule in ../projects/prodisign/rh/model/client/src/ModelModule.ts'. Please add a @NgModule annotation.

See "/tmp/ng-1Uj8ei/angular-errors.log" for further details.
```

I am using a complex module disposition, using secondary entrypoints. But other simplest dispositions throwns the same error.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.7.1
@angular/compiler:     8.2.13
rollup:                1.25.2
tsickle:               0.37.1
typescript:            3.5.3
```

**Comment by alan-agius4** [comment] 2019-11-11 07:06
Duplicate of https://github.com/angular/angular/issues/33722

**Closed by alan-agius4** 2019-11-11 07:06 UTC
