### ISSUE TITLE
ERROR: Could not resolve <src_file> upgrading to version 5.5.0

### ISSUE THREAD

**Issue by crowmagnumb** [ng-packagr/ng-packagr#1433] opened 2019-10-28 21:01 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description & How To Reproduce

I tried upgrading ng-packgr to the latest version from 5.4.3 and got the following error.

```
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'core'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
ERROR: Could not resolve './src/module' from dist/core/fesm5/core.js
An unhandled exception occurred: Could not resolve './src/module' from dist/core/fesm5/core.js
See "/tmp/ng-UIo5O5/angular-errors.log" for further details.
```

I was able to create a completely stripped down version of my multiple library project and recreate the problem. Any ng-packagr version greater than or equal to 5.5.0 results in the error, but 5.4.3 does not. Wonder if you could take a quick look at the [repo](https://github.com/animalus/ng-packagr5.5-issue).
To recreate the issue clone this repo and run ...

```
npm i
npm run build
```
Please note the ```npm run build``` command in the package.json file. you can also change the version of ng-packagr to 5.4.3 and rerun the above to verify that it works.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: >=5.5.0
@angular/*: 8.2.12
typescript: 3.5.3
rxjs: 6.5.3
node: 12.7.0
npm: 6.12.0
```

**Comment by jpspringall** [comment] 2019-10-28 21:40
I suspect this is the same issues as: https://github.com/ng-packagr/ng-packagr/issues/1431

**Comment by alan-agius4** [comment] 2019-10-28 22:08
Duplicate of #1431

**Closed by alan-agius4** 2019-10-28 22:08 UTC

**Comment by crowmagnumb** [comment] 2019-10-28 22:10
I would agree, that sounds like the exact same issue. Cheers.
