### ISSUE TITLE
Can't run ts-node inside library project

### ISSUE THREAD

**Issue by fireflysemantics** [ng-packagr/ng-packagr#1648] opened 2020-05-21 03:01 UTC
## Type of Issue

```
[X ] Bug Report
```

## Description

https://stackoverflow.com/questions/61926214/syntaxerror-unexpected-token-when-running-ts-node-in-angular-package-format-p

**Comment by alan-agius4** [comment] 2020-05-26 09:06
Duplicate of https://github.com/angular/angular-cli/issues/17788

**Closed by alan-agius4** 2020-05-26 09:06 UTC
