### ISSUE TITLE
Ng-packagr stopped bundling Type Definitions

### ISSUE THREAD

**Issue by ekm1** [ng-packagr/ng-packagr#1904] opened 2021-03-03 14:46 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description
After ng-packagr version 10.0.0 custom typings are not included in the bundle generated. The behavior was discovered using version 11.2.4

#### How To Reproduce

Create a library and inside a example.component.ts file or public-api.ts on the top reference your Type Definitions
`/// <reference path="./test.d.ts" />`

then try to build the package
`npm run build`

I found a repo and reproduced the issue can be accessed here: https://github.com/ekm1/replicate-issue 

#### Expected Behaviour

Expected behavior at least prior to ng-packagr 10.0.0 was that during build TypeDefinitions are also included into the bundle,
I am not sure if the behavior was meant to change, but looking at the Changelog i couldn't find anything mentioning it.

Also referencing into the typeRoots the types did not fix anything.

#### Version Information

```
ng-packagr: 10.0.0 and above
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment] 2021-03-04 09:15
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1727

**Closed by alan-agius4** 2021-03-04 09:15 UTC
