### ISSUE TITLE
Unable to update to angular 11

### ISSUE THREAD

**Issue by emmbee7806** [ng-packagr/ng-packagr#1792] opened 2020-11-17 20:26 UTC
## Type of Issue

```
[* ] Bug Report
[ ] Feature Request
```

## Description

On running `ng update @angular/cli` on angular 10 project  i'm getting error ` Package "@angular-devkit/build-ng-packagr" has an incompatible peer dependency to "ng-packagr" (requires "^10.0.0", would install "11.0.2").`

**Comment by alan-agius4** [comment] 2020-11-19 13:47
Duplicate of https://github.com/angular/angular-cli/issues/19384

**Closed by alan-agius4** 2020-11-19 13:47 UTC
