### ISSUE TITLE
TypeScript barrels break build

### ISSUE THREAD

**Issue by andreasonny83** [ng-packagr/ng-packagr#195] opened 2017-10-18 19:11 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When trying to build a library of reusable Angular component, ng-packagr doesn't seem to package the generated distribution version correctly

#### How To Reproduce

`ng-package.json`

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "dest": "package",
  "lib": {
    "entryFile": "src/lib/public_api.ts"
  }
}
```

`src/lib/public_api.ts`

```
export * from './modules/modules-a';
export * from './modules/modules-b';
export * from './modules/modules-c';
```

Then, in each `module` folder I have an `index.ts` to export the specific module:

`src/lib/modules/module-a/index.ts`

```
export * from './component-a.component';
export * from './component-a.module';
```

#### Expected Behaviour

When I generate the library with `ng-packagr -p ng-package.json`, the `ngx-customer-library.metadata.json` contains only this line of code:

```
{"__symbolic":"module","version":3,"exports":[{"from":"./modules/module-3/"}],"metadata":{},"origins":{},"importAs":"my-angular-library"}a
```

However, everything is working fine if inside my `src/lib/public_api.ts` I add an extra `/index`:

```
export * from './modules/modules-a/index';
export * from './modules/modules-b/index';
export * from './modules/modules-c/index';
```

#### Version Information

```
ng-packagr: v1.4.1
node: v8.6.0
@angular: v4.4.5
rxjs: 5.4.3
zone.js: .8.18
@angular/cli: 1.3.2
```

**Comment by dherges** [comment] 2017-10-19 19:12
Yes. There are some issue with [barrels](https://basarat.gitbooks.io/typescript/docs/tips/barrel.html) in the Angular compiler afaik. I don't know how and when exactly the issue occurs. However, I can say that it's better to use the full-path imports (pointing to a `*.ts` file) instead of the barrel imports.

**Comment by andreasonny83** [comment] 2017-10-19 19:53
Yes that has been my way around this problem but I was really hoping to benefits of barrels

**Comment by dherges** [comment] 2017-10-19 19:57
Ok. Changed the title so that it's easier to track. I fear there's nothing we can do about it. I can try to find and post a link to the original issue but it will not be before the next week.

**Comment by dherges** [comment] 2017-10-23 08:22
Here are issues that are related:

- Angular CLI w/ barrels and cyclic dependencies: https://github.com/angular/angular-cli/issues/1831#issuecomment-247895889
- ngc and barrels w/ AoT compilation: https://github.com/angular/angular/issues/13008#issuecomment-293543335
- AoT and barrels: https://github.com/angular/angular/issues/13590

Seeing all this, I think it's best to not use TypeScript barrels!

**Comment by mitsoe** [comment] 2017-11-08 20:38
I was facing a similar issue and fixed it by pointing directly at the index file like so. 

`export * from './modules/modules-a/index';`

**Comment by jeffora** [comment] 2018-03-13 06:11
I have created a minimal reproduction for this issue in a situation we were encountering it here: https://github.com/jeffora/ng-barrel.

Hopefully the README is easy enough to follow, but I'm assuming this isn't actually a bug with ng-packagr, as the issue is the metadata.json is generated incorrectly with missing classes when using barrel files. cc @dherges

**Comment by jeffora** [comment] 2018-03-19 03:10
I've also opened a pull request angular/angular#22856 which fixes the issue in my specific reproduction above, so might cover quite a few of these issues.

**Comment by ashu12318** [comment] 2018-06-13 09:39
Had same issue and changing all the bareels import statement in all the files helped solving this issue.
But this is unconventional.

**Comment by JoostK** [comment] 2018-07-10 18:40
https://github.com/angular/angular/pull/22856 was just merged into patch (6.0) and master (6.1), thanks a lot for your effort @jeffora!

For the record, should library authors re-bundle to create a fixed `metadata.json` file (once updated to the patched angular-cli of course), or is this fix purely on the consumer side?

**Comment by toupeira** [comment] 2018-09-21 11:33
> For the record, should library authors re-bundle to create a fixed metadata.json file (once updated to the patched angular-cli of course), or is this fix purely on the consumer side?

@JoostK looking at the fix it affects the generated metadata, so yes library authors should re-bundle.

Also for the record, this was released in Angular 6.0.8 / 6.1.0 and appending `/index` isn't required anymore.

**Comment by ianchi** [comment] 2018-09-26 22:56
Hi, I'm building with Angular 6.1.8, and I still have this problem.
When my 'public_api.ts' exports pure directories with barrel files, the generated metadata is empty.
When exporting with `folder/index` notation, the metadata is correctly generated.

So for me, appending `/index` is still required.

@toupeira did you have to change any setting to make it work?

**Comment by toupeira** [comment] 2018-10-19 13:47
@ianchi nevermind, I didn't test properly and `/index` is still required :sob:

**Comment by alexrosenfeld10** [comment] 2019-04-17 19:15
I'm having the same issue. The error message is rather ambiguous, adding it here for search ability as it took me a while to find this thread...

```
projects/mymodule/src/lib/reducers/index.ts(6,31): error TS2307: Cannot find module 'src/lib/reducers/myreducer.reducer'.
projects\mymodule\src\lib\mymodule.module.ts(15,39): Error during template compile of 'MyModule'
  Could not resolve src/lib/reducers relative to [object Object]..
```

**Comment by xjose97x** [comment] 2019-06-10 03:53
Any update?

**Comment by Rlcolli4** [comment] 2019-06-24 15:49
A question about this issues, when using barrel's to export my components I can't access any of the items in project I want to use them in. I'm trying to use them in a directive service and am unable to import them into the service for use even though the build works and I can reference the components in HTML. Is this expected with the current bug of barrels?

**Comment by alan-agius4** [comment] 2019-09-04 21:17
Closing as per https://github.com/ng-packagr/ng-packagr/issues/195#issuecomment-338583484

**Closed by alan-agius4** 2019-09-04 21:17 UTC
Labels: wontfix
