### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by leftstick** [ng-packagr/ng-packagr#654] opened 2018-03-02 05:39 UTC
## Type of Issue

```
[ ] Bug Report
```

## Description

While running with `ng-packagr -p package.json`, i got following error

```
Building Angular Package
Building entry point 'angular2-test-lib'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15
'ElementRef' is imported from external module '@angular/core' but never used
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Dropping unreachable code [0:40,0]
Declarations in unreachable code! [0:40,0]
Relocating source maps
Copying staged files
Writing package metadata
Built angular2-test-lib
Built Angular Package!
- from: /Users/admin/codes/github/angular2-test-lib
- to:   /Users/admin/codes/github/angular2-test-lib/dist
(node:2906) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '.ng_pkg_build/angular2-test-lib/out/node_modules/rxjs/operator/retry.d.ts'
(node:2906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2906) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code..
```

Here are my dependencies list:

```
"@angular/cli": "^1.5.0",
"@angular/common": "~5.0.0",
"@angular/compiler": "~5.0.0",
"@angular/compiler-cli": "~5.0.0",
"@angular/core": "~5.0.0",
"@angular/platform-browser": "~5.0.0",
"@angular/platform-browser-dynamic": "~5.0.0",
"@angular/router": "~5.0.0",
"core-js": "^2.5.3",
"ng-packagr": "^2.1.0",
"rxjs": "^5.5.6",
"typescript": "2.6.2",
"zone.js": "^0.8.18"
```

#### How To Reproduce

Nothing special in my package.json, just like your example

#### Expected Behaviour

I hope the libs can be generated without any error

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.1.0
@angular/compiler:     5.0.5
@angular/compiler-cli: 5.0.5
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.4.2
```

**Comment by about-code** [comment] 2018-03-04 19:41
Seems to be a duplicate of #589

**Comment by hughanderson4** [comment] 2019-01-03 16:03
@about-code please re-open this issue.
it is not a duplicate of #589 
this error is specifically about `'ElementRef' is imported from external module '@angular/core' but never used` which is never mentioned on 589.

**Comment by alan-agius4** [comment] 2019-01-03 16:15
@hughanderson4 the issue you are mentioning relates to 
https://github.com/angular/angular/issues/21280

**Comment by about-code** [comment] 2019-01-09 12:49
@leftstick would you mind reopen this issue?  #589 has been edited since my comment above and like @hughanderson4 I can't see ElementRef mentioned there anymore, either.

**Comment by sergiubologa** [comment] 2019-06-14 09:58
Does anyone have a workaround for this issue?

**Comment by alan-agius4** [comment] 2020-11-12 10:45
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. 
If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-11-12 10:45 UTC
