### ISSUE TITLE
Rollup config error on dynamic import during library build

### ISSUE THREAD

**Issue by GeorgeKnap** [ng-packagr/ng-packagr#1285] opened 2019-05-16 12:35 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

This bug relates to building angular library which uses dynamic imports.
Consider building `foo` library with the command `ng build foo`.
When the library contains a file (service in my case), which uses dynamic import, the build will fail throwing error below. 

```
Error: You must set "output.dir" instead of "output.file" when generating multiple chunks.
    at error (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:3410:30)
    at normalizeOutputOptions (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:17107:13)
    at getOutputOptions (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:16865:24)
    at Object.write (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:16957:43)
    at Object. (c:\Development\rollup-test\node_modules\ng-packagr\lib\flatten\rollup.js:46:22)
    at Generator.next ()
    at fulfilled (c:\Development\rollup-test\node_modules\ng-packagr\lib\flatten\rollup.js:4:58)
```

#### How To Reproduce

See details about how to reproduce at this post: 
[https://github.com/angular/angular-cli/issues/14444#issue-444906345](https://github.com/angular/angular-cli/issues/14444#issue-444906345)

**Comment by JensNguyen** [comment] 2019-06-03 08:50
Any updates on this? 
I have the same issue, which makes it sadly not possible to have dynamic imports in my libraries

**Comment by Razgort** [comment] 2019-06-06 15:12
Hello guys,
i think my question is related to this issue, i'm trying to load an external json config file at build time but i can't get it to work ...

**Comment by razims** [comment] 2019-06-28 12:12
I have the similar issue, any updates?

**Comment by CSchulz** [comment] 2019-07-11 10:12
We want to use this feature to define different routing modules in our commons library and encountered the named error.

Would be great to see this feature in the near future, because it makes our Angular app lazy loading finally.

**Comment by kingfolk** [comment] 2019-07-18 01:37
same issue. any updates? thanks

**Comment by raphael22** [comment] 2019-07-18 14:34
Any ETA on this ?

**Comment by alan-agius4** [comment] 2019-07-18 14:48
Can you please provide some context on the use cases you require dynamic imports in a library (Excluding JSON imports)

**Comment by devbean** [comment] 2019-07-19 01:11
Actually, our application is made up with several separate libraries. Although the final application is only one but we are required to compile each library in `prod` mode before submit to source tree to make sure these libraries have no any problem in final application release phase which is executed by scripts automatically. Because of this issue, we couldn't compile each library separately but have to compile the whole application directly. If there is anything wrong, we need to back to libraries to fix then submit then compile again. It'll take 20min to compile the whole application. Now we have to change compile scripts if this issue is not fixed.

BTW because of this issue, the behavior has break change so if this issue will not be fixed, I think the documents should be updated to point this out.

**Comment by CSchulz** [comment] 2019-07-19 07:16
What kind of imports are you using @devbean ?

**Comment by raphael22** [comment] 2019-07-19 08:24
@alan-agius4 
I need to import a button module in a header based on user role / build config, and then load another part of the library on click.
But basically, the dynamic import in a lazy-loaded library is a sweet feature when you deep-dive into code-splitting.

**Comment by devbean** [comment] 2019-07-20 12:54
@CSchulz 
In fact, the final application might not have such problem because our script will copy source code from every library to the final application src directory. What I mean is, because each team hold one library, they will compile their library code in `prod` before submit (such submit behavior triggers script copy action) to make sure their code not fail in `prod` of final release. Each library has lazy load so they couldn't compile it because of this issue. As I mentioned, in order to let them compile in `prod`, we need to supply each library a executable application to do test compile. This might be a workaround although I think fix this issue is a better way to solve such problem.

**Comment by pakopa** [comment] 2019-07-25 06:36
I am having this same issue with lazy-loaded routes.
Anyone knows of any kind of workaround for this?

**Comment by kingfolk** [comment] 2019-07-25 07:42
The issue may come from
https://github.com/ng-packagr/ng-packagr/blob/d34227f3b45358b6624df9ba76339b8b7e555f2f/src/lib/flatten/rollup.ts#L69
when there is dynamic import, rollup will try to use output.dir to build multiple bundles.

For me, the library I am trying to build is not entirely depends on Angular. So I just use [typescript-library-starte](https://github.com/alexjoverm/typescript-library-starter) 
and override the https://github.com/alexjoverm/typescript-library-starter/blob/master/rollup.config.ts#L15 to `output.dir`
will have the following issue
https://github.com/rollup/rollup/issues/2072
which just says umd bundle format is not compatible for dynamic import. As I googled what that means, one of github issue says `IIFE and UMD formats are (purposefully) self-contained`
https://github.com/lukeed/navaid/issues/5#issuecomment-488540276

It seems a lot of effort to make umd support dynamic import. For now I guess the best way right now is to support rollup build multiple bundles and add a ng-packagr option to disable umd build.

**Comment by JairoMarques** [comment] 2019-09-02 16:14
> I am having this same issue with lazy-loaded routes.
> Anyone knows of any kind of workaround for this?

Same here. My library has new Angular 8 syntax:

`loadChildren: () => import('./applications/applications.module').then(m => m.DsApplicationsModule) `

that now doesn't work.

But works with:
```

import { DsApplicationsModule } from './applications/applications.module';
export function getApplicationsModule() {
 return DsApplicationsModule;
}
...
loadChildren: getApplicationsModule 
...
```

**Comment by alan-agius4** [comment] 2019-09-02 18:49
I am not too keen about adding support for this feature, and the main reason for this is that IMHO it will make it easier for misuses and incorrect patterns.

The main point of this feature request seems to have lazy loaded modules in a library, which really libraries shouldn’t have! It should be the responsibility of the application to load a module from a library lazily or not, if you want a library to be more granular and tree shakable you should opt for secondary entry points.    

Route declaration should happen at an application level.

Related also to: https://github.com/angular/angular/issues/31893#issuecomment-516615243

**Comment by blemaire** [comment] 2019-09-04 07:29
@alan-agius4 what if the library is simply a plugin which contains its own routing?
Per instance I could be writing a messaging plugin which is meant to be imported and used by several applications. Correct me but a plugin should really be a library (as it is meant to be used in a parent module). Why couldn't we have lazy loaded routes within this plugin?

**Comment by raphael22** [comment] 2019-09-04 09:51
I'm agree with @blemaire.
In a plugin context you want the library to be autonomous.
Even more when you deal with non routed lazy-loaded component.

If you take my exemple in earlier post, why a plugin button which call a modal could not take the responsability of it ? THIS look like a bad pattern to me.

**Comment by devbean** [comment] 2019-09-05 01:12
I agree with @blemaire  and @raphael22 . If you think this is an incorrect pattern, you could write it in document as best practices or just give warnings. Since the feature is useful in some situations, it should not be missed in code. Just like many deprecated code. Developers are not recommended to use deprecated code but it is still in the framework.

**Comment by miladamery** [comment] 2019-09-07 11:53
Hi. i'm facing the same problem in our company projects. @JairoMarques said that we can solve this by something like:
```typescript
import { DsApplicationsModule } from './applications/applications.module';
export function getApplicationsModule() {
 return DsApplicationsModule;
}
...
loadChildren: getApplicationsModule 
...
```
Is this solution appropriate? What we lose here by using this?

**Comment by raphael22** [comment] 2019-09-07 13:15
I didn't try but i guess you get your DsApplicationsModule bundle in your umd ?
So you will lose lazy-load purpose here.

**Comment by JairoMarques** [comment] 2019-09-09 14:27
@raphael22 You're right! Just work, but without Lazy-load

**Comment by SparkMonkey** [comment] 2019-10-19 18:23
Same here. I'm still looking for a solution.

In my case I can't export an Angular Module that use new dynamical import statement.

"Lambda not supported".

If i add // @dynamic, ngc tells me that I have to use esnext or commonjs.

Thing is my tsconfig already use esnext.

So I suppose the issue is on ng-packagr side.

**Comment by itspers** [comment] 2019-11-13 13:53
didnt get point of @alan-agius4 

Case:
Im making UI library. I have Calendar module with calendar widget, that can be imported by consumer and used as simple UI widget when he need it.
Next i made Datepicker module with datepicker directive, which **when time will come** will create CdkOverlay with calendar inside.
So obvious solution i planned to import Calendar module dynamically when popup opened only and render there calendar directly. I even didnt thought it can be problem – wrote whole code at once and only then saw error _"You must set "output.dir" instead of "output.file...."_ in terminal after noticed browser want refresh...

**Comment by s2young** [comment] 2019-11-14 16:50
My Case: 

Writing a simple content management system for re-use across multiple sites.  The consuming site configures a route to point to the CMS.  Within that route, the CMS is fully functional with its own set of child routes for managing pages and content.  The CMS is built as an angular 9 library.

Pages are assembled by selecting from a set of UI components.  Any page can have any set of components.  I want all my components to be lazy-loaded to minimize overhead and load only what the page data calls for.

Likewise, there are editor components for each UI component.  Those must be lazy-loaded within the CMS itself to allow the editor to move elements up and down and edit content.

The CMS is a library using Angular 9 and I'm trying to do an ng build and get the 'output.dir' error because it's trying to output multiple chunks.

Any help on this would be greatly appreciated.  Thanks!

**Comment by s2young** [comment] 2019-12-26 21:29
Any movement on this?

**Comment by Azbesciak** [comment] 2020-01-23 15:00
Guys, I really need that ;)
And IMO I am not alone

**Comment by darekf77** [comment] 2020-01-23 15:23
@Azbesciak 

I disabled umd in ng-packard and I was able to keep lazy loading in library:

1. In file `node_modules/ng-packagr/lib/flatten/rollup.js`
```
 const bundle = yield rollup.rollup({
            context: 'this',
            external: moduleId => externalModuleIdStrategy.isExternalDependency(moduleId),
            inlineDynamicImports: true,  // CHANGE THIS TO TRUE
```

2. In file `node_modules/ng-packagr/lib/ng-package/entry-point/write-bundles.transform.js`comment this code:
```
// log.info('Bundling to UMD');
// yield flatten_1.flattenToUmd(Object.assign(Object.assign({}, opts), { entryFile: fesm5, destFile: umd, dependencyList: opts.dependencyList }));
```

**Comment by Azbesciak** [comment] 2020-02-04 06:40
@darekf77 Did not tested, but are you sure that turing `inlineDynamicImports` to `true` will not disable lazy completely? I mean - code *should* be inlined this way...?

**Comment by frank-26** [comment] 2020-02-26 06:53
same here.

**Comment by rootlocus22** [comment] 2020-03-01 16:53
There is no way we can do code splitting in angular libraries. I am creating a library of features which needs to be loaded on demand and not eagerly. Any update on this?

**Comment by andresbm05** [comment] 2020-03-03 18:01
Same problem here, I'm working on a company product which is huge. We want to split it in several libraries so we can sell the product with only those features needed.

Each feature, if required for the project, will be loaded on its own route and should be able to load all its pages in that context. Some features may have a large amount of pages so lazy loading is a must.

Any chance of getting this soon?

**Comment by Thilo84** [comment] 2020-03-06 16:05
We also have the same problem here. We have a custom component library with several modules. Each module can have lazy loaded translations:
```
export class ContactModule {
    constructor(private translateService: TranslateService) {
        translateService.addPartials([
            { lang: 'de', translations: () => import('./i18n/de-CH.json') },
            { lang: 'fr', translations: () => import('./i18n/fr-CH.json') },
            { lang: 'it', translations: () => import('./i18n/it-CH.json') },
            { lang: 'en', translations: () => import('./i18n/en.json') }
        ]);
    }
}
```

Any update on this? Or is there a recommendation for such a use case?

**Comment by raphael22** [comment] 2020-03-09 14:25
@Thilo84 I used http call here to lazy-load my translation. Then use setTranslation from ngx-translate with shouldMerge argument.

**Comment by cwc-products** [comment] 2020-04-07 18:51
I am also have issues with this.  I would like to lazy load a library into another library that will eventually be loaded into the main application.

**Comment by napstr** [comment] 2020-04-07 20:53
I created a workspace from scratch and generated a lib using the latest angular CLI (9), and as a side effect this is no longer an issue. It does not use ng-packgr directly, `ng build` now seems to do some magic itself and builds a library with dynamically imported lazy routes which can be uploaded to NPM and consumed in other projects.

**Comment by cwc-products** [comment] 2020-04-07 21:07
@napstr sounds like your recommendation is to upgrade to Angular 9.  FYI, I just finished upgrading to angular 8.

**Comment by napstr** [comment] 2020-04-07 23:33
@cwc-products yeah, definitely, although I'm not sure if that's what actually does the trick, I'm very new to Angular, just trying to make an inherited, fairly complex application work. Maybe creating the workspace from scratch reset some old configs. I thought I would be stuck on 8 due to this issue, but then I needed Ivy, and then I needed a bugfix in Ivy that was not backported to 8, so I decided to bite the bullet and update to 9, disabling lazy loading as a tradeoff...just to discover that the dynamic syntax suddenly just works :tm:

**Comment by riheldo** [comment] 2020-04-15 20:23
> I created a workspace from scratch and generated a lib using the latest angular CLI (9), and as a side effect this is no longer an issue. It does not use ng-packgr directly, `ng build` now seems to do some magic itself and builds a library with dynamically imported lazy routes which can be uploaded to NPM and consumed in other projects.

@napstr what was the version?
I tried replicate but angular reported me with the same errors

**Comment by daiscog** [comment] 2020-04-27 15:22
> The main point of this feature request seems to have lazy loaded modules in a library, which really libraries shouldn’t have! (https://github.com/angular/angular/issues/31893#issuecomment-516615243)

@alan-agius4 I am in the same situation as @andresbm05; I'm working on a large project that we want to decompose into several libraries that the customer can buy individually and use to compose their app with the features they need for their project.

The customer's app should **absolutely not** be responsible for having to declare the internal routing of each individual module.  For one thing, upgradability would be a nightmare.

At the moment, we can only package each module as a single lazy-loaded module that the root app router can load, but all the child routing within that module has to be eagerly loaded, which not at all optimal for us.

**Comment by napstr** [comment] 2020-04-27 15:57
@daiscog and others struggling: One thing that I forgot to mention is that I created secondary entrypoints that contain the route definitions. Maybe that helps your case too?
That way the application only has to load that small part eagerly, while the larger chunk of feature module itself stays lazily loaded.

Directory structure looks something like
```
frontend
|
\-projects
  |-featureA
  | |-ng-package.json
  | |-package.json
  | |-tsconfig.json
  | |-src
  | | |-lib                  <----- main module of featureA inside here
  | | \-public_api.ts
  | |
  | |-routing    
  | | |-ng-package.json      <----- defines a secondary entrypoint of featureA
  | | \-src
  | |   |-routes.ts          <----- lazy routes to the main entrypoint of featureA
  | |   \-public_api.ts
  |
  |-featureB
  | ...etc
  |-featureC
  | ...etc
  \-application
    |-...etc
    \-src
      \-application_routes.ts

```

The `application_routes.ts` then looks like
```
import { Routes } from '@angular/router';
import { FeatureARoutes } from 'foo/featureA/routing';
import { FeatureBRoutes } from 'foo/featureB/routing';
...etc

export const routes: Routes = [
	...FeatureARoutes,
	...FeatureBRoutes,
	...etc
];
```

Note that the application does not directly import anything from the main entry point of the features, only from the secondary routing entrypoint. The application does not have to be in the same workspace, this works exactly the same with the features uploaded as npm packages. 

Unsure how well this translates to your use cases, hope you find this helpful!

**Comment by nandagrabstechnology** [comment] 2020-05-13 06:11
Really worked for me... Good Idea. Thanks

**Comment by DefeninMaxime** [comment] 2020-05-20 08:30
Don't forget to export all your file in your public_api.ts. This was my mistake !

**Comment by alTach** [comment] 2020-10-05 22:14
in Angular 10.1 wen i try create lazy load in library i get likely error message: 
`ERROR: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.`

**Comment by Karman40** [comment] 2020-11-13 20:21
**Same issues here.**
Any ideas what is wrong?
```
ERROR: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.
An unhandled exception occurred: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.
````

**My app.routing**
```
{path: 'auth', loadChildren: () => import('../../../auth/src/lib/auth.module').then(m => m.AuthModule)},
```

**My main lib routing:**
```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import {AuthComponent} from './auth.component';

const routes: Routes = [
  {path: '', component: AuthComponent, children: [
      // {path: '', redirectTo: '/auth/login', pathMatch: 'full'},
      {path: 'login', loadChildren: () => import('./components/oauth-login-page/login.module').then(m => m.LoginModule)},
      // {path: 'registration', loadChildren: () => import('./components/oauth-registration-page/registration.module').then(m => m.RegistrationModule)},
      {path: 'password-forgot', loadChildren: () => import('./components/password-forgot-page/password-forgot.module').then(m => m.PasswordForgotModule)},
      {path: 'password-reset', loadChildren: () => import('./components/password-reset-page/password-reset.module').then(m => m.PasswordResetModule)},
      {path: 'email-verify', loadChildren: () => import('./components/email-verify-page/email-verify.module').then(m => m.EmailVerifyModule)},
  ]},
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class AuthRoutingModule { }
```

**tsconfig.lib.json**
```
  "angularCompilerOptions": {
    "skipTemplateCodegen": false,
    "strictMetadataEmit": false,
    "enableResourceInlining": true
  },
```

![image](https://user-images.githubusercontent.com/32225709/99117499-1cc83f00-25f6-11eb-9cbd-79a011febb2e.png)

**Comment by vmcbaptista** [comment] 2020-11-15 14:16
I tried to avoid the 
`ERROR: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.
An unhandled exception occurred: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.` by using dynamics imports using secondary entrypoints.

I ended up in the same situation exposed in #1562. I did a PR #1790 with an attempt to avoid the workaround presented there.

**Comment by Karman40** [comment] 2020-11-17 15:38
> I tried to avoid the
> `ERROR: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option. An unhandled exception occurred: When building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.` by using dynamics imports using secondary entrypoints.
> 
> I ended up in the same situation exposed in #1562. I did a PR #1790 with an attempt to avoid the workaround presented there.

So you managed to solve the problem? if so how?

**Comment by vmcbaptista** [comment] 2020-11-17 21:40
@Karman40 I created a quick repository to demonstrate what I did, you can check it here:

https://github.com/vmcbaptista/ng-packagr-lazy-load

Please have a look at the routing files.

I also call your attention to this change on tsconfig.json: https://github.com/vmcbaptista/ng-packagr-lazy-load/blob/742f447df91c35764538bf54bddfdadbfc19c4af/tsconfig.json#L27

It might be worth to have a look at the project https://github.com/kreuzerk/ng-samurai/ to help to create the secondary entry points (although I did not ever use it)

**Comment by Karman40** [comment] 2020-11-19 00:44
@vmcbaptista 

Thanks for your reply and help!
Please be patient. I'll test it tomorrow.

**Comment by alan-agius4** [comment] 2020-11-19 13:53
Hi all,

Closing the issue as at the moment lazy-loading is not designed to work at a library level.

See: https://github.com/angular/angular/issues/31893#issuecomment-516615243 and https://github.com/angular/angular-cli/issues/6373

In future this might be possible when Ivy libraries are published. But until then this is not a viable approach with View Engine.

**Closed by alan-agius4** 2020-11-19 13:53 UTC
Labels: feature

**Comment by Karman40** [comment] 2020-11-28 18:24
@vmcbaptista thnaks your help, but i mess something up and it doesn’t work for me.

Can I ask for help in private? Of course, if you think so, I'll pay for it if you fix your tunes for me.
