### ISSUE TITLE
Having a problem when creating package with RouterModule imported in NgModule decorator

### ISSUE THREAD

**Issue by SoundarDinesh** [ng-packagr/ng-packagr#778] opened 2018-04-17 07:11 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

I'm unable to create a package using ng-packagr@v3.0.0-rc.0. Also I'm using the latest angular version  .There is a build error i get when I run the packagr. This only happens when I import the RouterModule inside the imports section of the @NgModule decorator. Like so:

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    CommonModule,
    RouterModule.forChild(routes)
  ],
  // providers: [
  //   {
  //     provide: ROUTES,
  //     useValue: routes,
  //     multi: true
  //   },
  //   {
  //     provide: ANALYZE_FOR_ENTRY_COMPONENTS,
  //     useValue: routes, // provide them here too
  //     multi: true
  //   }
  // ],
})
export class AppModule { }

The error i get is : 
BUILD ERROR
Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'RouterModule' was called.

However, if i add it to through the providers section(commented out), then there is no error and the package is successfully _created.

#### How To Reproduce

I've created a repository containing the full app. Just download, npm install and then run npm run packagr, in order to reproduce the issue. The link to the repo : https://github.com/SoundarDinesh/lib-using-ng-packagr.git

_

#### Expected Behaviour
The package should be created when adding RouterModule.forChild in the imports section.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.0-rc.0
@angular/*: 6.0.0-rc.5
typescript: ~2.7.2
rxjs: 6.0.0-rc.0
node: v8.11.1
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by NagarajMadyastha** [comment] 2018-04-17 07:51
I get the same error when I transpile with ngc with skiptemplatecodegen=true in angular compiler option

**Comment by dherges** [comment] 2018-04-18 17:54
Hi all, can you confirm the issue is resolved by setting `skipTemplateCodegen: false`?

**Comment by SoundarDinesh** [comment] 2018-04-18 18:10
@dherges Yes, but not if i set it to false in my  tsconfig, that is the one found at the app's root folder. But rather inside ng-packagr, specifically in **compile-ngc.transform.js**  ( tsConfig.options.skipTemplateCodegen=false;). Does ng-packagr generate another tsconfig internally? Thanks for the response.

**Comment by ghost81** [comment] 2018-04-19 07:33
I can confirm too, but I too am not sure where this option should be placed.

**Comment by rhalff** [comment] 2018-04-22 12:37
As @SoundarDinesh  is showing in his commented code as a workaround you can use:
```typescript
@NgModule({
  // imports: [RouterModule.forChild(routes)],
  imports: [
    {
      ngModule: RouterModule,
      providers: [
        {
          provide: ANALYZE_FOR_ENTRY_COMPONENTS,
          multi: true,
          useValue: routes
        },
        {
          provide: ROUTES,
          multi: true,
          useValue: routes
        }
      ]
    }
  ],
  exports: [
    RouterModule
  ]
})
```
Which is the plain version of what a call to `forChild()` will produce.

It's like copy & pasting angular internals into your own code though, so it doesn't seem like a very elegant solution.

Perhaps the compiler could support some well known function calls like these?  Or have it somehow detect pure functions and have the compiler call the function en route, producing the above expansion.

**Comment by rhalff** [comment] 2018-04-28 00:05
Update:

The correct solution seems to be:

```typescript
export const routerModuleForChild = RouterModule.forChild(routes)

@NgModule({
  imports: [
    routerModuleForChild
  ],
  ...
})
```
See: https://github.com/ngxs/store/blob/master/packages/router-plugin/src/router.module.ts

**Comment by tashoecraft** [comment] 2018-05-01 20:43
No luck with anything above. While the library builds correctly, I get errors when trying to use it no matter what I try

**Comment by abnerey** [comment] 2018-06-18 22:51
The answer from @rhalff  works for me, but I had import "ModuleWithProviders" from "@angular/core" to be used in Angular v6, because ngc needs the variable's type metadata, something like this:

export const translateForRoot: ModuleWithProviders = TranslateModule.forRoot();

Same for "forChild"

**Comment by alan-agius4** [comment] 2021-11-14 07:01
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.

**Closed by alan-agius4** 2021-11-14 07:01 UTC
Labels: bug
