### ISSUE TITLE
rootDir package.json

### ISSUE THREAD

**Issue by georgelviv** [ng-packagr/ng-packagr#1675] opened 2020-06-24 14:16 UTC
https://github.com/ng-packagr/ng-packagr/blob/fbeee3ee477737a8d9be90f88d0e9b2a3d3b887c/src/lib/ts/tsconfig.ts#L89

In case if I want to display a package.json version in lib, and I cannot change rootDir, what should I do? put public.api in the root folder with package.json?

'rootDir' is expected to contain all source files.       
 import { version } from '../package.json';

**Comment by alan-agius4** [comment] 2020-11-11 10:41
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1675

**Closed by alan-agius4** 2020-11-11 10:41 UTC
