### ISSUE TITLE
Dynamic imports

### ISSUE THREAD

**Issue by mhdSid** [ng-packagr/ng-packagr#449] opened 2017-12-26 13:07 UTC
## Type of Issue
No support for esnext modules

```
[ x] Feature Request
```

## Description
I'm trying to to dynamically use an import statement in a project that depends on ng-packagr. 
Any idea if this is supported?

#### Version Information

```
ng-packagr: latest
@angular/*: latest
typescript: latest

```

**Comment by dherges** [comment] 2018-02-22 18:22
No, I guess not. Rollup will not ne able to determine whether the `require()`'d code is external or whether should be written to the bundle. Does the typescript compilation even succeed or is a dynamic import cause for a tsc/ngc build error?

**Comment by mhdSid** [comment] 2018-02-23 09:50
The compilation reached the second step and stopped after a tsc/ngc build error.

**Comment by mhdSid** [comment] 2018-02-23 09:53
It has been almost two months since the first comment, and we decided not to use ng-packagr. The best solution that fits our needs was to put the web components .ts files code as is in a separate repo, and once integrated in a project, we let angular cli takes care of all the minification and bundling.

**Comment by ghaiat** [comment] 2018-04-09 17:42
hello, any update on this ?

**Comment by lucasvst** [comment] 2018-06-28 17:30
Has anyone got it?

Same error for me, even if I put { "module": "esnext" } in my tsconfig.app.json.

**Comment by mhdSid** [comment] 2018-06-28 17:57
This is still not supported

**Comment by Goonersid** [comment] 2018-07-23 17:56
Is this on the roadmap!?? Could be helpful in deciding for an alternate solution

**Comment by ViceIce** [comment] 2019-07-15 12:32
This is really a show stopper 😢  Any known workaround?

**Comment by mahdiridho** [comment] 2019-08-06 04:08
@lucasvst same problem. I can run the apps well with dynamic import and "esnext" module config, but when run ng-packagr it shows error :

Compiling TypeScript sources through ngc
ERROR: PROJECTPATH/src/app/auth-client/auth-client.router.module.ts:55:1: Error encountered in metadata generated for exported symbol 'AuthClientRouterModule': 
 PROJECTPATH/src/app/auth-client/auth-client.router.module.ts:20:27: Metadata collected contains an error that will be reported at runtime: Lambda not supported.
  {"__symbolic":"error","message":"Lambda not supported","line":19,"character":26}

My angular-cli version is 7.3.9 and we won't move to version 8 yet as all projects running on version 7

**Comment by Mani2693** [comment] 2019-08-13 05:33
We are facing same issue , Workaround we have  is to use System.import() , This is not the solution because when you compile your library into any project using Angular-cli then you get below warning 
![image](https://user-images.githubusercontent.com/11607412/62917358-905b1b00-bdb9-11e9-8e79-4c6ecbbfa881.png)

Note: Above warning doesn't cause any issue with application , But it is scary to know this workaround will not work for so long 
Angular version is 7.3.9 
ng-packgr is 2.4.1

**Comment by miladamery** [comment] 2019-09-07 05:07
Hi. i'm facing the same problem in our company projects. In [Rollup config error on dynamic import during library build](https://github.com/ng-packagr/ng-packagr/issues/1285#issuecomment-527196671) JairoMarques said that we can solve this by something like this:
```typescript
import { DsApplicationsModule } from './applications/applications.module';
export function getApplicationsModule() {
 return DsApplicationsModule;
}
...
loadChildren: getApplicationsModule 
...
```
Is this solution appropriate? What we lose here by using this?

**Comment by SparkMonkey** [comment] 2019-10-18 15:57
Same here. I'm still looking for a solution

**Comment by alan-agius4** [comment] 2019-10-19 15:18
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1285

**Comment by alan-agius4** [comment] 2019-10-19 15:19
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1285

**Closed by alan-agius4** 2019-10-19 15:19 UTC
Labels: community: need feedback
