### ISSUE TITLE
Function calls are not supported in decorators but 'LoggerModule' was called.

### ISSUE THREAD

**Issue by javo2222** [ng-packagr/ng-packagr#1127] opened 2018-10-22 12:40 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

I wrote an angular logger library with ng-packagr to use this in different angular applications. The library doesn't do much more than printing something to the console in the constructor of the service. Everything works fine without --prod, so without AOT compile, in the angular application.

Besides I tried different ng-versions (5.x.x, 6.x.x & 7.x.x). But in all cases everytime (with AOT) the same error when I call LoggerModule.forRoot() in the app.module of the application:

```
ERROR in Error during template compile of 'AppModule' 
Function calls are not supported in decorators but 'LoggerModule' was called.
```

I read many articles about this topic, tried different angularCompilerOptions in tsconfig. Any further ideas out there? The module works fine without AOT (but this is no option for us)...

#### How To Reproduce

Write a library like the usage example of: https://www.npmjs.com/package/ng-packagr

Use this library in a new angular application which is generated by the angular cli by calling LoggerModule.forRoot() in the app.module.ts.

NgModule of the library:
```
@NgModule({
  declarations: [],
  imports: [],
  providers: []
})
export class LoggerModule {

  static forRoot(): ModuleWithProviders {
    return {
        ngModule: LoggerModule,
        providers: [LoggerService]
    }
  }
}
```

NgModule of the application:
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    LoggerModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent],
  entryComponents: [AppComponent]
})
export class AppModule {
}
```

Try ng build --prod...

#### Expected Behaviour

The build of the ng-app works with and without --prod flag / aot compiler. 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^4.3.1
@angular/*: ^6.1.0
typescript: ~2.9.2
```

**Comment by TimMeissner** [comment] 2018-11-09 12:53
export loggerModule =  LoggerModule.forRoot();

add loggerModule to imports, should work

**Comment by dherges** [comment] 2019-01-02 19:45
Hi, do you have a reproduction?

**Comment by christophercr** [comment] 2019-01-25 12:46
@dherges yes, I have a repo with the exact same issue: https://github.com/NationalBankBelgium/ngx-form-errors.

Then, the packaged library is used in the demo app: https://github.com/NationalBankBelgium/ngx-form-errors/tree/master/demo-app

If you try to run the demo app with AOT it will fail with this error:

```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'NgxFormErrorsModule' was called.
```

**Comment by christophercr** [comment] 2019-02-01 15:12
I finally found the root cause of the issue: calling `throw` (or any function) inside the `forRoot()` breaks the `metadata.json` generated by `ngc`.

So, previously I had this:

```typescript
// inside the NgxFormErrorsModule class

public static forRoot(formErrorsConfig: NgxFormErrorsConfig): ModuleWithProviders {
	if (!formErrorsConfig || !formErrorsConfig.formErrorComponent) {
		throw new Error("NgxFormErrorsModule: a config object should be provided containing the error message component to be used");
	}
	return {
		ngModule: NgxFormErrorsModule,
		providers: [NgxFormErrorsMessageService, { provide: NGX_FORM_ERRORS_CONFIG, useValue: formErrorsConfig }]
	};
}
```

So, refactoring the method as follows solved the issue:

```typescript
public static forRoot(formErrorsConfig: NgxFormErrorsConfig): ModuleWithProviders {
	return {
		ngModule: NgxFormErrorsModule,
		providers: [NgxFormErrorsMessageService, { provide: NGX_FORM_ERRORS_CONFIG, useValue: formErrorsConfig }]
	};
}

// now the check is done in the constructor
public constructor(@Optional() @Inject(NGX_FORM_ERRORS_CONFIG) formErrorsConfig: NgxFormErrorsConfig) {
	if (!formErrorsConfig || !formErrorsConfig.formErrorComponent) {
		throw new Error("NgxFormErrorsModule: a config object containing the Error component to be used should be provided via the forRoot() method."
		);
	}
}
```

**Comment by yglin** [comment] 2019-07-18 05:52
Got same problem here and solved with @christophercr 's method, THANX~
But a little difference is that I don't have **throwing error** in my forRoot().
I have to move the whole block of operations, **if (!config) { ...**, as below...

```
export class SharedInfraLogModule {
  
  static forRoot(config?: LogConfig): ModuleWithProviders {
    if (!config) {
      config = {
        threshold: LogLevel.Warning
      };
    }
    return {
      ngModule: SharedInfraLogModule,
      providers: [
        LogService,
        {
          provide: LogServiceConfigToken,
          useValue: config
        }
      ]
    };
  }
```

... to the service constructor ...

```
  constructor(@Optional() @Inject(LogServiceConfigToken) private config) {
    if (!this.config) {
      this.config = {
        threshold: LogLevel.Warning
      };
    }

```

It seems AOT gets upset if forRoot() does any operation before returning the module definition.
Do I describe the problem correctly?

**Comment by alan-agius4** [comment] 2019-10-28 05:01
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1428

**Closed by alan-agius4** 2019-10-28 05:01 UTC
Labels: cannot reproduce

**Comment by arifullahjan** [comment] 2020-01-10 16:33
> Got same problem here and solved with @christophercr 's method, THANX~
> But a little difference is that I don't have **throwing error** in my forRoot().
> I have to move the whole block of operations, **if (!config) { ...**, as below...
> 
> ```
> export class SharedInfraLogModule {
>   
>   static forRoot(config?: LogConfig): ModuleWithProviders {
>     if (!config) {
>       config = {
>         threshold: LogLevel.Warning
>       };
>     }
>     return {
>       ngModule: SharedInfraLogModule,
>       providers: [
>         LogService,
>         {
>           provide: LogServiceConfigToken,
>           useValue: config
>         }
>       ]
>     };
>   }
> ```
> 
> ... to the service constructor ...
> 
> ```
>   constructor(@Optional() @Inject(LogServiceConfigToken) private config) {
>     if (!this.config) {
>       this.config = {
>         threshold: LogLevel.Warning
>       };
>     }
> ```
> 
> It seems AOT gets upset if forRoot() does any operation before returning the module definition.
> Do I describe the problem correctly?

Wow ... yes but why?

**Comment by LeonardoSSev** [comment] 2020-03-27 14:11
I set the `fullTemplateTypeCheck` as one of the `angularCompilerOptions` in the tsconfig.json and it worked for me.
