### ISSUE TITLE
Please add a @NgModule annotation in AOT Compilation

### ISSUE THREAD

**Issue by MurhafSousli** [ng-packagr/ng-packagr#355] opened 2017-12-02 18:27 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

After compiling the package and runing `ng serve --aot` , I get this error

`ERROR in Error: Unexpected value 'NgProgressModule in .........../ngx-progressbar/node_modules/@ngx-progressbar/core/src/ng-progress.module.d.ts' imported by the module 'AppModule in .............../ngx-progressbar/src/app/app.module.ts'. Please add a @NgModule annotation.`

#### How To Reproduce

The module looks like this

```ts
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgProgressBarComponent } from './components/ng-progress-bar/ng-progress-bar.component';
import { NgProgressComponent } from './components/ng-progress/ng-progress.component';
import { NgProgress } from './services/ng-progress.service';

@NgModule({
  declarations: [
    NgProgressComponent,
    NgProgressBarComponent
  ],
  exports: [
    NgProgressComponent
  ],
  imports: [
    CommonModule
  ],
  providers: [
    NgProgress
  ]
})
export class NgProgressModule {
}
```

#### Expected Behaviour

Should work as it does in `ng serve`

#### Version Information

```
ng-packagr: v2.0.0-rc.4
node: v8.4.0
@angular: v5.0.0
rxjs: 5.5.x
zone.js: 0.8.14
```

**Comment by JoeQueR** [comment] 2017-12-20 08:53
Don't know if it helps, but i had the same issue : 

Turns out, my generated metadata `[library].metadata.json` was empty (no modules definitions, exported components was missing, etc...) wich work fines without aot activated... :(

Does your metadatas contains data to your `NgProgressModule` ?

My `ng-package.json` was refering to `public_api.ts`, which was exporting "barrel" files (`index.ts`)  wich themself was referencing other barrel files. But rather than exporting with the full path to barrel files `index.ts`, i was exporting the directory :

old `public_api.ts` :
`export * from "/my-app/directory"`

new `public_api.ts` :
`export * from "/my-app/directory/index"`

It's really important to specify explicitly the barrel file, in order to have metadata set correctly.
One way to correct it is to simply remove the barrels files and export everithing in `public_api.ts`

After that, i had problems with cyclic depedencies and barel files... But that's an another story.

Hope it help !

**Comment by MurhafSousli** [comment] 2017-12-20 09:40
I think it is solved in v2.0.0-rc.6. I use 2.0.0-rc.7 and it works fine

**Comment by MasDevProject** [comment] 2018-01-09 20:50
Thank you @JoeQueR.
Your tip solves the problem

**Comment by miloszpp** [comment] 2018-01-24 12:13
Thanks @JoeQueR , it helped me too!

**Comment by dherges** [comment] 2018-02-04 17:07
Hi all,

what is the current status? Has the issue been solved in the mean-time? If no, could someone please give access to a reproduction?

**Comment by isellsoap** [comment] 2018-02-13 11:44
@MurhafSousli I have the same original issue in v2.0.0 stable.

**Comment by dherges** [comment] 2018-02-22 18:09
The issue needs a reproduction if action should be taken. Plese provide one, if possible with access to source code in a repo or try to reproduce in the integration tests of ng-packagr.

**Comment by joeldatabox** [comment] 2018-03-22 00:04
Thanks @JoeQueR . This worked for me.

**Comment by SaturnTeam** [comment] 2018-05-04 09:06
You should add this to FAQ. It takes a month to find this solution

**Comment by bitbeter** [comment] 2018-05-12 12:31
Same issue in "ng-packagr": "^3.0.0-rc.5"

**Comment by LinBoLen** [comment] 2018-05-14 07:48
Same issue in "ng-packagr": "^3.0.0-rc.5"

**Comment by LinBoLen** [comment] 2018-05-14 07:50
export directory path is incorrect, must export with file

**Comment by abbazabacto** [comment] 2018-05-31 09:56
Same issue in "ng-packagr": "^3.0.0"

**Comment by abbazabacto** [comment] 2018-05-31 11:06
@dherges as you request for a repo demonstrating the issues hasn't been answered yet, I created one: https://github.com/abbazabacto/ngpackagr-barrel-issue

See the `README.md` for a detailed description on how metadata fails to generate when referencing TypeScript barrels `index.ts` without an explicit `/index` file reference.

I demonstrated that the issue occurs for all the TypeScript barrels, no matter how deep they are.

Using TypeScript barrels is really common, and because this issue is only visible when consumers of the module run an AOT build it is quite hard to detect.

A workaround is now to just reference TypeScript barrels with an explicit `/index`. It would be best if `ng-packagr` made it unneeded to do this. As this is already an old issue, I believe a lot of people (including me) already updated their references to barrels with `/index`, its important that both cases will work in the future.

**Comment by abbazabacto** [comment] 2018-05-31 11:48
@dherges this issue is a duplicate of https://github.com/dherges/ng-packagr/issues/195 which had more information and repo reproducing the issue already... maybe close this issue in favour of the older (and more complete one)?

**Comment by ashu12318** [comment] 2018-06-13 09:46
@abbazabacto  as I can see #195 has been labeled as wontfix. Not sure its already too long this issue is present there. I think it should have been fixed.

**Comment by dherges** [comment] 2018-06-20 18:37
Hi all, I think the way of going forward here is: try to reproduce the issue with `ngc` only (not ng-packagr, just invoke ngc on the shell).

**Comment by dherges** [comment] 2018-06-20 18:39
HI @abbazabacto , this is by far the best instructions I've got on how to reproduce. With the explanation of what's missing in the metadata I think it's an `ngc` issue. Could you try to reach out on the Angular repo as the fix would need to be in `@angular/compiler` ?

**Comment by heavybeard** [comment] 2018-12-19 13:54
> Don't know if it helps, but i had the same issue :
> 
> Turns out, my generated metadata `[library].metadata.json` was empty (no modules definitions, exported components was missing, etc...) wich work fines without aot activated... :(
> 
> Does your metadatas contains data to your `NgProgressModule` ?
> 
> My `ng-package.json` was refering to `public_api.ts`, which was exporting "barrel" files (`index.ts`) wich themself was referencing other barrel files. But rather than exporting with the full path to barrel files `index.ts`, i was exporting the directory :
> 
> old `public_api.ts` :
> `export * from "/my-app/directory"`
> 
> new `public_api.ts` :
> `export * from "/my-app/directory/index"`
> 
> It's really important to specify explicitly the barrel file, in order to have metadata set correctly.
> One way to correct it is to simply remove the barrels files and export everithing in `public_api.ts`
> 
> After that, i had problems with cyclic depedencies and barel files... But that's an another story.
> 
> Hope it help !

This is magic, but it works. Please @JoeQueR, accept my love!

**Comment by MoAsmar** [comment] 2020-04-13 15:19
@JoeQueR Saved my day after hours of investigations, thank you!

**Comment by NiklasPor** [comment] 2021-04-23 12:06
Still having this issue on ng-packagr@11.2.2. Compiling with:
```
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  },
```

Works when compiling with `enableIvy: true` tho.

**Closed** 2021-08-20 13:55 UTC
Labels: community: need feedback
