### ISSUE TITLE
Asset copy Enhancement

### ISSUE THREAD

**Issue by arvindnama** [ng-packagr/ng-packagr#1497] opened 2020-01-07 18:44 UTC
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
Recent PR https://github.com/ng-packagr/ng-packagr/pull/1465/ 
Introduced the feature to copy assets.
But the current format will limit us to :
1. Having all assets under project src .. ( from looking at the code)
2. and we cannot customize the destination folder structure.
  we are expecting assets to be under ::
  ```projects/<lib-name>/**/assets```
and destination will always be mapped to
```<dist-path>/<lib-name>/**/assets```

in my project , we have multiple projects (libraries & apps)in same repo
and we have a common folder for assets .. and this is out side of the project root (as expected)

with this i would not be able to use this ng-packagr feature as is ..

#### Expected Behaviour

I was looking at the AsstePattern syntax of anuglar-builder ( browser) .. https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/browser/schema.json#L393
```
export type AssetPattern =
  | {
      /**
       * The pattern to match.
       */
      glob: string;
      /**
       * The input directory path in which to apply 'glob'. Defaults to the project root.
       */
      input: string;
      /**
       * An array of globs to ignore.
       */
      ignore?: string[];
      /**
       * Absolute path within the output.
       */
      output: string;
    }
  | string;
```
this will allow to be more granular and as a user of the ng-packagr i can get alot of flexibility ..

I wanted this feature badly for my projects so did a poc for the same ,in the forked repo https://github.com/arvindnama/ng-packagr/commit/957c8f057636d86bf7e1637fa567540bed7a81f3

NOTE: I will create a PR on the master branch with the above changes soon.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.0.0-rc3
@angular/*: 8.2.3
typescript: 3.5.3
rxjs: 6.5.3
node:12.13.1
npm 6.12.1
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by arvindnama** [comment] 2020-01-07 21:23
@Splaktar, As per your request i was trying to create a PR from my git branch,
I was trying to push my local branch to remote , but i get 
```
$ git push --set-upstream origin anama/feature/1479-asset-pattern
ERROR: Permission to ng-packagr/ng-packagr.git denied to arvindnama.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can i get permission to create and push branch plz

**Comment by arvindnama** [comment] 2020-01-07 23:09
create a PR for the above https://github.com/ng-packagr/ng-packagr/pull/1500

**Comment by Splaktar** [comment] 2020-01-15 10:45
[Original comment](https://github.com/ng-packagr/ng-packagr/pull/1465#issuecomment-567684071) that spawned this issue.

**Comment by JohnnyDevNull** [comment] 2020-03-18 12:15
I really don't understand why this is not default by design! Why things like this have to be mentioned instead of using already built in stuff like from the angular-cli.

So we have to stay with cpx.

**Comment by pburgmer** [comment] 2020-06-17 16:02
I also need this.
I would like to copy sass / less files to the dist dir. They should be located within src but in dist I don't like a src folder. So I want to copy them directly to dist instead of dist/src.

**Comment by felix-auer** [comment] 2020-07-16 12:11
@pburgmer I have the same wish as you. Do you have any solution for this?

**Comment by pburgmer** [comment] 2020-07-16 12:46
@felix-auer I use https://github.com/linnenschmidt/build-ng-packagr. It's a wrapper that supports more sophisticated asset handling.

**Comment by felix-auer** [comment] 2020-07-16 12:51
@pburgmer Thank's for your advice. I will try this tool to. 👍

**Comment by twopelu** [comment] 2021-01-19 13:16
This same issue is happening in our projects, the new feature in ng-package to copy assets is ok but it is not compliant with default structure of an Angular library created with Angular CLI, where assets are into src folder not at the same level and they are supposed to be imported from /assets not /src/assets when using them in other applications.

The propert solution would be to allow defining the output path so that you can keep the assets folder where it is and copy them to dist/library/assets instead of dist/livbrary/src/assets.

**Comment by michaelurban** [comment] 2021-07-10 00:47
This issue and issues like it are why Angular development is an unpleasant experience. I can't go more than a few days without getting rocks in my shoes.

Angular Material recommends theming components ([link](https://material.angular.io/guide/theming-your-components)) in a way that is not easy to develop/package, by default, using ng-packagr.  

I have two issues with the current implementation:

0.  `np-package.json` `assets` only support `strings`. As mentioned above, `AssetPattern` makes much more sense.

The current implementation simply copies the files specified in the top-level `ng-package.json` (more on this in point 1 below) to the output folder, mirroring their locations in the source tree. This makes no sense in most situations and I'd argue that it makes this issue more of a bug report than a feature request.

For example, I'm packaging a library that follows Angular Material's guidelines for component theming. I need to distribute Sass theme files so that downstream apps can import them with `@use '~@project/name/submodule/_component.theme' as componentTheme`. Putting everything under `src` breaks this nice, predictable pattern.

1. Only `assets` specified in a top-level `ng-package.json` seem to be collected.  Libraries with secondary entry points/submodules with nested `ng-package.json` will have their `ng-package.json`'s `assets` property ignored. 

Going back to my Material-like component library, being able to specify theme assets in the same `ng-package.json` as the secondary entry point just makes sense.

Wrapping up:

Without using Bazel or resorting to pre/post hacks (that aren't compatible with `npm link`) how would I package an Angular Material-like component library using ng-packagr?

**Comment by michaelurban** [comment] 2021-09-27 21:48
Any movement?

**Comment by iursevla** [comment] 2021-12-31 19:30
> @felix-auer I use https://github.com/linnenschmidt/build-ng-packagr. It's a wrapper that supports more sophisticated asset handling.

Sadly it doesn't seem to work with angular 13

**Comment by dereekb** [comment] 2022-01-31 02:55
Ran into this myself. Just being able to set output location would solve my problem. My output all ends up at src/lib instead of in the lib folder with the code where I would like it to be.

**Comment by iursevla** [comment] 2022-01-31 18:51
@dereekb Dunno if you're using build-ng-packagr. If you are then use my fix for angular 13: https://www.npmjs.com/package/@iursevla/build-ng-packagr

**Comment by michaelurban** [comment] 2022-01-31 18:58
@iursevla Thanks for that but this really should be addressed by the project. I can't believe that I've been waiting to hear about movement on this for over six months. Not sure why it's being ignored.

**Comment by michaelurban** [comment] 2022-01-31 19:01
@alan-agius4 Could you take a look at this?

**Comment by alan-agius4** [comment] 2022-01-31 19:09
This issue is not being ignore, but there are other issues with higher priority. 

A PR would be welcome, if anyone wants to take a stab at this.

**Comment by michaelurban** [comment] 2022-02-01 09:36
@alan-agius4 Without communication it's hard to tell what's being ignored and what's low priority. After hitting this issue I bit the bullet and learned Bazel. The various packages were in constant flux, if documentation for the packages existed it invariably lagged behind releases, was incomplete, or incorrect. 

It's not a good story.

A small enhancement here would help fill a big hole for users with a very common use case. 

I'm currently working on filling a gap in another Google project or I'd tackle this myself.  @iursevla do you have time to take this one?

**Comment by SchnWalter** [comment] 2022-02-01 11:23
> A small enhancement here would help fill a big hole for users with a very common use case.
I don't see people flocking here to ask for this feature or to provide patches. If you want something done and nobody else has volunteered, you must get your hands dirty and help, this is how open source works. Also, you do realize that this is an open source project and that are not entitled to the free work of others, right?

**Comment by michaelurban** [comment] 2022-02-01 12:13
@SchnWalter Hi Walter, I'm currently contributing to multiple F/OSS projects at the moment. As I said, I'm currently filling in a gap on Google project. I've worked on that for 52 hours over the past two weeks. Unpaid. How much more of my time am I obligated to volunteer before I can ask for assistance in another area? Is it an extra 10 hours/week, 20? You tell me. I've put in thousands of hours of unpaid F/OSS work since 2002.

I spend a lot of time encountering, tracing, and reporting Google OSS bugs. At a certain point I have other work that needs to be done for my company. And here's the rub, I find far, FAR, more bugs in Google projects than any other in the F/OSS ecosystem. Also, those bugs are resolved at a lower rate and at a slower pace than in any other large projects I've contributed to.

Angular Material has a very specific project structure. You can't achieve that structure with ng-packagr as far as I can tell. If you're building a component library in the Angular Material style, and you're concerned about the DX of your Angular library, you're going to want to replicate that project layout. Pretty simple. Angular Material doesn't have this issue because they use Bazel. 

The existence of this issue shows that people are interested in this issue. Not sure what you're arguing here.

The question goes from "should I contribute" (which I am) to "as one person, how much work can I be expected to do to be able to use a library?". I can't fix every bug I find, there are simply too many. 

I appreciate the work that Google devs are doing but the projects always have internal priorities at Google that make it frustrating as an external developer. The incentives are not aligned and I'm often left out in the cold world of "not a priority". 

Going further down this thread with you would off topic so I'm going to ignore further responses.

**Comment by TheNightmareX** [comment] 2022-03-23 14:51
I've spent a whole day looking for a non-hacky solutions to properly include assets, but finally ended up a hacky way - creating a script to move assets manually.

Angular's official document shows us the way Angular Material does, while Angular Material doesn't even use ng-packagr. I've looked into the multiple popular Angular component libraries and found that all of the ones using ng-packagr choose to use external scripts to move their assets into the dist folder manually, and the others don't use ng-packagr. Obviously, it is impossible to manage assets using ng-packagr without external scripts. This can be a reason why there are not many Angular libraries, especially component libraries.

@arvindnama created a PR #1500 for this feature at the start of 2020 but was not responded until the end of 2021, and finally got rejected because "it is stale". It is quite confusing, but as one of the contributors said that these changes are ok, maybe it can be merged if we create a PR now. I'll also have a try.

**Comment by TheNightmareX** [comment] 2022-03-23 18:00
PR #2284 created for this feature

**Closed** 2022-03-28 14:57 UTC
Labels: feature

**Comment by michaelurban** [comment] 2022-03-28 16:46
Thanks!

**Comment by michaelurban** [comment] 2022-03-28 17:12
Thanks again to @alan-agius4, but I need to point out something impressive that I stumbled across:

@TheNightmareX is still in high school.

Great work @TheNightmareX, thanks for your efforts and persistence. Respect and handshakes. I'm sure you can hit up anyone in this thread when you're ready to look for a job!
