### ISSUE TITLE
Npm link angular modules causes webpack compiler error

### ISSUE THREAD

**Issue by wip-abramson** [ng-packagr/ng-packagr#606] opened 2018-02-08 09:44 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description
I am trying to link a module built by ng-packagr into another project using npm link. 
I want this project to pick up changes that occur in the linked module.
Because I am linking from the lib folder you have to re run ng-packagr every time file changes occur in the linked project for them to be picked up in the project that uses this linked module.
The rebuilding of the package (lib folder) causes an error when the project that uses the linked module is served. I serve it using ng serve --preserve-symlinks.
By that I mean I want to be able to pick up changes that occur in the linked module while  running  project that uses this linked module.
This currently causes my Angular CLI webpack compiler to throw the following error.
Module build failed: Error: ENOENT: no such file or directory <node_module location of the linked module>
This is because when ng-packagr runs to rebundle the linked project, it first removes the files in the lib folder (The folder that I ran npm link from) before replacing them with the newly bundled project.
So when these files are removed, webpack see's that there has been a change, tries to recompile and fails because these files are not yet ready (ng-packagr is still runinng).

#### How To Reproduce

1. Setup 2 angular projects, where one includes the other as a dependency
2. Package the project that is the dependency using ng-packagr
3. Cd into the destination that ng-packagr places packaged files (lib usually)
4. Run npm link
5. In the other project, run npm link <dependency_name>
6. Now making a change to the dependency project and rerunning ng-packagr should show changes in the module's folder in node_modules of the other project. Ie the one that uses the dependency. This works fine for me.
7. Serve the project that uses this dependency. ng serve --preserve-symlinks
8. Make a change in the dependency project and run ng-packagr
9. In the terminal where the served project is running you will see the error

#### Expected Behaviour

I would like to be able to make a change in the linked project, rebuild the lib folder and have the changes picked up while the project that uses the linked lib module is running/served.

For this to happen the behavoir I would expect to see is the package is built first and then written to the lib folder destination.

A hack to achieve this that worked for me was.

1. Set ng-packagr destination to a temp folder
2. When built, copy files from temp folder into the lib folder

This works when linking from the lib folder, however it did lead to some issues with the lib folder getting bundled into the temp during ng-packagr if it was already present.
To get around this I deleted all .ts files from the lib folder before rebuilding the package, preventing the lib folder from getting included.

These are the npm scripts I used to achieve this.

    "build-lib": "npm run del-ts && npm run packagr && npm run copylib",
    "copylib": "copyfiles -u 1 ./temp/**/*.* ./dist-lib",
    "del-ts" : "del-cli ./dist-lib/**/*.ts",
    "packagr": "ng-packagr -p ng-package.json",

If ng-packagr could do this temp folder step as part of the packaging process, or at least stop ng-packagr removing old packaged module files until the new package is ready to overrite it that would be great.

Thank you.

#### Version Information

```
ng-packagr: 1.7.0
@angular/*: 5.1.3
typescript: 2.4.2
rxjs: 5.5.5
node: 8.9.4
npm: 4.6.1
copyfiles: 1.2.0
del-cli: 1.1.0
```

**Comment by dherges** [comment] 2018-02-11 17:43
Hi, is it a duplicate of #596 ?

**Comment by wip-abramson** [comment] 2018-02-11 18:22
No I don't think so. My issue is that the lib folder's content gets removed, then ng-packagr compiles and adds the newly compiled files to the lib. Rather than ng-packagr overwritting the lib folder when the files have already been compiled.

**Comment by stephanie-dm** [comment] 2018-02-21 10:19
@dherges : I had the exact same problem as @wip-abramson . The workaround he suggested, works for me. It saves me a lot of trouble: now I don't have to restart my "ng serve" anymore each time I do a build, awesome!

**Comment by dherges** [comment] 2018-02-21 18:29
#632

**Comment by vasinkevych** [comment] 2018-03-18 09:55
As workaround, `npm pack` work well for me

**Comment by stephanie-dm** [comment] 2018-03-19 07:50
I replaced @wip-abramson 's workaround with the option from #632 : `"deleteDestPath": false,`
This also solved my problem

**Closed** 2021-07-10 21:56 UTC
Labels: feature
