### ISSUE TITLE
[BUG] Error compiling emun

### ISSUE THREAD

**Issue by andrew19881123** [ng-packagr/ng-packagr#783] opened 2018-04-18 09:52 UTC
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

> ng-packagr -p package.json

Building Angular library
Generating bundle for xxxxx
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15

**BUILD ERROR**
Unexpected token (2:20) in C:\Users\xx\Documents\xxxx\xx.enum.js
SyntaxError: Unexpected token (2:20) in C:\Users\xxxx\.ng_pkg_build\xxx\xx.enum.js
    at error (C:\Users\xxxxx\node_modules\rollup\dist\rollup.js:185:14)
    at Promise.resolve.then.catch.err (C:\Users\xxx\node_modules\rollup\dist\rollup.js:17584:6)
    at <anonymous>

_**file ts**_
```
export enum MY_ENUM {
  'X-TEST-REQUESTID',
  'X-TEST-CONVERSATIONID',
  'X-TEST-SESSIONID',
  'X-TEST-SEQUENCEID',
  'X-TEST-PROCESSID'
}
```

_**compiled js**_
```
export let MY_ENUM = {};
MY_ENUM.;    <-------------------- ERROR HERE
'X-TEST-REQUESTID' = 0;
MY_ENUM.;
'X-TEST-CONVERSATIONID' = 1;
MY_ENUM.;
'X-TEST-SESSIONID' = 2;
MY_ENUM.;
'X-TEST-SEQUENCEID' = 3;
MY_ENUM.;
'X-TEST-PROCESSID' = 4;
MY_ENUM[MY_ENUM.];
'X-TEST-REQUESTID';
"'X-TEST-REQUESTID'";
MY_ENUM[MY_ENUM.];
'X-TEST-CONVERSATIONID';
"'X-TEST-CONVERSATIONID'";
MY_ENUM[MY_ENUM.];
'X-TEST-SESSIONID';
"'X-TEST-SESSIONID'";
MY_ENUM[MY_ENUM.];
'X-TEST-SEQUENCEID';
"'X-TEST-SEQUENCEID'";
MY_ENUM[MY_ENUM.];
'X-TEST-PROCESSID';
"'X-TEST-PROCESSID'";
//# sourceMappingURL=xxxxx.enum.js.map
```
## version
"ng-packagr": "1.7.0"

**Comment by dherges** [comment] 2018-06-20 18:20
This looks like a TypeScript issue. Could you try to reproduce the issue with only tsc and nail down whether it's an issue for typescript/ng-packagr?

**Comment by alan-agius4** [comment] 2020-11-11 11:13
Closing as this is not caused by ng-packagr.

**Closed by alan-agius4** 2020-11-11 11:13 UTC
