### ISSUE TITLE
box-shadow not getting evaluated in ng-packagr>12.1.2 in IE 11

### ISSUE THREAD

**Issue by somuda86** [ng-packagr/ng-packagr#2221] opened 2022-01-13 13:49 UTC
box-shadow 0 0 3px rgba(#000000, 0.12), 0 1px 2px rgba(#000000, 0.24); works fine in ng-packagr 12.1.2 in IE11.
but not in 12.2.6. I think removing cssnano introduces this bug.

**Comment by alan-agius4** [comment] 2022-01-14 08:51
Can you please share your browserslist configuration?

**Comment by PhiLhoSoft** [comment] 2022-01-14 12:51
Just a reminder that IE11 support is deprecated in Angular 12, and removed in Angular 13…
If you still have clients / users still using IE11, you should warn them.

**Comment by somuda86** [comment] 2022-01-14 17:44
# This file is currently used by autoprefixer to adjust CSS to support the below specified browsers
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries
#
# For IE 9-11 support, please remove 'not' from the last line of the file and adjust as needed

> 0.5%
last 2 versions
Firefox ESR
not dead
IE 11

**Comment by alan-agius4** [comment] 2022-01-14 17:49
I am unable to replicate with the steps provided.

Please provide a reproduction.

**Comment by somuda86** [comment] 2022-01-20 10:36
Just style an element like  box-shadow: 0 0 3px rgba(global-colors.$color-black, 0.12), 0 1px 2px rgba(global-colors.$color-black, 0.24); Here $color-black is a variable holding color code. This kind of syntax works with modern browsers but not in IE 11.

**Comment by alan-agius4** [comment] 2022-01-20 10:38
I am unable to replicate, can you please share reproduction. 

A good way to make a minimal repro is to create a new app via `ng new` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2022-02-08 06:57
Closing since no reproduction was provided.

**Closed by alan-agius4** 2022-02-08 06:57 UTC
Labels: needs reproduction
