### ISSUE TITLE
Error during template compile, function calls are not supported in decorators.

### ISSUE THREAD

**Issue by Tyler-V** [ng-packagr/ng-packagr#822] opened 2018-04-30 13:27 UTC
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

One of my libraries dependencies requires a .forRoot() call to declare the module with providers.

I am including this Module.forRoot() in my module and it works fine, however running packagr for the project fails on compilation.

#### How To Reproduce

```
import { DeviceDetectorModule } from 'ngx-device-detector';

@NgModule({
    imports: [
        DeviceDetectorModule.forRoot(),
    ],
   ...
}
```

```
BUILD ERROR
Error during template compile of 'EasyGridModule'
  Function calls are not supported in decorators but 'DeviceDetectorModule' was called.

Error: Error during template compile of 'EasyGridModule'
  Function calls are not supported in decorators but 'DeviceDetectorModule' was called.

    at Object.<anonymous> (C:\Users\Tyler\Documents\GitHub\@ngx-easy\node_modules\ng-packagr\lib\ngc\compile-source-files.js:69:35)
    at Generator.next (<anonymous>)
    at C:\Users\Tyler\Documents\GitHub\@ngx-easy\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Tyler\Documents\GitHub\@ngx-easy\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\Users\Tyler\Documents\GitHub\@ngx-easy\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\Users\Tyler\Documents\GitHub\@ngx-easy\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:37:60)
    at Generator.next (<anonymous>)
    at C:\Users\Tyler\Documents\GitHub\@ngx-easy\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

#### Expected Behaviour

Successful compilation for publishing.

#### Version Information

```
    "@angular/compiler-cli": "^6.0.0-rc.1",
    "@angular-devkit/build-ng-packagr": "~0.5.10",
    "@angular-devkit/build-angular": "~0.5.10",
    "ng-packagr": "^2.4.2",
    "tsickle": ">=0.27.5",
    "tslib": "^1.9.0",
    "typescript": "2.7.2",
    "@angular/cli": "~6.0.0-rc.6",
```

**Comment by Tyler-V** [comment] 2018-04-30 13:33
I have tried marking the module as dynamic and I still get the same error.

```
import { DeviceDetectorModule } from 'ngx-device-detector';

// @dynamic
@NgModule({
    imports: [
        DeviceDetectorModule.forRoot(),
    ],
   ...
}
```

**Comment by alan-agius4** [comment] 2018-04-30 13:50
You need to tell the compiler that it is a dynamic module. Check here for more info https://github.com/dherges/ng-packagr/issues/767#issuecomment-385199831

**Comment by alan-agius4** [comment] 2018-04-30 14:15
Looks like the `@dynamic` has no effect in this case. Though what I noticed was that setting `fullTemplateTypeCheck` does stop the error. I'll log an error with Angular.

**Comment by wardbell** [comment] 2018-05-05 21:52
@alan-agius4 I  have this problem too. I tried `fullTemplateTypeCheck` and it made no difference.

I have a repro.
```
git clone https://github.com/johnpapa/angular-ngrx-data.git ngrx-data-FAIL
cd ngrx-data-FAIL
git checkout ng-v6-FAIL
npm install
```

Now attempt to build the `ngrx-data` library

```bash
npm run build-lib
```

The build fails. The console says

```bash
BUILD ERROR
Error during template compile of 'NgrxDataModule'
  Function calls are not supported in decorators but 'StoreModule' was called.
  ...
```

Comment out the two ngrx imports in `NgrxDataModule` (leaving the `FooModule`) and try building again.
This time the build succeeds and generates a package in `dist`.

Note that `FooModule` is just fine.

**Comment by dherges** [comment] 2018-05-06 12:15
preface: I hate tsconfig.

@wardbell ng-packagr auto-generates a tsconfig for build. TL;DR it's just releasing 3.0.0-rc.3 that [enables `fullTemplateTypeCheck`](https://github.com/dherges/ng-packagr/commit/83f2cb6fab0b1347aacdb326cd4afb92b68e67c2#diff-1030477c98db09c51ad4bff94f8ee0a9) and should solve your specific build issue

Long story: 

```bash
$ git clone https://github.com/johnpapa/angular-ngrx-data.git ngrx-data-FAIL
$ cd ngrx-data-FAIL
$ git checkout ng-v6-FAIL
$ npm install
/* edit node_modules/ng-packagr/lib/ts/conf/tsconfig.ngc.json */
$ cat node_modules/ng-packagr/lib/ts/conf/tsconfig.ngc.json 
{
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "flatModuleId": "AUTOGENERATED",
    "flatModuleOutFile": "AUTOGENERATED",
    "skipTemplateCodegen": false,
    "strictMetadataEmit": false,
...
$ npm run build-lib 
...
Build success
```

The combinations I tried were:

#### Build success

```json
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true
```

```json
    "skipTemplateCodegen": false,
    "strictMetadataEmit": false
```

#### Build failures

```json
    "skipTemplateCodegen": false,
    "strictMetadataEmit": true
    // fullTemplateTypeCheck omitted (= default value)
```

```json
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    // fullTemplateTypeCheck omitted (= default value)
```

```json
    "skipTemplateCodegen": true,
    "strictMetadataEmit": false,
    // fullTemplateTypeCheck omitted (= default value)
```

**Comment by wardbell** [comment] 2018-05-07 04:38
## Update
@dherges explored and "solved) my use case in the [corresponding issue 23609 on the Angular repo](https://github.com/angular/angular/issues/23609#issuecomment-386876693).

**Comment by DoubleHub** [comment] 2019-07-02 08:03
I'm having this exact same error now in 2019 and I have no idea why

**Comment by TotallWAR** [comment] 2019-07-02 11:57
The same here. 
` Function calls are not supported in decorators but 'DeviceDetectorModule' was called.`
`error TS2339: Property 'forRoot' does not exist on type 'typeof DeviceDetectorModule'.`


Tried to combine
    "skipTemplateCodegen": true|false,
    "strictMetadataEmit": true|false,
    "fullTemplateTypeCheck": true|false
these options but didn't help.
Any suggestions?

**Comment by DoubleHub** [comment] 2019-07-02 15:38
@TotallWAR I fixed it by rolling back to version 1.3.1 of that package. Apparently the developer of that package released a new version (1.3.7) which is actually breaking because it completely removes forRoot() so it makes no sense that he only updated the last digit of the version number... he said himself that he's going to change this but in the mean time just use version 1.3.1 where forRoot is present

**Comment by SlimenTN** [comment] 2019-09-03 13:23
@dherges this on worked for me:
```
"skipTemplateCodegen": false,
    "strictMetadataEmit": false
```
Thanks a lot man.

**Comment by alan-agius4** [comment] 2019-10-28 05:01
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1428

**Closed by alan-agius4** 2019-10-28 05:01 UTC
