### ISSUE TITLE
Cannot read property 'maxNodeModuleJsDepth' of undefined

### ISSUE THREAD

**Issue by skaughtx0r** [ng-packagr/ng-packagr#1186] opened 2019-01-17 01:09 UTC
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

`npm run build` errors with:

```
BUILD ERROR
Cannot read property 'maxNodeModuleJsDepth' of undefined
TypeError: Cannot read property 'maxNodeModuleJsDepth' of undefined
    at Object.createProgram (/home/user/ng-test/node_modules/typescript/lib/typescript.js:73929:51)
    at analyseEntryPoint (/home/user/ng-test/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:32:24)
    at MapSubscriber.exports.analyseSourcesTransform.rxjs_1.pipe.operators_1.map.graph [as project] (/home/user/ng-test/node_modules/ng-packagr/lib/ng-v5/init/analyse-sources.transform.js:14:9)
    at MapSubscriber._next (/home/user/ng-test/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/user/ng-test/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/home/user/ng-test/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/user/ng-test/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/user/ng-test/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/home/user/ng-test/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/user/ng-test/node_modules/rxjs/internal/Subscriber.js:67:18)
```

#### How To Reproduce

This appears to happen with the simplest possible use case.

See the following repository.

https://github.com/skaughtx0r/ng-packagr-error

ng-packagr v4.5.0 works fine, however ng-packagr v4.6.0 errors.

#### Expected Behaviour

ng-packagr should build without error.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.6.0
@angular/*: 6.1.4
typescript: 2.7.2
rxjs: 6.3.3
node: 8.12.0
npm: 6.4.1
```

**Comment by alan-agius4** [comment] 2019-01-17 06:45
@skaughtx0r, thanks so much for the reproduction. I found the causes and landed a fix.

**Closed** 2019-01-17 15:06 UTC
