### ISSUE TITLE
ng update fails with "incompatible peer dependency" with v14.3.0

### ISSUE THREAD

**Issue by manbearwiz** [ng-packagr/ng-packagr#2585] opened 2023-03-16 21:02 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Running `ng update` on an angular library using angular 13 fails with an  incompatible peer dependency.

```
Package "ng-packagr" has an incompatible peer dependency to "@angular/compiler-cli" (requires "^15.0.0-next", would install "14.3.0")
```

Seems to have been introduced in this commit. https://github.com/ng-packagr/ng-packagr/commit/e3eca0ab8b2669eea0cb3fd5c46413ef6a3197d1

You can see the 15-next peer dep in the 14.3.0 tag. This seems like the only change in 14.3.0 so I'm kinda wondering if 14.3.0 was released by accident. This change is not in the v14 branch, and that package version is still 14.2.2 https://github.com/ng-packagr/ng-packagr/blob/335289d7221d51460f325870fb075de9b36e40ce/package.json#L64 
#### How To Reproduce

Run this update command on an angular 13 library using ng-packager 13. The update will try to install 14.3.0 which has a peer dependency on `@angular/compiler-cli@^15.0.0-next`

```
ng update @angular/core@14 @angular/cli@14
```

#### Expected Behavior

Angular update works without needing to force.

#### Version Information

```
ng-packagr: 13.3.1
@angular/*: 13.3.12
typescript: 4.6.4
rxjs: 6.6.7
node: 14.18.1
npm: 8.19.4
```

**Comment by alan-agius4** [comment] 2023-03-22 12:05
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/2485

**Closed by alan-agius4** 2023-03-22 12:05 UTC

**Comment by manbearwiz** [comment] 2023-03-22 23:03
Ah yeah good call. I had the same issue, Azure DevOps artifact feed didn't copy over the deprecated tag.
