### ISSUE TITLE
"Function calls are not supported in decorators" when consuming library built with ng-packagr

### ISSUE THREAD

**Issue by joeattardi** [ng-packagr/ng-packagr#885] opened 2018-05-18 20:48 UTC
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

I'm using `ng-packagr` via Angular CLI to create a library. The library builds successfully. When I try to consume this library from another Angular application, though, I get the error "function calls are not supported in decorators".

I have a module in my library, `LoggerModule`, that has a static `forModule` method:

```
@NgModule({})
export class LoggerModule {
  static forModule(module?: string): ModuleWithProviders {
    return {
      ngModule: LoggerModule,
      providers: [
        Store,
        { provide: MODULE_TOKEN, useValue: module },
        { provide: LoggerService, useFactory: LoggerServiceFactory, deps: [Store, MODULE_TOKEN] }
      ]
    };
  }
}
```

In my application, in the `AppModule`, I am calling `LoggerModule.forModule`:

```
@NgModule({
  declarations: [AppComponent],
  imports: [
    // ...
    LoggerModule.forModule('AppModule')
  ]
```

When I do a normal `ng build`, everything builds and runs fine. But if I do a `ng build --aot`, I get this error:

```
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'LoggerModule' was called.
```

I have a separate version of this library that's not built with `ng-packagr`, but rather just compiled in along with the main app, and even an AOT build is successful in that setup.

#### How To Reproduce

 - Create a module in the library with a static method
 - Build the module with ng-packagr
 - Try to consume the package in an app, calling that static method in the `AppModule`'s `imports` array

#### Expected Behaviour
This error isn't raised and the build continues.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.0.0-rc.5
@angular/compiler: 6.0.2
rollup: 0.58.2
tsickle: 0.28.0
typescript: 2.7.2
rxjs: 6.1.0
node: 9.11.1
yarn 1.6.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment] 2018-05-19 18:03
To some extend it relates to https://github.com/angular/angular/issues/23609

**Comment by alan-agius4** [comment] 2019-10-28 05:00
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1428

**Closed by alan-agius4** 2019-10-28 05:00 UTC
