### ISSUE TITLE
Support config package format when build for performance

### ISSUE THREAD

**Issue by cdllqos** [ng-packagr/ng-packagr#1700] opened 2020-07-17 16:20 UTC
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Our project was so big, so we split some domain code into different workspace.  When we debug a project, we have to run `ng build --watch`  command, it will build `bundles`、`esm5`、`esm2015`、`fesm5`、`fesm2015` package format. For developing, it output so many packages which we don't need it. So, we think it's a good idea to config package format when build. It will improve performance.

#### How To Reproduce
```bash
ng build ${projectName}
```

#### Expected Behaviour
ng-package.json
```json
{
  "xxx":"xxx",
  "packageFormat": ["fesm2015"]
}
```
it will output `fesm2015` and `esm2015` format files.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            10.0.2
@angular/compiler:     10.0.2
rollup:                2.21.0
tsickle:               0.39.0
typescript:            3.9.6
```

**Comment by JoostK** [comment] 2020-07-17 16:24
I'll refer you to #1222 for a discussion on this proposal.

**Comment by cdllqos** [comment] 2020-07-17 16:25
@JoostK OK

**Comment by alan-agius4** [comment] 2020-07-20 15:55
Duplicate of #1222

**Closed by alan-agius4** 2020-07-20 15:55 UTC
