### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by IsaacHub** [ng-packagr/ng-packagr#1667] opened 2020-06-12 08:38 UTC
http://ng-packagr.github.io/ng-packagr/

**Comment by JoostK** [comment] 2020-06-12 09:20
For completeness, this is probably about the repo's description on Github. We should just remove the link, but I can't edit the description.

**Comment by alan-agius4** [comment] 2020-06-12 09:32
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1539

**Closed by alan-agius4** 2020-06-12 09:32 UTC
