### ISSUE TITLE
InjectionToken not included in metadata

### ISSUE THREAD

**Issue by Abrissirba** [ng-packagr/ng-packagr#317] opened 2017-11-25 18:01 UTC
## Type of Issue
```
[x ] Bug Report
[ ] Feature Request
```

## Description

I am exporting the following InjectionToken ```export const SX_NGX_FABRIC_DIALOG_DATA = new InjectionToken<any>('SxNgxFabricDialogData');```

When I run ng-packagr, the InjectionToken is not included in the metadata.json file which resulted in the following error ``` Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler``` when building with the following flags ```ng build --prod --aot --sourcemaps --build-optimizer --named-chunks --stats-json```

#### How To Reproduce
Add an InjectionToken in you library, run ng-packagr and try to use that injection token in the app that refereneces the library. Project can be found here: https://github.com/Abrissirba/sx-ngx-fabric

#### Expected Behaviour

The injection token should be included in the metadata.json

#### Version Information
```
ng-packagr: v2.0.0-rc.3
node: v8.x.y
@angular: 
rxjs: "^5.5.2",
zone.js: "^0.8.14"
```

**Comment by DavidParks8** [comment] 2017-11-25 19:49
I don’t see the token being included in any typescript decorator in your library. I believe the decorators are the source of that metadata. This looks like an incomplete use of the injection token in your library.

**Comment by Abrissirba** [comment] 2017-11-26 06:07
In my library the InjectionToken is only used in the following method in dialog.service.ts. This is the same way that angular material handles dialogs and in that library the InjectionToken is included in the metadata. https://github.com/angular/material2/tree/master/src/lib/dialog

```
 /**
   * Creates a custom injector to be used inside the dialog. This allows a component loaded inside
   * of a dialog to close itself and, optionally, to return a value.
   */
  private createInjector<T>(config: SxNgxFabricDialogConfig, dialogRef: SxNgxFabricDialogRef<T>): PortalInjector {
    const injectionTokens = new WeakMap();

    injectionTokens.set(SxNgxFabricDialogRef, dialogRef);
    injectionTokens.set(SX_NGX_FABRIC_DIALOG_DATA, config.data);

    return new PortalInjector(this.injector, injectionTokens);
  }
```

**Comment by DavidParks8** [comment] 2017-11-26 06:27
What I meant, is that you didn't include the token in a module's providers [like angular material does](https://github.com/angular/material2/blob/6e865b7ba402c826d57688b545f8f53e66e05e32/src/lib/dialog/dialog-module.ts#L50). [Yours](https://github.com/Abrissirba/sx-ngx-fabric/blob/220599a4e0bcd7ee3fdb50f416332582d1012ac9/src/app/sx-ngx-fabric/dialog/dialog.module.ts#L31) is missing the injection token. Thus, it will not be part of the metadata.

**Comment by Abrissirba** [comment] 2017-11-26 06:42
I see, however if you look in the material file you linked there is also an InjectionToken called  MAT_DIALOG_DATA and that is not included in the modules provider from what I can see.

**Comment by DavidParks8** [comment] 2017-11-26 16:32
Good point. I just cloned your library and built it, then linked it, then built the demo app with the linked library with the compiler commands you provided and it worked perfectly. I wonder if there is something going on in the app you are trying to use your library from?

**Comment by DavidParks8** [comment] 2017-11-26 16:48
Specifically, it's having trouble resolving paths.
```
Field 'browser' doesn't contain a valid alias configuration
                    resolved symlink to C:\Users\dapar\source\repos\sx-ngx-fabric-master\dist-pkg\src\app\sx-ngx-fabric\dialog\index.ts.js
                      using description file: C:\Users\dapar\source\repos\sx-ngx-fabric-master\dist-pkg\package.json (relative path: ./src/app/sx-ngx-fabric/dialog/index.ts.js)
                        no extension
                          Field 'browser' doesn't contain a valid alias configuration
                          C:\Users\dapar\source\repos\sx-ngx-fabric-master\dist-pkg\src\app\sx-ngx-fabric\dialog\index.ts.js doesn't exist
                        .ts
                          Field 'browser' doesn't contain a valid alias configuration
                          C:\Users\dapar\source\repos\sx-ngx-fabric-master\dist-pkg\src\app\sx-ngx-fabric\dialog\index.ts.js.ts doesn't exist
                        .js
                          Field 'browser' doesn't contain a valid alias configuration
                          C:\Users\dapar\source\repos\sx-ngx-fabric-master\dist-pkg\src\app\sx-ngx-fabric\dialog\index.ts.js.js doesn't exist
                        as directory
                          C:\Users\dapar\source\repos\sx-ngx-fabric-master\dist-pkg\src\app\sx-ngx-fabric\dialog\index.ts.js doesn't exist
```

**Comment by dherges** [comment] 2018-02-22 18:08
Hi all, what is the current status here?

The error `Field 'browser' doesn't contain a valid alias configuration` is pretty generic in Anguilar CLI and unfortunately there' not a "uniform" answer where it comes from and how to solve that error.

**Comment by krotscheck** [comment] 2018-03-27 16:31
It appears I'm having the same issue. My use case is that I have a library that exports injection tokens, as an alternative to `forRoot` for providing runtime configuration. The consuming application then creates its own `ConfigModule`, whose job it is to provide those injection tokens based on the runtime environment. The exported module contains a static forRoot method as a convenience, however it doesn't seem to be possible to reference the same Injection tokens. They don't show up in the metadata, so I suspect it's the same cause.

Steps to reproduce: 
1. Pull this branch - https://github.com/kangaroo-server/kangaroo-ui/tree/feature/login
2. `yarn install`
3. `yarn build`

Observed error:
```
 | ERROR in @kangaroo/authz-ui/modules/config/module.ts(43,5): Error during template compile of 'ConfigModule'
 |   Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler in 'oauthApiRootProvider'
 |     'oauthApiRootProvider' references 'OAUTH2_API_ROOT' at @kangaroo/authz-ui/modules/config/angular-authn-contracts.ts(39,12)
 |       'OAUTH2_API_ROOT' references 'OAUTH2_API_ROOT'
 |         'OAUTH2_API_ROOT' references 'OAUTH2_API_ROOT'
 |           'OAUTH2_API_ROOT' is not initialized at @kangaroo/@kangaroo/angular-authn/lib/oauth2/contracts.ts(6,22).
```

**Comment by krotscheck** [comment] 2018-03-28 15:59
A bit more insight, and a workaround from #720 as applied to my case: Apaprently the issue is that - for whatever reason - the first entry point must be a direct reference to the barrel file, rather than the directory it lives in. This cascades - so if your `public_api.ts` is a barrel file, which itself imports from directories, the metadata won't be constructed properly.

The workaround for this issue is: Always refer barrel files directly, don't use directory resolution.

**Comment by MattSenter** [comment] 2018-06-04 14:49
This workaround saved my life.

**Closed** 2021-08-20 13:55 UTC
Labels: question
