### ISSUE TITLE
Incremental builds should only build changed files

### ISSUE THREAD

**Issue by tomcek112** [ng-packagr/ng-packagr#1216] opened 2019-02-12 10:33 UTC
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

Hi all, we are using `ng-packagr` to package a medium-sized Angular 7 component library of roughly 30 components and have found that the build times are, despite incremental builds, very slow and costing us a lot of development time. Our library builds usually take over 50 seconds regardless of the size of the change. 

If I understand the source code of `ng-packagr` correctly, the incremental build builds each entry point entirely new when a change is detected. I am suggesting a feature that incremental builds should only build the file(s) that actually changed. This would speed up build times significantly by avoiding building files that did not change. 

I am aware that this feature request is a possible duplicate of #828 and also that @alan-agius4 raised some concerns in that issue but would love to hear your thoughts on whether these concerns still hold or can be worked around.

Thank you for your time and commitment to this project!

#### Version Information

```
ng-packagr: 4.7.0
```

**Comment by alan-agius4** [comment] 2019-02-12 11:55
Hi @tomcek112,

Thanks for reaching out. Do you know which parts of the compilation takes the most time? 

The full entry-point is built upon every file that changes within it. Is because we need to produce various outputs, such as fesm5, fesm2015, umd, es5 and es2015, when ever a single file changes it effects all the mentioned outputs. However, parts of this, or the most time consuming parts which is the ngc compilation and css processing is fully incremental, hence when a file changes, the transpilation happens incrementally and based on cached files and ngc programs.

**Comment by tomcek112** [comment] 2019-02-12 15:06
Hi @alan-agius4, thanks for the reply!

So if I understand you correctly then this feature already exists through caching the compiled files? For us the most time consuming part of the build process is indeed `ngc` compilation, taking ~26s in standard builds and ~15s in incremental ones. However, the sum of the time taken by the bundling steps is also not insignificant as each takes roughly 4s. 

Is there any other way that you know of how we can speed up the `ngc` compilation?

**Comment by alan-agius4** [comment] 2019-02-12 16:32
I have a suspect that when doing the change other files within a tree are
being invalidated.

Can you check if you have the same timings if you change a root file?
Example public_api.ts?

**Comment by tomcek112** [comment] 2019-02-12 17:12
Yeah the timings are the same for `public_api.ts`

**Comment by alan-agius4** [comment] 2019-02-15 17:58
I will try to look into this in the coming days. As i’d need to create a reproduction first.

**Comment by alan-agius4** [comment] 2019-02-21 13:10
@tomcek112 can you provide a some stats about your library? 
Example, how many try https://github.com/Jamaks/ng-app-counter or https://github.com/compodoc/ts-stats

**Comment by alan-agius4** [comment] 2019-02-21 13:52
Can you kindly try if with this fix https://github.com/ng-packagr/ng-packagr/pull/1223 the timings are better?

**Comment by alan-agius4** [comment] 2019-03-24 10:42
Closing as no further feedback provided.

**Closed by alan-agius4** 2019-03-24 10:42 UTC
