### ISSUE TITLE
"'rootDir' is expected to contain all source files."

### ISSUE THREAD

**Issue by TomMettam** [ng-packagr/ng-packagr#2374] opened 2022-07-08 09:04 UTC
```
[X] Bug Report
[ ] Feature Request
```
I have a source tree which contains multiple projects, including multiple Angular libraries packaged with ng-packagr.

The projects all share some common typescript interfaces. These do not belong to any of the libraries and I don't want to have to manage separate copies of these interfaces.

When I build, I get the error "X is not under 'rootDir' 'Y'. 'rootDir' is expected to contain all source files."

#### How To Reproduce

Place some shared code outside of the angular library's root

#### Expected Behaviour

ng-packagr should identify such shared files outside of the rootDir and copy them into the packaged source tree, resolving paths appropriately.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            14.0.3
@angular/compiler:     14.0.5
rollup:                2.75.7
typescript:            4.7.4
```

**Comment by TomMettam** [comment] 2022-07-08 09:26
I should mention: Putting these shared interfaces in a separate package would cause significant maintenance challenges. It should not be required to do that.

**Comment by JoostK** [comment] 2022-07-08 10:36
This is working as expected. Each entry-point is configured with a `rootDir` as it needs to have a well-defined output base, and having files outside of this `rootDir` would not be written within this output base.

You don't need a separate package to support this, you'd just need a separate entry-point that contains these definitions; then import them using an absolute module specifier from other entry-points.

**Comment by TomMettam** [comment] 2022-07-08 10:51
But then the packaged library won't contain those shared files, right?

We need to have a mechanism to copy these into the library at package time.

**Comment by alan-agius4** [comment] 2022-07-10 17:46
Closing as @JoostK explained this is by design.

**Closed by alan-agius4** 2022-07-10 17:46 UTC

**Comment by TomMettam** [comment] 2022-07-13 14:14
Unfortunately the entry-point mechanism is insufficient.. it requires that the additional entry points are beneath the library's tree, i.e  a subfolder of the package.json.

Shared code, as in code which is used by multiple projects, can't be inside a single project's tree.
