### ISSUE TITLE
Issue with running packagr during postinstall hook

### ISSUE THREAD

**Issue by jasonmontalto** [ng-packagr/ng-packagr#667] opened 2018-03-07 01:44 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

This is most likely a user error issue. But am not entirely sure how best to ask the question. So I am positioning it as a bug for now. Feel free to change the type to whatever is best.

Running into an odd issue that I can't unwind after upgrading from 1.6 to 2.2.  I have a private git based library (hosting source code only) that is being loaded into another application via an npm dependency. 

 When I run the packager inside of the common library repo, the packager successfully runs. Creating the artifacts as I would expect.

I also have the library's packages.json file set to run the packager command on the postinstall hook (`"postinstall": "ng-packagr -p ng-package.json"`).  When its run during this phase, I get the following output.

```
Building Angular Package
Building entry point '@curion/common-library'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15

BUILD ERROR
Could not resolve './src/lib/components/button' from .ng_pkg_build/curion-common-library/out/public_api.js
Error: Could not resolve './src/lib/components/button' from .ng_pkg_build/curion-common-library/out/public_api.js
    at error (/Users/jasonmontalto/Projects/curion_platform/ap_cdc_base_pattern_library/node_modules/@curion/common-library/node_modules/rollup/dist/rollup.js:170:15)
    at /Users/jasonmontalto/Projects/curion_platform/ap_cdc_base_pattern_library/node_modules/@curion/common-library/node_modules/rollup/dist/rollup.js:19580:25
    at <anonymous>
```

My public_api file exists in the root directory of the repo and contains the following:
```
export * from './src/lib/components/button';
...
```

In theory, should I be able to run packager in the postinstall hook? Am I missing a configuration that would connect the src code to the workingDirectory during the build?

 I currently do not have a repo that I can use for you guys to test, as this is all proprietary source code. If need be, I can attempt to extract the issue into a couple of repos.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.2.0
@angular/compiler:     5.2.7
@angular/compiler-cli: 5.2.7
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.7.2
```

**Comment by scttcper** [comment] 2018-03-07 04:06
try putting the public_api inside the src folder

**Comment by jasonmontalto** [comment] 2018-03-07 15:08
Hey @scttcper,

Thanks for the feedback. I just switched the library to have the public_api in my src folder. Updated the imports in the public_api so that it looks like:

```
export * from './lib/components/button/index';
...
```

removed my entryFile override in ng-package.json. 

Re-ran my test and am getting basically the same error:
```
> ng-packagr -p ng-package.json

Building Angular Package
Building entry point '@curion/common-library'
Cleaning build directory
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM15

BUILD ERROR
Could not resolve './lib/components/button/index' from .ng_pkg_build/curion-common-library/out/public_api.js
Error: Could not resolve './lib/components/button/index' from .ng_pkg_build/curion-common-library/out/public_api.js
    at error (/Users/jasonmontalto/Projects/curion_platform/ap_cdc_base_pattern_library/node_modules/ng-packagr/node_modules/rollup/dist/rollup.js:170:15)
    at /Users/jasonmontalto/Projects/curion_platform/ap_cdc_base_pattern_library/node_modules/ng-packagr/node_modules/rollup/dist/rollup.js:19580:25
    at <anonymous>
```

If I can get some time today, I will attempt to create a reproducible setup with public repos.

**Comment by jasonmontalto** [comment] 2018-03-10 00:43
Quick update. I am working on getting a reproducible set of repos. I have not been able to reproduce the exact same error, instead the inlining of the stylesheets and templates is failing. As soon as I have it ready to go, I will add the links to this ticket. 

Thanks and have a great weekend!

**Comment by pegpeg** [comment] 2018-05-03 16:39
Hi @jasonmontalto 

I have the same issue.

When I try to build my lib (a dependency of my main project) with a postinstall script, ng-packagr doesn't copy the files of my lib in /dist folder.
So, I have also the error:

```
Building Angular Package
Building entry point 'my-lib-ui'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Downleveling ESM2015 sources through tsc
Bundling to FESM2015

BUILD ERROR
Could not resolve './component-kit/button/button.module' from dist\esm2015\public_api.js
Error: Could not resolve './component-kit/button/button.module' from dist\esm2015\public_api.js
    at error (C:\AA\Workspace\OneLab\main\node_modules\rollup\dist\rollup.js:224:15)
    at C:\AA\Workspace\OneLab\main\node_modules\rollup\dist\rollup.js:19454:25
    at <anonymous>
```

That works well if I build my lib directly.

Did you find a solution?

Thanks!

**Comment by jasonmontalto** [comment] 2018-05-03 20:47
@pegpeg No unfortunately, I was pulled on to a different project and have not been able to loop back. I left it off with the start of a sample app to demonstrate the issue for the ng-packagr team. I was not able to get that completed. 

My team was not able to figure out a work around, so we ended up resorting to hosting a private repo to store our compiled artifacts. We pull from that rather than build during installation.  

I would love to know if you find a solution. If you are able to figure something out, please reply to this post with your findings.

Thanks,
Jason

**Comment by pegpeg** [comment] 2018-05-03 21:05
@jasonmontalto 

I've just noticed that it works with Typescript ~2.5.3 in my case, but not if >2.6.

**Comment by stefano-rainieri** [comment] 2018-05-04 13:57
same issue for me and i confirm what @jasonmontalto say:
- build it directly works with typescript ^2.4.1
- build it in postinstall script works  with typescript ~2.5.3 but not with ~2.6.2

It breaks because some files miss under `.ng_build/` forlder, but i don't understand yet the reason why it works/not works for different typescript versions.

**Comment by zdenekhatak** [comment] 2018-07-16 14:09
Also facing this issue. Downgrading to lower versions of Typescript is not possible since angular 6 requires typescript > 2.7.2.

Has anyone come up with a solution or the only way to install own libraries from private repos is to commit also the tgz file / dist folder?

**Comment by sommcz** [comment] 2018-09-03 11:39
same issue when building my repo in linux container. switching to typescript 2.5.3 works. when i'm building on my windows machine, it works with 2.6.2 without any problems.

**Comment by sommcz** [comment] 2018-09-03 13:55
update: my issue is solved.

The probably reason why my build failed was some error in my sources which was silently ignored on windows machine and with lower typescript version (2.5.3), but on new typescript it fails compilation.

It looks like ng-packagr doesn't show this kind of errors. I found it by calling tsc directly with `./node_modules/.bin/tsc -p src/tsconfig.lib.json` and `./node_modules/.bin/ngc` commands.

**Comment by cen1** [comment] 2018-10-31 17:06
Same issue here but I can't even do a normal build. I forked a lib, added a new file and it simply won't be copied to the dist folder. Could someone shed some light on what part of ng-package is responsible for copying files to dist folder? What exactly determines which folders/files are copied and which are not?

**Comment by mpscheidt** [comment] 2018-11-14 13:52
What I found is that rather than
`export * from "./rest";`

I had to export every type individually in `public_api`:
`export { ThisType, ThatType } from "./rest";`

**Comment by rwoody** [comment] 2019-01-17 17:58
Are other things building at the same time? I think I had a problem like this as well, but I think it's related to building multiple packages at the same time that reference the same `tsconfig.json` outDir...

Could have also been a coincidence that it built correctly after changing this though...

**Comment by cen1** [comment] 2019-01-18 11:13
In my case it was due to the fact that d.ts exported API was not copied. I had to convert the whole .js implementation to angular/typescript class.

**Comment by filipiz** [comment] 2019-02-03 14:41
> In my case it was due to the fact that d.ts exported API was not copied. I had to convert the whole .js implementation to angular/typescript class.

What did you converted in your implementation?

**Comment by Razgort** [comment] 2019-06-06 07:59
Hello guys i'm also having the same issue here :
`Building Angular Package
Building entry point 'shared'
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)
Error: Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)
    at error (F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:3460:30)
    at F:\angular-plugin-architecture\node_modules\rollup\dist\rollup.js:21474:17
    at <anonymous>

Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)
Error: Could not resolve entry (F:\angular-plugin-architecture\dist\shared\esm2015\shared.js)`

Did someone found a fixe for that issue ?

**Comment by kamilchlebek** [comment] 2019-06-06 08:04
Instead of using `postinstall` script, you may try to use `prepare`. 

This made the build passing on the client side, but then I run into some path issues and I've abandoned it for now - so I'm not 100% sure if this is correct approach.

**Comment by KingDarBoja** [comment] 2019-06-14 20:18
Having the same issue with Typescript 3.4.0. The `postinstall` script is not working but building at the source project does.

**Comment by batiyeh-ford** [comment] 2020-02-20 19:25
Having the same issue. Anyone find a fix for this or are we stuck making separate repos for our distribution?

**Comment by sdharagit** [comment] 2020-06-09 07:15
> Rather than
> `export * from "./rest";`
> 
> I had to export every type individually in `public_api`:
> `export { ThisType, ThatType } from "./rest";`

Is this process is working?? Please reply soon .. I'm stuck with the same issue.

**Comment by mpscheidt** [comment] 2020-06-09 13:06
> > Rather than
> > `export * from "./rest";`
> > I had to export every type individually in `public_api`:
> > `export { ThisType, ThatType } from "./rest";`
> 
> Is this process is working?? Please reply soon .. I'm stuck with the same issue.

Yes, at least at the time it was a resolution. If the issue is still the same with more recent Angular version, I cannot say.

**Comment by sdharagit** [comment] 2020-06-10 07:11
Any solution on this issue would be helpful because stuck with the same issue for long time. 
I'm using Angular 5 and  "ng-packagr": "^3.0.6" 
Issue -   The lib is generating dist without any issue when running individually but when trying to generate dist inside of Angular project after adding the package in package,json its giving me  - 
```
Building Angular Package
Building entry point '@infoblox/common-services'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Could not resolve './licensing/licensing.service' from dist\esm2015\public_api.js
Error: Could not resolve './licensing/licensing.service' from dist\esm2015\public_api.js
    at error (D:\MyWorks\Infoblox\csp.root.ui\packages\ufe-nav-menu\node_modules\@infoblox\common-services\node_modules\rollup\dist\rollup.js:199:15)
    at D:\MyWorks\Infoblox\csp.root.ui\packages\ufe-nav-menu\node_modules\@infoblox\common-services\node_modules\rollup\dist\rollup.js:20784:25
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

**Comment by alan-agius4** [comment] 2020-11-12 10:39
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-11-12 10:39 UTC
