### ISSUE TITLE
"Maximum call stack size exceeded" when using a recursive type

### ISSUE THREAD

**Issue by kkoo95** [ng-packagr/ng-packagr#1329] opened 2019-06-28 15:58 UTC
## Type of Issue

```
[X] Bug Report
[ ] Feature Request
```

## Description

Exporting a class which contains a constructor argument with a recursive type gives a `Maximum call stack size exceeded` error. Which is really hard to debug in the middle of a big application.

#### How To Reproduce

Just generate a brand new lib and modify generated service constructor so it includes a parameter with a recursive type:
```typescript
@Injectable()
export class SomeService {
  constructor(public injected: Array<Array<any>>) { }
}
```
The compiler won't even have the opportunity warn about the resolution of this parameter and fail with an overflow.

#### Expected Behaviour

Some clearer message. Anything really. :) A line, a name. You decide !

The __workaround__ is to use a custom type:
```typescript
export type MyType = Array<Array<any>>;

@Injectable()
export class SomeService {
  constructor(public injected: MyType) {
  }
}
```
Now we get the warning about some unresolved type. Which I fix with an `InjectionToken`

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            4.7.1
@angular/compiler:     7.2.15
rollup:                0.67.4
tsickle:               0.35.0
typescript:            3.1.6

```

**Comment by florian-kittel** [comment] 2019-07-04 14:37
Hi @kkoo95,

this issue is related to https://github.com/ng-packagr/ng-packagr/issues/1252 -> the root cause of the problem seem to be the Node Js version. Which version do you use?

**Comment by alan-agius4** [comment] 2019-07-06 19:24
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1252

**Closed by alan-agius4** 2019-07-06 19:24 UTC
