### ISSUE TITLE
ng packagr does not remove devDependencies

### ISSUE THREAD

**Issue by mscudlik** [ng-packagr/ng-packagr#1028] opened 2018-07-30 09:46 UTC
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description

*ng-packagr 4.0.1*

_A bug: please describe the error that you encountered_

- ng-packagr copies devDependencies to the final package.json even though they are not whitelisted.
 - i have angular in peerDependencies and devDependencies
- as a consequence i get an invalid "package" (i.e. npm link will install all those dependencies...)
- building an app with a linked library will not work

- the following error happens, because angular core is now referenced twice
```shell
ERROR in ../@foo/bar/foo-bar.ts(9,2): Error during template compile of 'FoobarModule'

  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'

    'NgModule' calls 'ɵmakeDecorator'.

node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

node_modules/@foo/bar/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

- devDependencies should not be copied by default and only when they are whitelisted

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 4.0.1
@angular/*: 6.1.0
typescript: 2.7.2
rxjs: 6.2.2
node: 8.11.3
```

**Comment by alan-agius4** [comment] 2018-07-30 16:22
While whitelisted semantically you should still need add the actual dependencies to dependencies instead of dependencies. That said, if they are listed as peerDependencies they still need to be listed as dependencies in the application.

Ng-package doesn’t modify the dependencies, peerDependencies and devDependencies within a package.json.

Can you share your package.json?

**Comment by mscud** [comment] 2018-07-31 07:48
I think the root cause of my problem is that npm link will install devDependencies and dependencies 

```shell
node_modules/@foo/bar/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

this leads to a node_module folder and duplicate @angular/core errors.

But even if you leave that aside, i still think that the dependecneis i use belong to the devDependencies.
They are not a dependency of the library itself but only used to develop the library.
And i also think that the devDepenencies must not appear in the final package.json as this makes no sense, so everything else is a workaround.

```json
  "peerDependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "core-js": "^2.5.7",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  },
  "optionalDependencies": {
    "prismjs": "1.15.0",
    "marked": "0.4.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.7.0",
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/platform-server": "^6.0.0",
    "@compodoc/compodoc": "^1.0.5",
    "@types/jasmine": "2.5.41",
    "@types/node": "8.0.51",
    "angular-cli-ghpages": "0.5.2",
    "autoprefixer": "6.6.1",
    "codelyzer": "4.4.2",
    "core-js": "^2.5.7",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.4",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "ncp": "^2.0.0",
    "ng-packagr": "4.0.1",
    "puppeteer": "1.5.0",
    "rimraf": "2.6.2",
    "rxjs": "^6.0.0",
    "rxjs-tslint": "0.1.5",
    "scss-bundle": "^2.3.2",
    "tslint": "5.11.0",
    "typescript": "2.7.2",
    "watch": "^1.0.2",
    "yargs": "6.4.0",
    "zone.js": "^0.8.26"
  },
```

```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "dest": "tmp",
  "lib": {
    "entryFile": "src/lib/index.ts"
  }
}
```

**Comment by mscud** [comment] 2018-07-31 12:49
the path mapping helps to assure that angular versions of the lib (the peerDependencies) and  of the demo application (the dependencies) are the same version. but it does not help to solve the devDependencies issue with npm link

**Comment by alan-agius4** [comment] 2018-07-31 13:07
I will ensure that it picks the root node_modules. Or the peerDependencies.

**Comment by alan-agius4** [comment] 2018-07-31 15:46
It will ensure that it picks the root node_modules, ie the peerDependencies.

 It looks more of a paths issues to me if the devdeps are effecting your final bundle. 

That said, if you don’t want to install devDeps on npm link and you have npm version 5.10+, you can run npm link --only=production

**Comment by CarstenLeue** [comment] 2019-03-11 16:16
@alan-agius4 independent of the discussion how `npm link` works, is there any usecase for including `devDependencies` in a package published to npm?

If not, I would second the request to remove `devDependencies` from the generated `package.json`, automatically (just as `scripts` are removed)

**Comment by restjohn** [comment] 2021-05-12 18:55
How about the use case of depending on type definitions?  For example
```
{
  "devDependencies": {
    "@types/geojson": "... types version ..."
  }
}
```

**Comment by alan-agius4** [comment] 2022-12-21 14:25
Closing as this is not planned.

**Closed by alan-agius4** 2022-12-21 14:25 UTC
Labels: community: need feedback, community: discussion
