### ISSUE TITLE
override rootDir

### ISSUE THREAD

**Issue by qballer** [ng-packagr/ng-packagr#1323] opened 2019-06-19 11:15 UTC
## Type of Issue
```
[ ] Bug Report
[ x] Feature Request
```
## Description
I'm currently implementing an integration with ng-packagr to the [teambit/bit](https://github.com/teambit/bit) in order to provide component support the angular community. In my use case I need to override the rootDir. It looks like you guys [override](https://github.com/ng-packagr/ng-packagr/blob/4421e6fd3b14a6885c831510293b3107d6343846/src/lib/ts/tsconfig.ts#L100) this property and I was wondering if [basePath](https://github.com/ng-packagr/ng-packagr/blob/4421e6fd3b14a6885c831510293b3107d6343846/src/lib/ts/tsconfig.ts#L91) can be default and override in ```ng-package.json```. I need this in order to simulate the original environment the code is written (something bit does create partial components). I see there are other issues on this topic and wonder if you can share more information as to why this is an issue.  
 #### How To Reproduce
N/A
#### Expected Behaviour
allow rootDir in ng-package
#### Version Information
```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            5.3.0
@angular/compiler:     8.0.0
rollup:                1.15.1
tsickle:               
typescript:            3.4.5
```

**Comment by alan-agius4** [comment] 2019-06-19 11:26
Related and duplicate of https://github.com/ng-packagr/ng-packagr/issues/1264

**Closed by alan-agius4** 2019-06-19 11:26 UTC
