### ISSUE TITLE
xlf translation files are ignored by ng-packagr

### ISSUE THREAD

**Issue by zelibobla** [ng-packagr/ng-packagr#748] opened 2018-04-05 08:57 UTC
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Ng5 internationalization is being added into module as proposed in official docs: https://angular.io/guide/i18n
Due to this additional .xlf file appears among the module elements and must be imported in specific way. It works like a charm in module standalone launch, but in the module exported by ng-packagr .xlf file doesn't exist.
It would be nice to get the support of internationalization with ng-packagr

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.2.0
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.5.3
```

**Comment by alan-agius4** [comment] 2021-07-10 22:05
Duplicate of #695

**Closed** 2021-07-10 22:05 UTC
