### ISSUE TITLE
[v1] Missing RX declarations

### ISSUE THREAD

**Issue by CarstenLeue** [ng-packagr/ng-packagr#568] opened 2018-01-30 08:28 UTC
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

the following rx declarations seem to be missing:

"rxjs/add/operator/shareReplay": "Rx.Observable.prototype"
        "rxjs/scheduler/AsyncAction": ?,
        "rxjs/scheduler/AsyncScheduler": ?
        "rxjs/scheduler/queue": ?

**Comment by CarstenLeue** [comment] 2018-01-31 08:48
I noticed that when building my module, the source code of the shareReplay operator was included, unless I explicitly excluded it in the config file. 
I checked the "rollup.globals.ts" file and did not find the declaration in there, so I thought it might be missing in the default config. 
Same for "AsyncAction" and "AsyncScheduler. " "queue" slipped in as a mistake.

**Comment by alan-agius4** [comment] 2018-01-31 08:50
You should be using the `2.0.0-rc` version

**Comment by artaommahe** [comment] 2018-02-02 08:30
Same issue here: using `rxjs/add/operator/shareReplay` results in +80kb of rxjs code in bundles. Cant use v2+ due to lack of ng4 support (and cant upgrade to ng5 due to 2-3x build time slownown)

**Comment by Sibiraj-S** [comment] 2018-09-04 14:10
Fixed in [v2.0.0-rc.8](https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md#200-rc8-2017-12-26)

**Comment by alan-agius4** [comment] 2020-11-11 11:14
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent ng-packagr version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Closed by alan-agius4** 2020-11-11 11:14 UTC
