### ISSUE TITLE
BUILD ERROR EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by degoedke** [ng-packagr/ng-packagr#837] opened 2018-05-04 09:10 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description
I set up 2 new Angular-Projects and set them up EXACTLY like in this tutorial: https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e . Every time i try to run the ng-packagr it fails and then there is the following error:

> npm run forestrun
> 
>  bte@0.0.0 forestrun C:\Users\Kevin.DeGoede\Documents\yoyo\bte
>  ng-packagr -p ng-package.json
> 
> Building Angular Package
> Building entry point 'bte'
> Cleaning build directory
> Rendering Stylesheets
> Rendering Templates
> Compiling TypeScript sources through ngc
> Bundling to FESM15
> Bundling to FESM5
> Bundling to UMD
> Minifying UMD bundle
> Relocating source maps
> Copying staged files
> Writing package metadata
> Distributing npm packages with 'dependencies' is not recommended. Please consider adding @angular/animations to 'peerDependencies' or remove it from 'dependencies'.
> 
> BUILD ERROR
> EPERM: operation not permitted, unlink 'C:\Users\Kevin\Documents\yoyo\bte\dist\src\app\modules'
> Error: EPERM: operation not permitted, unlink 'C:\Users\Kevin\Documents\yoyo\bte\dist\src\app\modules'
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 111
> npm ERR! bte@0.0.0 forestrun: `ng-packagr -p ng-package.json`
> npm ERR! Exit status 111
> npm ERR!
> npm ERR! Failed at the bte@0.0.0 forestrun script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Kevin\AppData\Roaming\npm-cache\_logs\2018-05-04T08_30_30_818Z-debug.log

When trying again the following error will occur: 

>  npm run forestrun
> 
>  bte@0.0.0 forestrun C:\Users\Kevin\Documents\yoyo\bte
>  ng-packagr -p ng-package.json
> 
> Building Angular Package
> glob error { Error: EPERM: operation not permitted, scandir 'C:\Users\Kevin\Documents\yoyo\bte\dist\src\app\modules'
>   errno: -4048,
>   code: 'EPERM',
>   syscall: 'scandir',
>   path: 'C:\\Users\\Kevin\\Documents\\yoyo\\bte\\dist\\src\\app\\modules' }
> 
> BUILD ERROR
> EPERM: operation not permitted, scandir 'C:\Users\Kevin\Documents\yoyo\bte\dist\src\app\modules'
> Error: EPERM: operation not permitted, scandir 'C:\Users\Kevin\Documents\yoyo\bte\dist\src\app\modules'
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 111
> npm ERR! bte@0.0.0 forestrun: `ng-packagr -p ng-package.json`
> npm ERR! Exit status 111
> npm ERR!
> npm ERR! Failed at the bte@0.0.0 forestrun script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Kevin\AppData\Roaming\npm-cache\_logs\2018-05-04T08_54_07_739Z-debug.log

When I try to access the dist/src folder with the system explorer I cant access it since I am not permitted to access it, although being logged in as the user it requests.

#### How To Reproduce

You can follow the tutorial https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e on Windows 10 with the Angular IDE.

I dont know whether there is something wrong with my OS or with the other software I am using. I tried it on another PC with another Windows 10 Build, but the error will still occur there. I also tested the same on a Mac and it worked fine.

#### Expected Behaviour

The behavior I expected was that packing the application works fine, just like on my Mac.

#### Version Information

```
Windows 10 Pro: 1709 Build 16299.371
Angular IDE: 17.0.0.c0000019t201804160508
ng-packagr: 2.4.2
@angular/*: 5.2.10
typescript: 2.5.3
rxjs: 5.5.10
node: 9.4.0
npm: 5.6.0
```

**Comment by macjohnny** [comment] 2018-05-07 13:03
this could be when you are simultaneously running `ng serve` or `ng build`

**Comment by jayoungers** [comment] 2018-06-13 13:31
In case anyone else stumbles upon this for a similar reason:

I started getting this in angular-cli 6 when doing `ng build my-lib --prod`:  I needed to add this to my tsconfig to resolve it:

  "exclude": ["dist"]

**Comment by tobyStaff** [comment] 2018-07-27 11:10
@jayoungers - Im having the exact same issue with Angular CLI 6, when doing `ng build my-lib --prod`. Your tip helped me resolve this - so thank you. 

However do you know why? Is this just covering up an important error or should the error not be shown?

**Comment by markwhitfeld** [comment] 2018-10-09 19:35
I was able to fix this by running the command prompt/bash as admin and closing VSCode!
Seems like VSCode was locking some files.
Potentially something else could be locking these files for you.

**Comment by mpscheidt** [comment] 2018-10-10 05:57
@markwhitfeld In case you've installed the VSCode plugin "Angular Language Service", try to deactivate it. It locks files and prevents ng-packagr from working correctly.

**Comment by sagar-patro** [comment] 2018-11-08 10:51
The error occurred with me when tried with "ng new my-app".
npm version: 6.4.1
I am not even using VSCode.

**Comment by datrinh** [comment] 2018-12-12 14:58
@mpscheidt This worked for me thanks. Is there a way to avoid deactivating the plugin tho?

**Comment by Achilles718611** [comment] 2019-03-29 07:07
I use WebStorm, but still got error.

**Comment by dotnetcanuck** [comment] 2019-06-06 19:29
I'm using VS Code, and I have the Angular Language Service extension installed.

But I didn't have to touch anything with the extension. Simply adding the `dist` exclusion to the `tsconfig.json` file did the trick!

Thanks, @jayoungers!

**Comment by luissanchez0305** [comment] 2019-08-15 21:28
FYI I found another solution to the unlink issue. Im on windows and had to run the terminal as Administrator for ng to be able to manipulate files on dist folder

**Comment by KevinGuancheDarias** [comment] 2019-08-22 16:38
In my case this error was caused by VSCode, closing VSCode allowed me to ng build my library. But @jayoungers solution allows me to run ng build `with VSCode open`

**Comment by alan-agius4** [comment] 2021-07-10 22:01
Closing as this should no longer be an issue.

**Closed by alan-agius4** 2021-07-10 22:01 UTC
