### ISSUE TITLE
"Function calls are not supported in decorators but 'RoutingService' was called" - while ng build --prod

### ISSUE THREAD

**Issue by MalliswariKP** [ng-packagr/ng-packagr#1428] opened 2019-10-22 10:38 UTC
When I am trying to build using 'ng build' it works properly. When I do 'ng build --prod', I end up with below error :

**ERROR in Error during template compile of 'MainRoutingModule'
Function calls are not supported in decorators but 'RoutingService' was called.**

RoutingService is a service used to get path based on Id and getById is a static method.

**main-routing.module.ts**
_import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { MainComponent } from './main.component';
import { AuthService } from './authorization/auth.service';
import { RoutingService } from '../shared/routing/routing.service';
import { DashboardComponent } from '../dashboard/dashboard.component';

const routes: Routes = [
  {
    path: RoutingService.getById('main', 'path'),
    component: MainComponent,
    children: [
      {
        path: '',
        redirectTo: RoutingService.getById('home', 'path'),
        pathMatch: 'full',
        data: {
          breadcrumbItem: {
            ignore: true
          }
        }
      },
      {
        path: RoutingService.getById('home', 'path'),
        component: DashboardComponent,
        data: {
          breadcrumbItem: {
            label: 'home'
          }
        }
      },
      {
        path: RoutingService.getById('dashboard', 'path'),
        redirectTo: RoutingService.getById('home', 'path'),
        pathMatch: 'full',
        data: {
          breadcrumbItem: {
            ignore: true
          }
        }
      },
      {
        path: RoutingService.getById('projects', 'path'),
        canActivate: [AuthService],
        loadChildren: '../project/project.module#ProjectModule'
      },
      {
        path: RoutingService.getById('campaigns', 'path'),
        canActivate: [AuthService],
        loadChildren: '../campaign/campaign.module#CampaignModule'
      },
      {
        path: RoutingService.getById('vehicles', 'path'),
        canActivate: [AuthService],
        loadChildren: '../vehicle/vehicle.module#VehicleModule'
      }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes, {
    // => should load page even if URL has not changed (solves problem that earlier filled input fields stay filled on reload)
    onSameUrlNavigation: 'reload'
  })],
  exports: [RouterModule]
})
export class MainRoutingModule { }_

**Comment by alan-agius4** [comment] 2019-10-28 04:59
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1428

**Closed by alan-agius4** 2019-10-28 04:59 UTC

**Comment by jpmckearin** [comment] 2019-11-12 05:50
> Duplicate of #1428

@alan-agius4 This is #1428.... 

Since all of the issues around this, including this issue itself, are being marked as a duplicate of this dead-end issue, I am going to leave traces here.

The fix -> https://github.com/angular/angular/issues/23609#issuecomment-386876693

The explanation -> https://github.com/ng-packagr/ng-packagr/pull/860

**Comment by alan-agius4** [comment] 2019-11-12 05:57
Sorry. Meant duplicate of https://github.com/ng-packagr/ng-packagr/issues/767
