### ISSUE TITLE
Keeping version numbers in sync in angular library project package.json files

### ISSUE THREAD

**Issue by parky128** [ng-packagr/ng-packagr#1315] opened 2019-06-07 07:37 UTC
When building an Angular Library application, is there an automated way to keep the root level package.json and the library application's package.json (e.g. under `projects/my-library`) file versions in sync when using `npm version` commands?

When I use the command, its only incrementing the root level package.json, is there a special command, or any other way to propagate the version number down to the library package.json file?

I have seen some solutions such as running a script after `ng build` to read the root level package.json version number and write that into the library one. 

Thanks

**Comment by alan-agius4** [comment] 2019-06-07 07:44
Duplicate of https://github.com/angular/angular-cli/issues/14699

You should probably look at https://github.com/semantic-release/semantic-release

**Closed by alan-agius4** 2019-06-07 07:44 UTC

**Comment by parky128** [comment] 2019-06-07 08:23
What about that tool will help me with my problem?

**Comment by alan-agius4** [comment] 2019-06-07 08:34
Yes
