### ISSUE TITLE
Angular 7 UMD format not work after package

### ISSUE THREAD

**Issue by 100cm** [ng-packagr/ng-packagr#1157] opened 2018-12-11 08:35 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

when  i run ng build my_package , the umd.js like this:

```
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core')) :
    typeof define === 'function' && define.amd ? define('dz-plugin-demo-lib', ['exports', '@angular/core'], factory) :
    (factory((global['dz-plugin-demo-lib'] = {}),global.ng.core));
}(this, (function (exports,i0) { 'use strict';
...
```

In angular 7 ,You can't get global.ng.core any more.So if u call window.dz-plugin-demo-lib will return {} empty object

So, How to fix this ?
```
$ node_modules/.bin/ng-packagr --version
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.2
@angular-devkit/build-angular      0.11.2
@angular-devkit/build-ng-packagr   0.11.2
@angular-devkit/build-optimizer    0.11.2
@angular-devkit/build-webpack      0.11.2
@angular-devkit/core               7.1.2
@angular-devkit/schematics         7.0.7
@angular/cli                       7.0.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.2
@schematics/angular                7.0.7
@schematics/update                 0.10.7
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1
```

**Comment by dherges** [comment] 2018-12-12 10:42
Seems to be a bug related to Angular 7.

**Comment by alan-agius4** [comment] 2018-12-17 07:17
Duplicate of 
https://github.com/angular/angular-cli/issues/13205

**Closed by alan-agius4** 2018-12-17 07:17 UTC
Labels: bug
