### ISSUE TITLE
How to wrap external javascript file

### ISSUE THREAD

**Issue by hei-pa** [ng-packagr/ng-packagr#998] opened 2018-07-16 06:07 UTC
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Question
```

## Description

I need to `embed` an external javascript file in my library. I have no ideo how to do that. In the docs there are examples for npm packages but not for plain javascript files.

I tried several ideas with `lib.embedded` or `lib.externals` without luck.

This is my project structure:

```
src
├── lib
│   ├── janus-api.js
│   └── janus-web-rtc-subject.ts
```

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "dest": "dist",
  "lib": {
    "externals": {
      "./src/lib/janus-api.js": "Janus"
    },
    "entryFile": "public_api.ts"
  },
  "whitelistedNonPeerDependencies": ["."]
}
```

Now the `janus-web-rtc-subject.ts` file imports the `janus-api.js` and uses some functions.
The code looks ok but ng-packagr failes to bundle that structure.

```
import Janus from './janus-api.js';
import {Observable, Subject} from 'rxjs';

export class JanusWebRtcSubject {
...
```

And the error is

```
BUILD ERROR
Could not resolve './janus-api.js' from dist\esm2015\src\lib\janus-web-rtc-subject.js
Error: Could not resolve './janus-api.js' from dist\esm2015\src\lib\janus-web-rtc-subject.js

```

#### Expected Behaviour

Bundle the `janus-api.js` in the lib via `externals` or `embedded`.

#### Version Information

```
ng-packagr: 3.0.3
@angular/compiler: 6.0.7
rollup: 0.59.4
tsickle: 0.29.0
typescript: 2.7.2
rxjs: 6.2.1
node: v8.11.1
npm: 6.1.0
```

**Comment by alan-agius4** [comment] 2018-07-16 16:46
Duplicate of https://github.com/dherges/ng-packagr/issues/650

**Comment by rfvanbuskirk** [comment] 2018-08-17 18:32
I have an external JavaScript (part of a separate server), that I’m trying to display on an html page. 

On my page I have the following:

<script src="https://www.vitalsite.net/Rendering/render.ashx?id=DF5EB335-72D8-4FCD-9BF2-24D5A1DE28BE" type="text/javascript">// <![CDATA[

// ]]></script>

That script src has the following on that site:

document.write('<p class="ERWTRow"><span class="LocationName"><a href=http://www.capecodhealth.org/locations/cape-cod-hospital/>Cape Cod Hospital ER</a></span><span class="Time">35 mins</span><span class="Date">&#40;as of 2:00 PM on 8/17/2018&#41;</span></p>');

With the current script on my page, it displays:

Cape Cod Hospital35 mins(as of 2:00PM on 8/17/2018)

I’ll refer to this as the “externalJSstring”

What I would like to do is refer to this script to show the following information:

Cape Cod Hospital
//! Span class = “Locationname” ... getting this isn’t even necessary as I may put it as a heading or <p> field. 

I’d like to then display the following information from the external JavaScript. 

35 mins
//! Span class = “Time”
//! Other option is the “externalJSstring”.splice or sub string?

(as of 2:00PM on 8/17/2018)
//! Span class = “Date”
//! Other option is the “externalJSstring”.splice or sub string?

I’ve tried using AJAX or DOM or even  “substring” expression to splice the necessary characters (Time, Date). But no luck.  

Thank you.

**Closed** 2018-08-29 04:11 UTC
