### ISSUE TITLE
[Angular 5] `ng build --prod` gives error […] add a @NgModule annotation

### ISSUE THREAD

**Issue by so-dinesh-rawat** [ng-packagr/ng-packagr#892] opened 2018-05-21 09:00 UTC
## Type of Issue
```
[x] Bug Report
[ ] Feature Request
```

## Description

I want to use 3 level scope in my project like `@once/ui/datepicker` or `@once/ui/dropdown`. So I started using ng-packagr; which is working fine for me. I am able to use 3-level scope in my project. 

I am using @once/ui shared library in a project. The command `ng serve` works fine for me and everything works as expected. 

Unfortunately, in the project using @once/ui components, `ng build -prod` doesn't work anymore. I've also tried adding the `--preserve-symlinks` argument. but no luck!

#### How To Reproduce

Install `@once/ui/datepicker` in your project and run `ng build --prod`, now the error is reproduced.
Also adding small code snippet here:

```
import { DatepickerModule } from '@once/ui/datepicker';
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    DatepickerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})

export class AppModule { }
```

Now run: 

`ng build --prod`

You will get:-

`ERROR in : Unexpected value 'DatepickerModule in /install-pack/node_modules/@once/ui/datepicker/src/datepicker.module.d.ts' imported by the module 'AppModule in /install-pack/src/app/app.module.ts'. Please add a @NgModule annotation.`

However, if I set `--aot` to false using:-

`
ng build --prod --aot false`

Everything works and the build is successfull!

#### Expected Behaviour

ng build -prod should produce compiled minified distribution files like it did with Angular 4.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 2.4.5
@angular/*: 5.2.10
typescript: 2.5.3
node: 9.10.1
npm: 6.0.0```

**Comment by namlard** [comment] 2018-05-23 09:08
Hi,

Is there a way to see the code of your modules, or the project ?

**Comment by elclanrs** [comment] 2018-05-26 15:38
I've seen this error multiple times and in my case it always comes down to using barrel files. So I'd look in your code and see if you have any barrel imports and change it to import from `index` explicitly

```
// bad
import { foo } from './baz';

// good
import { foo } from './baz/index';
```

I wish there was better support for barrels because our project is huge and it took a while to change all the imports. Although changing them back when barrels are better supported is an easier search-and-replace.

**Comment by so-dinesh-rawat** [comment] 2018-05-29 05:02
@elclanrs 
My barrel file is same as you have mentioned.

export * from './lib/drop-down/index';
export * from './lib/datepicker/index';
export * from './lib/dialog/index';

**Comment by so-dinesh-rawat** [comment] 2018-05-29 05:04
@elclanrs 
I wanted to use 3 level of naming like:-

import { DropDownModule } from '@once/ui/dropdown';

But if I run ng build --prod the build command fails

But if i change this to import { DropDownModule } from '@once/ui';

Everything works!

**Comment by alan-agius4** [comment] 2018-06-15 10:09
Duplicate of #917?

**Comment by nikhiltech0722** [comment] 2018-06-29 10:32
Is their any solution to this?

**Comment by mpicard** [comment] 2018-07-11 14:25
I'm also seeing this in Angular 5.2.x. I'm using the compiler to compileModuleAsync the UMD bundle. I have an example here:

```
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core'), require('@angular/forms'), require('@angular/common')) :
    typeof define === 'function' && define.amd ? define('titan-test-widget', ['exports', '@angular/core', '@angular/forms', '@angular/common'], factory) :
    (factory((global['titan-test-widget'] = {}),global.ng.core,global.ng.forms,global.ng.common));
}(this, (function (exports,core,forms,common) { 'use strict';

    /**
     * @fileoverview added by tsickle
     * @suppress {checkTypes,extraRequire,uselessCode} checked by tsc
     */
    var TestComponent = (function () {
        function TestComponent() {
        }
        TestComponent.decorators = [
            { type: core.Component, args: [{
                        selector: 'app-test',
                        template: "<p>\n  test works!\n</p>\n",
                        styles: ["p{font-size:3rem;color:red}"]
                    },] },
        ];
        return TestComponent;
    }());

    /**
     * @fileoverview added by tsickle
     * @suppress {checkTypes,extraRequire,uselessCode} checked by tsc
     */
    /** @type {?} */
    var providerValue = TestComponent;
    var LibModule = (function () {
        function LibModule() {
        }
        LibModule.decorators = [
            { type: core.NgModule, args: [{
                        imports: [common.CommonModule, forms.FormsModule],
                        declarations: [TestComponent],
                        entryComponents: [TestComponent],
                        exports: [TestComponent],
                        providers: [{ provide: 'Entry', useValue: providerValue }]
                    },] },
        ];
        return LibModule;
    }());

    /**
     * @fileoverview added by tsickle
     * @suppress {checkTypes,extraRequire,uselessCode} checked by tsc
     */

    /**
     * @fileoverview added by tsickle
     * @suppress {checkTypes,extraRequire,uselessCode} checked by tsc
     */

    exports.providerValue = providerValue;
    exports.LibModule = LibModule;
    exports.TestComponent = TestComponent;

    Object.defineProperty(exports, '__esModule', { value: true });
})));
```

Seems to me the output looks correct. However upon compilation (with AOT enabled) it can't figure out what CommonModule and FormsModule are because they get named into random two letter functions. When I turn AOT off, it works.

**Comment by yogen-darji-hs** [comment] 2018-09-18 12:18
Hi @mpicard , Did you find any work around. I am facing similar problem.

**Comment by so-dinesh-rawat** [comment] 2018-09-18 13:56
no @yogen-darji-hs Now we are using two-level scoping and we have moved to angular 6 using libraries now.

**Comment by frankyaorenjie** [comment] 2019-06-04 09:54
May I ask is there any update here? We also encountered this issue in Angular7.

**Comment by atalantus** [comment] 2019-12-17 16:26
Bump. Still there in Angular 8.2...

**Comment by rocifier** [comment] 2020-02-04 03:54
I just tried to create a new library with angular 8.2 and when I import it into my blank project's module via the dist folder or the src folder, and build my project, I get the same type of error. I create a separate workspace for the library than my project, but was careful to match typescript and angular/angular cli versions. Does this mean angular libraries are broken out of the box?

`ERROR in : Unexpected value 'UoaControlsModule in C:/Repos/uoa-common/projects/uoa-controls/src/lib/uoa-controls.module.ts' imported by the module 'AppModule in C:/Repos/one-page-app/src/app/app.module.ts'. Please add a @NgModule annotation.`

**Comment by diminutivesloop** [comment] 2020-10-05 15:20
I get this error in an Angular 9.1.12 project that is importing a library also built with Angular 9.1.12. Weirdly it only occurs when I disable Ivy.

**Comment by SchnWalter** [comment] 2020-10-05 15:52
@diminutivesloop, can you please provide a minimal reproduction repository? Otherwise I would close this issues as obsolete. It was first reported on Angular v5 and from what I can tell, people talk about a few different root causes for this type of error and should be reported in separate issues.

P.S. AFAIK barrel files work just fine in recent versions (that are still supported) and probably that the issues that @so-dinesh-rawat reported no longer exist.

**Comment by JoostK** [comment] 2020-10-05 15:55
@diminutivesloop A common cause is having multiple versions of Angular, or e.g. symlinks into other `node_modules` trees such that a secondary instance of `@angular/core` is brought in from that parallel `node_modules` tree.

@SchnWalter Thank you for responding to these requests!!

**Comment by diminutivesloop** [comment] 2020-10-05 21:17
@JoostK @SchnWalter So this issue actually went away when I explicitly disabled Ivy for my library project. Based on the [Angular Ivy Docs](https://angular.io/guide/ivy#maintaining-library-compatibility) I thought Ivy was already disabled by default for ng-packagr projects.

**Closed** 2020-11-11 13:49 UTC
