### ISSUE TITLE
Is it possible for the Second Entry point to refer the files in other second entry point

### ISSUE THREAD

**Issue by FahadRS** [ng-packagr/ng-packagr#1820] opened 2020-12-26 19:13 UTC
Hello every one i am building a library which contains serveral different sub libraries (secondry entry points) following is my strtucture for the library

ng-core   // primary entry poiint
      ng-core/services     // first entry point
      ng-core/models      // second entry point

now in my first entry point i mean ng-core/services i wanted to access the file in from the second entry point ng-core/models but when i run the build command i am getting the following error

 error TS6059: File 'C:/Users/Fahad/Documents/Angular/libraries-workspace/projects/ng-core/src/models/Mashup.ngtypecheck.ts' is not under 'rootDir' 'C:\Users\Fahad\Documents\Angular\libraries-workspace\projects\ng-core\src\services'. 'rootDir' is expected to contain all source files.

so my question is that it is possible to access the files between two sub entry points 

Plus i did some research on other repositories on the github i was able to know there are some libraries which are using the exact same artchitecture like here in this https://github.com/valor-software/ngx-bootstrap/blob/development/src/accordion/accordion.module.ts 

`import { CollapseModule } from 'ngx-bootstrap/collapse';`

ngx-collapse module is used in the second entry point
     
Here is the link for the sample repository https://github.com/FahadRS/libraries-workspace

**Comment by jiriKralovec** [comment] 2021-01-04 08:18
Having the same issue. Currently we are working with barrel files to work around the issue, but it is not really optimal. I would like to know if there is a solution to this.

**Comment by SchnWalter** [comment] 2021-01-18 17:55
The whole idea of `ng-packagr` is to package libraries in the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview) and from what I can tell, what you are trying to do isn't really compatible with APF.

> The general rule in the Angular Package Format is to produce a FESM file for the smallest set of logically connected code

If you start importing between entry points using relative imports and not using the entry point names, the `BuildGraph` can no longer be created, I would suggest that you stick to relative imports inside entry points and named imports when importing between them.


--- 

Duplicate of #1759

**Comment by alan-agius4** [comment] 2021-01-31 10:32
To reference files between entry- 
points, use the entrypoint module specifier instead of the related path.

Ex:
```ts
import { foo } from `my-lib`;
import { bar } from `@my-lib/secondary`

```

**Closed by alan-agius4** 2021-01-31 10:32 UTC
