### ISSUE TITLE
v17.1.1 Breaks Angular Packages Containing SCSS

### ISSUE THREAD

**Issue by logancooper-tylertech** [ng-packagr/ng-packagr#2772] opened 2024-01-23 20:34 UTC
## Type of Issue

```
[ X ] Bug Report
[ ] Feature Request
```

## Description

_A bug: please describe the error that you encountered_

After updating from v17.1.0 to v17.1.1, building angular libraries/packages that contain components using SCSS files, where those SCSS files contain imports (using the `@import` syntax) of other SCSS files no longer works, and instead throws an error: `No loader is configured for ".scss" files`. Reverting back to v17.1.0 causes the problem to no longer occur, confirming it is a problem introduced in v17.1.1.

#### How To Reproduce

_A bug: please include instructions how to reproduce. Issues without reproduction are likely to receive no feedback._

1) Create a new angular project that will be built as a library, and create a test component within the library
2) Use SCSS for styling components within the library, including the `@import` syntax to import other SCSS files from elsewhere within the library
3) Attempt to build the library, using ng-packagr to package everything

#### Expected Behaviour

_A bug: please describe what behaviour or result you expected_

The package/library should build correctly, similarly to how it did in 17.1.0 and earlier versions. SCSS files should not result in the package failing to build.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 17.1.1
@angular/*: ~17.1.0
typescript: ~5.3.0
rxjs: ~7.8.0
node: 20.10.0
npm/yarn: npm 10.3.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by alan-agius4** [comment] 2024-01-24 13:03
Hi @logancooper-tylertech, I am unable to replicate this. Kindly provide a minimal reproduction. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment] 2024-02-01 10:30
Closing due to a lack of a reproduction. If the problem persists please provide a minimal reproduction.

**Closed by alan-agius4** 2024-02-01 10:30 UTC
Labels: needs reproduction
