### ISSUE TITLE
Feat: specify package.json path

### ISSUE THREAD

**Issue by Badisi** [ng-packagr/ng-packagr#2028] opened 2021-07-16 21:11 UTC
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Considering the following :
- a library with secondary entry points
- some schematics

In order to import the secondary entry points as follow :
```ts
import { A } from 'my-lib/entry-point-a';
import { B } from 'my-lib/entry-point-b';
```
one should scaffold its library project like this :
```
my-lib/
├── projects/
│   ├── library/
│   │   ├── entry-point-a/
│   │   │   ├── ng-package.json
│   │   │   └── public-api.ts
│   │   ├── entry-point-b/
│   │   │   ├── ng-package.json
│   │   │   └── public-api.ts
│   │   ├── ng-package.json
│   │   ├── package.json
│   │   └── public-api.ts
│   └── schematics/
│   │   └── ...
└── package.json
```

#### Pros

The main `ng-package.json` will automatically generate the secondary entry points based on its relative location.
```
dist/my-lib/
├── entry-point-a/
└── entry-point-b/
```

#### Cons

What I dislike with this approach is that I have to manage 2 `package.json` files.
- it's easy to forget about the nested one or mix the two (especially when upgrading the version number)
- they both have data that should be kept in sync
- things like `img.shields.io` or `bots` use the one at the root of the project (which leads to unnoticed outdated dependencies in the real library)

I tried keeping only the `package.json` at the root of the project and moving the main `ng-package.json` file alongside with it but this results in the following :
```
dist/my-lib/projects/library/
├── entry-point-a/
└── entry-point-b/
```
which breaks the secondary entry points imports.

#### Proposal

It would be great if we could specify the path of the `package.json` file in the main `ng-package.json` file.
```json
{
    "lib": {
       "packageJsonFile": "../../package.json"
    }
}
```
That way we could keep only the `package.json` at the root of the project and have only that one to be managed.

#### Version Information

```
ng-packagr: 12.1.0
@angular/*: 12.1.2
typescript: 4.3.5
node: 14.17.0
npm: 7.19.1
```

**Comment by alan-agius4** [comment] 2021-07-19 05:33
The nested package.json **must not** contain any dependencies. Dependencies in the nested package.json are completely ignored.  The nested package manifest exists to enable correct module resolutions. It is very unlikely that you will ever need to update any of the sub-entry points `package.json`.

**Comment by Badisi** [comment] 2021-07-19 08:55
I understand your point but in my case I'm trying to bundle a single package with both my lib and its schematics, and schematics **requires** dependencies.

Let me try to explain my reasoning :

**Assumption** : `package.json` should be alongside `ng-package.json`
```
my-lib/
├── projects/
│   ├── library/
│   │   └── ng-package.json -> package.json not found
│   └── schematics/
│   │   └── ...
└── package.json
```

**Attempt A** : both `package.json` and `ng-package.json` in the library folder
 > This solution is not viable as it's missing the schematic's dependencies in the final package.json
```
my-lib/
├── projects/
│   ├── library/
│   │   ├── ng-package.json
│   │   └── package.json -> will be bundled in dist
│   └── schematics/
│   │   └── ...
└── package.json -> schematic's deps will never be bundled
```

**Attempt B** : both `package.json` and `ng-package.json` at the root of the project
 > This solution is working fine for a single entry point
```
my-lib/
├── projects/
│   ├── library/
│   │   └── ...
│   └── schematics/
│   │   └── ...
├── ng-package.json -> entryFile: './projects/library/public-api.ts'
└── package.json
```
 > But is breaking when using a secondary entry point
```
my-lib/
├── projects/
│   ├── library/
│   │   └── secondary-entry-point/
│   │   │   └── ng-package.json
│   └── schematics/
│   │   └── ...
├── ng-package.json -> entryFile: './projects/library/public-api.ts'
└── package.json

Results in : `dist/my-lib/projects/library/secondary-entry-point`
Which breaks : `import { ... } from 'my-lib/secondary-entry-point`
```

---- 
Now that I'm writing it, it looks like it is more related to an issue than a missing feature.

In attempt B, the `secondary-entry-point` module resolution should be resolved from the `entryFile` path in the main `ng-package.json` not from the main `ng-package.json` location itself.

**Comment by alan-agius4** [comment] 2021-07-19 09:48
It appears that you are incorrectly setting up the directory structure, and in this case above failures are actually expected.

With the below structure you have 2 seperate libraries `@mylib/library` and `@mylib/schematics`, 

```
my-lib/
├── projects/
│   ├── library/
│   │   └── secondary-entry-point/
│   │   │   └── ng-package.json
│   └── schematics/
│   │   └── ...
```

Both `package.json` and `ng-package.json` should be along side the entrypoints and I think the structure that you are looking for is more along
```
my-lib/                               // This is your workspace (Monorepo)
├── projects/                         // This is directory which contains all the libraries
│   └── library/                      // This is the root of your library
│     └── schematics/                 // This is your secondary entry-point
│     │   └── ng-package.json
│     └── secondary-entry-point/      // This is another secondary entry-point
│     │   └── ng-package.json
├───── ng-package.json                // entryFile: './projects/library/public-api.ts'
└───── package.json                   // Manifest of the library, deps of all entry-points, including schematics. 
```

**Comment by Badisi** [comment] 2021-07-19 10:20
But if I follow you correctly, `schematics` as a `secondary entry-point` will be built the same way as the library (ie. `es2020` modules while they should be `commonjs` modules).

But maybe you are right and I'm taking things incorrectly..

My goal is to deliver a **single package** containing both the library and the schematics.
Something like `@angular/material` does :
```
@angular/material/
├── button/
├── schematics/
├── ...
```
That's why I set up the directory structure as if it was 2 separate librairies.
- library is built into `dist/my-lib/` using `ng build` 
- schematics is built into `dist/my-lib/` using `tsc`

Only issue is how to manage the `package.json` (like where to put it and how to avoid duplicating it).

**Comment by alan-agius4** [comment] 2021-07-19 10:28
In that case you can use the same structure that I mentioned above and omit `package.json` and `ng-package.json` from the `schematics` secondary entry-point, and build it manally using tsc

Material example below;

```
angular/                              // This is your workspace (Monorepo)
├── projects/                         // This is directory which contains all the libraries
│   └── material/                     // This is the root of your library
│     └── schematics/                 
│     └── card/                       // This is another secondary entry-point
│     │   └── ng-package.json
│     └── button/                     // This is another secondary entry-point
│         └── ng-package.json
├───── ng-package.json                // entryFile: './projects/library/public-api.ts'
└───── package.json                   // Manifest of the library, deps of all entry-points, including schematics. 
```

**Comment by Badisi** [comment] 2021-07-19 12:23
Absolutely agreed and it is mostly like my attempt B.

Except there is an issue with this structure.
The generated dist will be :
```
dist/my-lib/
└── projects/
    └── library/
        │── card/
        └── button/
```
instead of
```
dist/my-lib/
│── card/
└── button/
```
which implies `import * from 'my-lib/projects/library/button'` instead of `import * from 'my-lib/button'`.

That's why to me it looks like an issue with the secondary entry-point module resolution.
It should be resolved from the `entryFile` specified in the main `ng-package.json` and not from the `ng-package.json` location itself.

**Comment by alan-agius4** [comment] 2021-07-19 12:32
It will not generate `dist/my-lib/projects/`. This happens if you have `ng-package.json` under your `projects` or your entryFile is not configured properly. 

NB: the `entryFile` should be a relative from the `ng-package.json` configuration.

**Comment by Badisi** [comment] 2021-07-19 12:55
I have built a simple project to illustrate the issue : [my-lib.zip](https://github.com/ng-packagr/ng-packagr/files/6840990/my-lib.zip)

Can you spot something wrong in the following structure ?

<img width="427" alt="Screenshot 2021-07-19 at 14 45 31" src="https://user-images.githubusercontent.com/674862/126162202-e1d03c2c-1d0d-4e5e-8b7f-488beb9ad4a7.png">

And btw, thanks a lot for your time and your help. Really appreciates 😉

**Comment by alan-agius4** [comment] 2021-07-19 13:02
The problem is ng-package.json in the root, by adding that you are configuring a library at that level, ie “projects” is your main entrypoint.

This file should be moved under the “library” directory.

**Comment by alan-agius4** [comment] 2021-07-19 13:04
You will only need to create a package.json in the library folder.

The root level package.json is reserved for the dependencies needed to get build and tests all the projects within your mono repo.

**Comment by Badisi** [comment] 2021-07-19 14:06
Ok then but if I'm adding `schematics` to the game, I should specify their dependencies in both the `package.json` at the root (so I can build them and test them) and the `package.json` in the library folder (to make sure the deps gets to the final `package.json` in the dist). Right ?

**Comment by alan-agius4** [comment] 2021-07-19 15:23
That is correct. In the root these should be listed as devDependencies while in the library package.json these should be listed as direct dependencies.

**Comment by Badisi** [comment] 2021-07-19 17:00
This is exactly what's driving me nuts.
Having to manage 2 `package.json` at 2 different places but serving the same purpose.
I often forgot about the one or the other and I end up desynchronised between what I'm testing and what will be published.
I don't know if there is good practices I should follow here..

-----

One last thing I'm curious about:
 > The problem is ng-package.json in the root, by adding that you are configuring a library at that level, ie “projects” is your main entrypoint.

Then why is it working with a single entry-point library, like the following ?

<img width="423" alt="Screenshot 2021-07-19 at 18 17 31" src="https://user-images.githubusercontent.com/674862/126194963-8aa42b63-932d-4f8d-9087-986ccc5aed04.png">

It's only when I add an `ng-package.json` to `/card` and `/button` folders (to make them secondary entry-points) that the dist is messed up with a `projects` folder.
It doesn't feel consistent and sounds more like a bug don't you think ?

**Comment by alan-agius4** [comment] 2021-07-19 17:52
> Having to manage 2 package.json at 2 different places but serving the same purpose.
> I often forgot about the one or the other and I end up desynchronised between what I'm testing and what will be published. I don't know if there is good practices I should follow here..

They serve different purposes, I think in your case you should move away from a multi project setup to a single project setup.

You can use bots to manage dependencies such as Renovate Bot.


> Then why is it working with a single entry-point library, like the following ?

This is probably because the `project` option in angular.json is set to the ng-packagr configuration inside the project directory.

Note, ng-packagr will output the structure as defined in the source tree. IE: if you defined a `project` inside the library, which is defined by using `ng-package.json` it will not remove it.

**Comment by Badisi** [comment] 2021-07-19 19:19
> This is probably because the project option in angular.json is set to the ng-packagr configuration inside the project directory.

In both example the `project` property in the `angular.json` was set to the `ng-package.json` at the root of the project.

-----

Based on your recommandation I moved away from a multi project setup and made a single project structure: [my-lib.zip](https://github.com/ng-packagr/ng-packagr/files/6843251/my-lib.zip)


But I'm still seeing the same issue : 

**Single entry-point** 

<img width="537" alt="Screenshot 2021-07-19 at 20 35 32" src="https://user-images.githubusercontent.com/674862/126214490-e1c248b8-f405-45de-8674-1307099b1980.png">

**Updating the same project to use secondary entry-points**

 > Same structure as above, I just changed the export in `src/index.ts` and added 2 `ng-package.json` in both `card` and `button` folders to make them secondary entry-points.

<img width="537" alt="Screenshot 2021-07-19 at 20 29 21" src="https://user-images.githubusercontent.com/674862/126214511-79b877ec-9f6a-48ca-ba4a-a340773dcb90.png">

**Comment by alan-agius4** [comment] 2021-07-20 05:00
In the above case, you have 2 scenarios, the first is a library without any secondary entrypoints,. In this case, the `button` directory, is a feature directory. while the second you have a library with secondary entrypoints, and hence why the output is different. 

Avoid placing your secondary entry-points under the `src` directory of the primary entrypoints, https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md

Closing since, there is no bug here and it is working as expected.

**Closed by alan-agius4** 2021-07-20 05:00 UTC
