### ISSUE TITLE
warn for missing dependencies

### ISSUE THREAD

**Issue by diminutivesloop** [ng-packagr/ng-packagr#1858] opened 2021-02-05 13:55 UTC
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
With unbundled dependencies library projects must list their dependencies both in the root `package.json` and in `project/<project-name>/package.json` as either regular dependencies or peerDependencies. However if a dependency is only listed in the root `package.json` the library will build without error and the issue will only manifest when the library is included in another project which is likely after the library has already been published.

#### Expected Behaviour
When building a library project ng-packagr should error or warn when it detects an import that can't be matched to a project file or an entry in `project/<project-name>/package.json`.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 9.1.5
@angular/*: 9.1.13
typescript: 3.8.3
rxjs: 6.6.3
node: 12.20.1
npm/yarn: 6.14.10
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by SchnWalter** [comment] 2021-02-08 05:49
I was able to reproduce this issue with the latest version. If the module is installed in the workspace (and types exist), then the library built successfully because the compilers look into the closest `node_modules` directory for resolving module names. The build also works with modules installed in the workspace using `--no-save` param.

The `cacheCompilerHost` will probably need to have a special behavior for resolving module names (`PackageNode.cache.moduleResolutionCache`) or `analyseEntryPoint` should be updated to check against the explicit dependencies of the current package.

In the meantime, you might be able to configure some lint rules to guard against this:
* TSLint: [no-implicit-dependencies](https://palantir.github.io/tslint/rules/no-implicit-dependencies/)
* ESLint: [no-extraneous-import](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-extraneous-import.md)

**Comment by alan-agius4** [comment] 2021-02-08 10:56
I think since this functionality is already provided by packages in the toolchain, such as ESLint and TSLInt, we shouldn't re-invent the wheel.

Let's reconsider this in the future if we see that is a greater demand for this.

**Comment by SchnWalter** [comment] 2021-02-08 22:00
I've ran some tests on a project with `eslint`, `@angular-eslint/*` and `eslint-plugin-node` and I saw that we have the necessary rules for avoiding the issue presented here.

These are the rules that need to be enabled:

* `node/no-missing-import` - it will complain when the dependency is not present in the root `package.json`.
* `node/no-extraneous-import` - it will complain when the dependency present in the root `package.json`, but it's missing from the library `package.json` file.

And these rules don't require any configuration, they work out of the box.

@alan-agius4, you are right, we should probably not handle this in `ng-packagr`, it's just extra code that will need to be maintained. But instead of closing the issue, we could postpone it until `@angular/cli` switches to ESLint, then we could update the library schematic to enable these rules.

**Comment by alan-agius4** [comment] 2021-02-12 11:18
This seems to be more of a feature for https://github.com/angular-eslint/angular-eslint since this is where the schematics of Eslint are found.

The Angular CLI will not add ESLint by default, but it will be up to the user to choose which linting solution to use.

**Closed by alan-agius4** 2021-02-12 11:18 UTC
