### ISSUE TITLE
Angular library build error with enableIvy=false

### ISSUE THREAD

**Issue by yinshuxun** [ng-packagr/ng-packagr#2045] opened 2021-08-12 13:47 UTC
## Type of Issue

```
[x ] Bug Report
[ ] Feature Request
```

## Description

![image](https://user-images.githubusercontent.com/18656086/129206601-d413be4f-0070-4e3f-89e1-2af9d3b85aca.png)

In my project ,  I set up "enableIvy": false would be  error.
If I replacing "enableIvy": false with "compilationMode": "partial" , it can work normally, but I don't know why

#### How To Reproduce

my test project: https://github.com/yinshuxun/test-ngpackager
```
git clone https://github.com/yinshuxun/test-ngpackager.git
yarn 
yarn build
```

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            12.2.0
@angular/compiler:     12.2.1
rollup:                2.56.2
typescript:            4.3.5
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by JounQin** [comment] 2021-08-12 13:58
The problem is related to `@alauda/common-snippet@v3`, what means if the older versions can be used and built correctly. But `@alauda/common-snippet` itself is also built by `ng-packagr` with its default configuration(`enableIvy: false`) without no error.

**Comment by SchnWalter** [comment] 2021-08-13 12:19
You should provide a minimum reproduction repo and not have a ton of dependencies.

**Comment by JounQin** [comment] 2021-08-13 15:21
> You should provide a minimum reproduction repo and not have a ton of dependencies.

Some deps are just peer dep of `@alauda/common-snippet`.

And if you check https://github.com/yinshuxun/test-ngpackager/blob/main/projects/my-lib/src/public-api.ts, you will find the source code is just minimum.

**Comment by yinshuxun** [comment] 2021-08-13 16:40
@SchnWalter I have simplified this project and now execute ```yarn build``` or ```ng-packagr -c projects/my-lib/tsconfig.lib.prod.json -p projects/my-lib/ng-package.json``` can reproduce this problem

**Comment by SchnWalter** [comment] 2021-08-20 14:20
@yinshuxun, that is not a reproduction, you are only re-exporting a closed source library.

And that one has quite a few dependencies, some of which are Angular libraries. You should add a 2nd **minimal** example library that can trigger the same issue when being re-exported, otherwise we can't really help you with anything. We need to see the full code and you should work on providing a **minimal** reproduction, we can't and won't review tens of libraries for you.

**Comment by JounQin** [comment] 2021-08-20 14:30
`@alauda/common-snippet` is bundled by `ng-packagr` too, and can be simple viewed at [unpkg](https://unpkg.com/browse/@alauda/common-snippet@3.1.13/)

There is no problem when bundling `@alauda/common-snippet` itself with same tsconfig or `ng-packagr`'s default tsconfig. So the reproduction can only be made as such.

If we can reproduce this issue without `@alauda/common-snippet`, then that means we should have already determined what is happening. So your requirement is unacceptable IMO.

**Comment by SchnWalter** [comment] 2021-08-20 14:33
I'm sorry to disappoint, but with that attitude you won't find volunteers jumping to help. Good luck!

P.S. The published npm package doesn't contain a link to that source code.

**Comment by JounQin** [comment] 2021-08-20 14:52
That's our internal package, so the whole source code can not be provided.

That's OK you won't help, let's wait for other active maintainers.

Besides, we've already found a workaround by a custom tsconfig like following as Angular [document](https://angular.io/guide/angular-compiler-options#compilationmode).

```jsonc
{
  "angularCompilerOptions": {
    "enableIvy": true,
    "compilationMode": "partial",
    "strictMetadataEmit": false
  }
}
```

**Comment by SchnWalter** [comment] 2021-08-20 16:28
Since enabling Ivy fixed your issue and https://github.com/ng-packagr/ng-packagr/pull/2051 being merged about 3h ago, I think that this issue can be closed. The next release of Angular won't support non-Ivy builds.

**Comment by JounQin** [comment] 2021-08-20 16:59
Yeah, but it's for Angular@13 only.

cc @alan-agius4

**Comment by alan-agius4** [comment] 2021-08-28 11:23
This doesn't look like an ng-packagr issue.

I was able to reproduce using ngc directly and therefore this is more TypeScript/Angular Compiler issue. That being said, since View Engine is at it's end of life, it's unlikely that this will be addressed unless it was a regression. 

```
ngc -p projects/my-lib/tsconfig.lib.prod.json 
RangeError: Maximum call stack size exceeded
    at speculationHelper (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:11669:26)
    at Object.lookAhead (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:11704:20)
    at speculationHelper (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:30307:27)
    at lookAhead (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:30326:20)
    at isStartOfFunctionTypeOrConstructorType (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:32263:58)
    at parseTypeWorker (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:32341:17)
    at doOutsideOfContext (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:30153:20)
    at parseType (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:32338:20)
    at parseTypeParameter (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:31528:34)
    at parseListElement (/workspace/test-ngpackager/node_modules/typescript/lib/typescript.js:30876:20)
```

Using Ivy in partial mode, is the way to go here since it will also be the only supported way to ship libraries in version 13.

**Closed by alan-agius4** 2021-08-28 11:23 UTC
