### ISSUE TITLE
False detection of potential dependency

### ISSUE THREAD

**Issue by shlomiassaf** [ng-packagr/ng-packagr#1982] opened 2021-05-19 22:22 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

The source analyser will detect internal, dependant package via this logic:

https://github.com/ng-packagr/ng-packagr/blob/c2efc42591ea8f2581cb7c8d3ea16a6b9cfa526e/src/lib/ng-package/entry-point/analyse-sources.transform.ts#L62-L71

This matching logic is very simple, assuming every module resolved that starts with the current package name is a secondary, internal package. This is not always the case.

There are several scenarios that can fail this.

For example, I have a package `@scope/A` and an internal package `@scope/A/B`

`@scope/A` does import from `@scope/B` thus it will get picked up by the logic above, at some point.  
However, if I reference an internal part in `@scope/B`, like `@scope/B/internal/path` it will get caught and since
it's not actually a library it will throw an exception

`ERROR: Entry point @scope/B/internal/path which is required by @scope/A doesn't exists.`
 
Now, we might say that referencing  `@scope/B/internal/path` might not be valid and we better reference it in a relative way, which is OK i guess.

However, i'm not physically referencing it, in my scenario i'm just augmenting a type in  `@scope/B` which is located at  `@scope/B/internal/path`.

```ts
declare module '@scope/B/internal/path' {
  interface MyAugmentedInterface {
    str: string;
  }
}
```

This one goes through the resolution pipeline, although type only, and so throws an exception.

In general the logic to detected internal packages is very inclusive and I didn't find an option that allows setting excluded paths or some way of modifiying the behaviour.

I don't want to augment via relative paths because the output structure might not fit the source file structure.
So the location of the augmented `.d.ts` in the output dist should not be relative but absolute. When absolute it will work in development as well as packaged 

Regardless, personally I think that this method of detecting child packages is very "generous". Maybe some conventions should be in place. For example, the directory of the child path must have a `package.json` with at least the "name" property of the package included. This looks like a reasonable convention to me.

#### Version Information

```
ng-packagr:            12.0.0
@angular/compiler:     12.0.0
rollup:                2.48.0
typescript:            4.2.4
```

**Comment by alan-agius4** [comment] 2021-05-25 08:37
The reason why the check is there, is so that when users forget to declare a sub-entrypoint as such we fail with an actionable error message.

**Comment by matheo** [comment] 2021-05-26 17:38
Thanks @alan-agius4 now I will try to upgrade my monorepo of libraries :)

**Comment by shlomiassaf** [comment] 2021-05-27 11:10
@alan-agius4 This did not solve the issue.

There's an additional check to detect `d.ts` files but augmentation is not about `d.ts` at all times.
I can augment a type in a regular `.ts` file.

I understand why this check is in place but it is restrictive.  
It detects false dependencies.

At least, until you figure out how to tackle this, let control the level of severity.  
Let it throw and error by default but add an opt-in option in `ng-packagr.json` to reduce it to a warning or ignore it so I can control some of it.

In general, the resolver does not provide information about the referenced module which means you can't really detect if the import comes from augmentation or not.

**Comment by alan-agius4** [comment] 2021-05-28 15:45
I will try to look into this next week, that said adding an option is not is not really on the table since this will need to be supported for at least 2 major versions.

**Comment by dschwank** [comment] 2021-06-09 15:28
The exclusion of `.d.ts` is causing some issues on our side right now. Version `12.0.0` is working fine, but since `12.0.1` (first version with this fix) we get the following error:

```
Building Angular Package
ERROR: Debug Failure. False expression.
Error: Process completed with exit code 1.
```

The reason is, that we have a `/// <reference types="cypress" />` in one of our files. With this fix typescript will end up with a resource it can't resolve. Our current fix is to stick with version `12.0.0`.

**Comment by JoMen6** [comment] 2021-06-09 15:46
@dschwank  I run into the same issue. The problem is this assertion https://github.com/microsoft/TypeScript/blob/main/src/compiler/program.ts#L2911

I removed this line and the build runs successfully, but i think this assertion is there for some reason.

My current solution is also stepping back to version 12.0.0.

**Comment by alan-agius4** [comment] 2021-06-09 16:49
@JoMen6 & @dschwank, I have a fix for your case https://github.com/ng-packagr/ng-packagr/pull/2003 which will be released later on today.

**Comment by JoMen6** [comment] 2021-06-10 07:38
@alan-agius4 It works, thank you very much :pray:

**Comment by dschwank** [comment] 2021-06-10 10:33
@alan-agius4 Thanks a lot for the quick support! It works nice for us 🥳

**Closed** 2024-01-25 10:00 UTC
Labels: bug
