### ISSUE TITLE
Library that imports JSON file breaks the application build

### ISSUE THREAD

**Issue by klemenoslaj** [ng-packagr/ng-packagr#1705] opened 2020-07-23 09:59 UTC
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

Consuming the library containing a JSON import fails on application build with the following error (library itself is built successfully with both Ivy and ViewEngine):

```
ERROR in dist/library/public-api.d.ts:1:36 - error TS2307: Cannot find module './example.json' or its corresponding type declarations.

1 export { default as numbers } from './example.json';
```

Adding `"skipLibCheck": true,` to `tsconfig.base.json` silences this error. Ivy built library works fine after that, ViewEngine built library fails with following error:

```
ERROR in The target entry-point "library" has missing dependencies:
 - ./example.json
```

#### How To Reproduce

Checkout the repository: https://github.com/klemenoslaj/ng-package-json-import
Execute: `yarn && build:lib-ivy` - This works fine!
Execute: `yarn && build:lib-ve` - **This breaks**!

---

Remove `skipLibCheck` from `tsconfig.base.json` to fail for both Ivy and ViewEngine.

#### Expected Behaviour

Application should successfully compile when consuming a library with imported JSON.

#### Version Information

```
ng-packagr:            10.0.3
@angular/compiler:     10.0.5
rollup:                2.22.2
tsickle:               
typescript:            3.9.7
```

**Comment by SchnWalter** [comment] 2020-08-14 10:48
I took a quick glance and I saw that you are missing an `"resolveJsonModule": true` in `compilerOptions` for `tsconfig.base.json`

**Comment by klemenoslaj** [comment] 2020-08-15 18:31
> I took a quick glance and I saw that you are missing an `"resolveJsonModule": true` in `compilerOptions` for `tsconfig.base.json`
> 
> Also, you should never use `skipLibCheck`.

Are you sure? I am on a phone but i can see the resolveJsonModule in tsconfig.base.json: https://www.github.com/klemenoslaj/ng-package-json-import/tree/master/tsconfig.base.json

**Comment by alan-agius4** [comment] 2020-11-11 10:57
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/1496

**Closed by alan-agius4** 2020-11-11 10:57 UTC
