### ISSUE TITLE
Support building individual entrypoints alone

### ISSUE THREAD

**Issue by daiscog** [ng-packagr/ng-packagr#2776] opened 2024-01-26 13:53 UTC
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

Add support for building a single secondary (or primary) entrypoint in isolation.

Currently, all entrypoints are built together in one single operation.  To make more efficient use of tools like `nx` that allow build caching, it would be useful to be able to build a single entrypoint alone.  This way, I can break down building my npm package into several separate, cacheable operations and not have to rebuild the entire package every time one entrypoint changes.

**Comment by alan-agius4** [comment] 2024-01-26 14:20
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/2732

**Closed by alan-agius4** 2024-01-26 14:20 UTC
