### ISSUE TITLE
No name was provided for external module

### ISSUE THREAD

**Issue by ralberts** [ng-packagr/ng-packagr#730] opened 2018-03-27 14:32 UTC
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[x] Not sure :-)
```

## Description

Once I upgraded to 2.2.0 I started seeing this error and I have tried so many things... any help would be greatly appreciated.

> No name was provided for external module 'commonjs-proxy:jquery' in options.globals – guessing 'require$$0'

I have the following ng-package.json defined:

```
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "lib": {
    "entryFile": "public_api.ts",
    "embedded": ["ng-fullcalendar", "fullcalendar"],
    "umdModuleIds": {
      "jquery": "$",
      "moment": "moment",
      "commonjs-proxy:jquery": "$"  // Tried with this in and out
    }
  },
  "whitelistedNonPeerDependencies": ["."]
}

```

It seems like it's an issue with the "fullcalendar" (https://github.com/fullcalendar/fullcalendar).  It is compiled with webpack and looking at the dist file - it seems like it should work with rollup.  Though I always get confused on the different bundling methods.

#### How To Reproduce

I will edit this with reproducing steps and will look at if it's possible to break an integration test.  Just thought I would put this out there first in case it's something really obvious.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.4.1
@angular/compiler:     5.2.9
@angular/compiler-cli: 5.2.9
rollup:                0.55.5
tsickle:               0.27.2
typescript:            2.5.3
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by noelmace** [comment] 2018-03-27 15:31
duplicate of https://github.com/dherges/ng-packagr/issues/579 
see the documentation here : https://github.com/dherges/ng-packagr/blob/master/README.md#third-party-dependencies-external-and-embedded-dependencies

**Comment by ralberts** [comment] 2018-03-27 16:31
To totally show that I don't know what I am doing - I found that adding the following to the commonJs() options in the rollupPlugins - worked around the error:
```
        const rollupPlugins = [
            nodeResolve({ jsnext: true, module: true }),
            commonJs({
                    ignore: ['jquery', 'moment'] // <-- Adding this line in the rollup file in this project

```
Hoping this helps give a clue to what I might have wrong.

**Comment by tommck** [comment] 2018-04-04 18:25
does that `"moment": "moment",` work for you?

**Comment by codeNoobie** [comment] 2018-04-05 20:16
@dherges @tommck I am new to using ng-packagr. I am getting the above errors as well. 

I have declared a bunch of external libraries as peerDependencies. I do not want to include any code from third party in our bundle. But when i run ng-packagr, I get these errors. What does these errors mean? Is it trying to include the code from the third party libs and it would exactly do that if add those libs in the `external` array.

My goal is to not include anything from third party lib. The consumer of my lib will have to provide those external libs to make it work. What am i missing? 

Thanks in advance for helping!

**Comment by adarowiec** [comment] 2018-10-15 10:28
any resolve?

**Comment by alan-agius4** [comment] 2018-11-30 08:30
Kindly check the documentation here https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md

**Closed** 2018-11-30 08:32 UTC
