### ISSUE TITLE
Barrel files (*.d.ts) created in dist from secondary endpoint "Cannot find module" of external libraries

### ISSUE THREAD

**Issue by polonmedia** [ng-packagr/ng-packagr#2702] opened 2023-10-10 12:41 UTC
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description

Im refactoring a big library of components from one entry point to multiple second entries. I managed to resolve all of the imports and circular dependencies but the build process is failing.
![image](https://github.com/ng-packagr/ng-packagr/assets/59230634/252143c4-87ce-4d10-8183-dda01ff50de2)

The secondary entries are importing themselves obviously (via @paths/secondary) and there is no issue there. What is the problem is that there is no explenation in documentation how to handle such case as above - lacking external libraries. What I've found so far is to preseverSymlinks in tsconfig but adding that to workspace tsconfig and/or library tsconfig did not change anything.
My paths are as following:
![image](https://github.com/ng-packagr/ng-packagr/assets/59230634/3ccfbafd-7aa0-412b-9eee-b05552c7d680)
and they are added to both tsconfigs of workspace and lib.

So what is the solution here? I went through old, closed issues but nothing seem to work or even be the exact problem I have, as it seems that I've done everything correct up to this point. Should I add paths for the
`"@cytiva/cui-design-ng": [
  "dist/cui-design-ng/*",
  "dist/cui-design-ng"
]` dist part of them? That's how it's done? Seems counter-productive to add every used peerDependecy of the lib to the dist build pathMapping. Speaking of this, I should also mentioned that the peerDeps are added to the lib's package.json, and installed in the workspace. I even tried to install them in the library location with its own node_modules but this also did not work. 

#### Expected Behaviour

The problems people seem to face quite frequently are not described in the documentation. If there could be a described process of how to handle such cases in libraries with more than 2 components and external libraries would be great. Or even the process of ng-packager itself, instead of trying to read about it from a developer response in closed or half-resolved issues from 2019.

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
"ng-packagr": "^16.0.0",
@angular/*:"^16.0.0"
typescript:"~4.9.5"
rxjs:"~6.5.5"
node: 16.14.0
npm/yarn: 8.3.1
```

**Comment by polonmedia** [comment] 2023-10-10 12:45
@JoostK @SchnWalter @alan-agius4 Im sorry for spamming you but this is something that needs to be somehow resolved and is blocking development of a library done right from your Secondary Entry Points example.

**Comment by polonmedia** [comment] 2023-10-10 13:59
![image](https://github.com/ng-packagr/ng-packagr/assets/59230634/0cfa00b6-941a-481f-95e6-94cd664a50b6)
This seems to be viable working solution. But is it the correct way? Am I missing one tsconfig property to handle this for me? Or do I really need a specific paths to node_modules for every external library my lib uses?

**Comment by alan-agius4** [comment] 2023-11-07 11:05
Closing since no reproduction was provided.

**Closed by alan-agius4** 2023-11-07 11:05 UTC
Labels: needs reproduction
