### ISSUE TITLE
Module not found: Error: can't resolve the component. Facing issue when trying to import component from a package made using ng-packagr.

### ISSUE THREAD

**Issue by aditimalviya** [ng-packagr/ng-packagr#1117] opened 2018-10-15 06:29 UTC
## Description
I have exported the package from a different app and trying to use that package in a different application as a dependency. I am getting the following error when trying to import components from that package.
ERROR in ./src/app/core/component-dynamic-loader/component-dynamic-loader.component.ts
Module not found: Error: Can't resolve 'avanade-packagr/src/app/modules/xd-components/xd-list-view/xd-list-view.component'
in 'C:\Users\aditi.malviya\work\xd.ng.starter.demo.app\src\app\core\component-dynamic-loader'

#### How To Reproduce

**index.ts:**
export * from './xd-components.module';
**public_api.ts:**
export * from './src/app/modules/xd-components/index';

**ng-package.json:**
{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "lib": {
      "entryFile": "public_api.ts"
    },
     "externals": {
        "moment": "moment",
        "lodash": "lodash"
      }
  }
**commands:**
npm run packagr
cd dist
npm pack
npm install "package url"

**import statement:**
import { XdListViewComponent } from 'avanade-packagr/src/app/modules/xd-components/xd-list-view/xd-list-view.component';

#### Expected Behaviour

_A bug: The component should get imported in the app from the package.

#### Version Information

```
$ node_modules/.bin/ng-packagr --5.10.0
"ng-packagr": "^1.7.0",
@angular/*: ^4.2.6
typescript:  "~2.4.2"
rxjs: "^5.4.0"
```

**Comment by dreamerkumar** [comment] 2018-10-22 18:14
See if it works after deleting your index.ts and importing directly. Barreling has got some issues.

**Comment by aditimalviya** [comment] 2018-10-24 03:55
Yeah. I tried that too. But it doesn't seem to work even after directly importing.

**Comment by babeal** [comment] 2018-11-13 20:41
why are you importing from this path?  ```import { XdListViewComponent } from 'avanade-packagr/src/app/modules/xd-components/xd-list-view/xd-list-view.component';```?  Shouldn't the import statement just be ```import { XdListViewComponent } from 'avanade-packagr'```

**Comment by alan-agius4** [comment] 2019-11-11 07:03
Duplicate of https://github.com/ng-packagr/ng-packagr/issues/917

**Closed by alan-agius4** 2019-11-11 07:03 UTC

**Comment by FarkasAndras93** [comment] 2020-03-27 07:34
> why are you importing from this path? `import { XdListViewComponent } from 'avanade-packagr/src/app/modules/xd-components/xd-list-view/xd-list-view.component';`? Shouldn't the import statement just be `import { XdListViewComponent } from 'avanade-packagr'`

In my case, this worked. I have a self-made angular library and my import was:
import { MyHomeComponentModule } from 'my-home-page-component/public-api';

then I switched to:
import { MyHomeComponentModule } from 'my-home-page-component';

and my build problems disappeared.
